Repository DistributedCollective/sovryn-dapp, pull requests merged in 2022-10, with the labels that each got.

#17 SOV-107 - base GTM configuration
  .gitignore
  apps/frontend/.env.example
  apps/frontend/README.md
  apps/frontend/public/index.html
  apps/frontend/src/app/5_pages/App/App.tsx
Labels: enhancement

#14 feat: add Link atomic component
  packages/tailwindcss-config/index.js
  packages/ui/src/1_atoms/Link/Link.module.css
  packages/ui/src/1_atoms/Link/Link.stories.tsx
  packages/ui/src/1_atoms/Link/Link.test.tsx
  packages/ui/src/1_atoms/Link/Link.tsx
  packages/ui/src/1_atoms/Link/Link.types.ts
  packages/ui/src/1_atoms/index.tsx
Labels: enhancement

#18 feat: add badge atomic component
  packages/ui/src/1_atoms/Badge/Badge.module.css
  packages/ui/src/1_atoms/Badge/Badge.stories.tsx
  packages/ui/src/1_atoms/Badge/Badge.test.tsx
  packages/ui/src/1_atoms/Badge/Badge.tsx
  packages/ui/src/1_atoms/Badge/Badge.types.ts
  packages/ui/src/1_atoms/index.tsx
  packages/ui/src/2_molecules/Dropdown/Dropdown.module.css
Labels: enhancement

#13 Paragraph component implementation
  apps/frontend/src/app/3_organisms/EthersProviderTest.tsx
  apps/frontend/src/styles/tailwindcss/base.css
  packages/ui/__mocks__/styleMock.js
  packages/ui/jest.config.js
  packages/ui/package.json
  packages/ui/src/1_atoms/Paragraph/Paragraph.module.css
  packages/ui/src/1_atoms/Paragraph/Paragraph.stories.tsx
  packages/ui/src/1_atoms/Paragraph/Paragraph.test.tsx
  packages/ui/src/1_atoms/Paragraph/Paragraph.tsx
  packages/ui/src/1_atoms/Paragraph/Paragraph.types.ts
  packages/ui/src/1_atoms/index.tsx
  packages/ui/styles/base.css
  yarn.lock
Labels: enhancement

#16 [Dropdown] - update component
  packages/ui/src/2_molecules/Dropdown/Dropdown.module.css
  packages/ui/src/2_molecules/Dropdown/Dropdown.stories.tsx
  packages/ui/src/2_molecules/Dropdown/Dropdown.test.tsx
  packages/ui/src/2_molecules/Dropdown/Dropdown.tsx
  packages/ui/src/2_molecules/Dropdown/Dropdown.types.ts
  packages/ui/src/2_molecules/Menu/components/MenuItem/MenuItem.module.css
Labels: enhancement

#23 [NavMenuItem] - implement component
  packages/ui/src/1_atoms/Badge/Badge.module.css
  packages/ui/src/2_molecules/NavMenuItem/NavMenuItem.module.css
  packages/ui/src/2_molecules/NavMenuItem/NavMenuItem.stories.tsx
  packages/ui/src/2_molecules/NavMenuItem/NavMenuItem.test.tsx
  packages/ui/src/2_molecules/NavMenuItem/NavMenuItem.tsx
Labels: enhancement

#21 [Heading] - add component
  packages/ui/src/1_atoms/Heading/Heading.module.css
  packages/ui/src/1_atoms/Heading/Heading.stories.tsx
  packages/ui/src/1_atoms/Heading/Heading.test.tsx
  packages/ui/src/1_atoms/Heading/Heading.tsx
  packages/ui/src/1_atoms/Heading/Heading.types.ts
  packages/ui/src/1_atoms/index.tsx
  packages/ui/styles/base.css
Labels: enhancement

#26 feat: add forwardRef to interactive components SOV-698
  packages/ui/src/1_atoms/Button/Button.test.tsx
  packages/ui/src/1_atoms/Button/Button.tsx
  packages/ui/src/1_atoms/Input/Input.test.tsx
  packages/ui/src/2_molecules/Dropdown/Dropdown.test.tsx
  packages/ui/src/2_molecules/Dropdown/Dropdown.tsx
  yarn.lock
Labels: enhancement

#24 feat: add Tabs component
  packages/tailwindcss-config/index.js
  packages/ui/src/1_atoms/Tabs/Tabs.module.css
  packages/ui/src/1_atoms/Tabs/Tabs.stories.tsx
  packages/ui/src/1_atoms/Tabs/Tabs.test.tsx
  packages/ui/src/1_atoms/Tabs/Tabs.tsx
  packages/ui/src/1_atoms/Tabs/Tabs.types.ts
  packages/ui/src/1_atoms/Tabs/components/Tab/Tab.module.css
  packages/ui/src/1_atoms/Tabs/components/Tab/Tab.tsx
Labels: enhancement

#29 Sov 742 d 2 UI library data action id updates
  apps/frontend/src/app/2_molecules/ConnectWalletButton/ConnectWalletButton.tsx
  apps/frontend/src/app/5_pages/App/App.tsx
  packages/ui/jest.setup.js
  packages/ui/src/1_atoms/Badge/Badge.test.tsx
  packages/ui/src/1_atoms/Badge/Badge.tsx
  packages/ui/src/1_atoms/Button/Button.tsx
  packages/ui/src/1_atoms/Heading/Heading.tsx
  packages/ui/src/1_atoms/Icon/Icon.tsx
  packages/ui/src/1_atoms/Input/Input.test.tsx
  packages/ui/src/1_atoms/Input/Input.tsx
  packages/ui/src/1_atoms/InputBase/InputBase.tsx
  packages/ui/src/1_atoms/Lead/Lead.module.css
  packages/ui/src/1_atoms/Lead/Lead.stories.tsx
  packages/ui/src/1_atoms/Lead/Lead.tsx
  packages/ui/src/1_atoms/Link/Link.test.tsx
  packages/ui/src/1_atoms/Link/Link.tsx
  packages/ui/src/1_atoms/Paragraph/Paragraph.tsx
  packages/ui/src/1_atoms/index.tsx
  packages/ui/src/2_molecules/Dialog/Dialog.stories.tsx
  packages/ui/src/2_molecules/Dialog/Dialog.tsx
  packages/ui/src/2_molecules/Dialog/components/DialogHeader/DialogHeader.tsx
  packages/ui/src/2_molecules/Dropdown/Dropdown.test.tsx
  packages/ui/src/2_molecules/Dropdown/Dropdown.tsx
  packages/ui/src/2_molecules/Menu/components/MenuItem/MenuItem.tsx
  packages/ui/src/2_molecules/NavMenuItem/NavMenuItem.stories.tsx
  packages/ui/src/2_molecules/NavMenuItem/NavMenuItem.tsx
  packages/ui/src/2_molecules/Overlay/Overlay.tsx
  packages/ui/src/2_molecules/WalletIdentity/WalletIdentity.stories.tsx
  packages/ui/src/2_molecules/WalletIdentity/WalletIdentity.test.tsx
  packages/ui/src/2_molecules/WalletIdentity/WalletIdentity.tsx
  packages/ui/src/2_molecules/WalletIdentity/components/AddressBadge/AddressBadge.tsx
  packages/ui/src/2_molecules/WalletIdentity/components/DisconnectSubmenu/DisconnectSubmenu.tsx
Labels: refactoring

#31 chore/tabs-updates-SOV-848
  packages/ui/src/2_molecules/Tabs/Tabs.module.css
  packages/ui/src/2_molecules/Tabs/Tabs.stories.tsx
  packages/ui/src/2_molecules/Tabs/Tabs.test.tsx
  packages/ui/src/2_molecules/Tabs/Tabs.tsx
  packages/ui/src/2_molecules/Tabs/Tabs.types.ts
  packages/ui/src/2_molecules/Tabs/components/Tab/Tab.module.css
  packages/ui/src/2_molecules/Tabs/components/Tab/Tab.tsx
  packages/ui/src/2_molecules/index.ts
Labels: refactoring

#33 chore(actions): automation for package releases
  .github/workflows/release.yml
  package.json
Labels: enhancement

#34 chore: configure changesets
  .changeset/README.md
  .changeset/config.json
  .changeset/smart-pugs-shave.md
  package.json
  yarn.lock
Labels: enhancement

#28 [Tooltip] - add component
  .changeset/rotten-pugs-enjoy.md
  packages/ui/src/2_molecules/Tooltip/Tooltip.module.css
  packages/ui/src/2_molecules/Tooltip/Tooltip.stories.tsx
  packages/ui/src/2_molecules/Tooltip/Tooltip.test.tsx
  packages/ui/src/2_molecules/Tooltip/Tooltip.tsx
  packages/ui/src/2_molecules/Tooltip/Tooltip.types.ts
  packages/ui/src/2_molecules/Tooltip/Tooltip.utils.ts
  packages/ui/src/2_molecules/index.ts
  packages/ui/src/types/index.ts
Labels: enhancement

#30 SOV-580: vertical tabs component
  .changeset/nice-bananas-deliver.md
  .prettierignore
  package.json
  packages/ui/.eslintrc.js
  packages/ui/.storybook/preview.js
  packages/ui/.storybook/tailwind.css
  packages/ui/src/2_molecules/VerticalTabs/VerticalTabs.module.css
  packages/ui/src/2_molecules/VerticalTabs/VerticalTabs.stories.tsx
  packages/ui/src/2_molecules/VerticalTabs/VerticalTabs.test.tsx
  packages/ui/src/2_molecules/VerticalTabs/VerticalTabs.tsx
  packages/ui/src/2_molecules/VerticalTabs/VerticalTabs.types.ts
  packages/ui/src/2_molecules/VerticalTabs/components/VerticalTabItem.module.css
  packages/ui/src/2_molecules/VerticalTabs/components/VerticalTabItem.tsx
  packages/ui/src/2_molecules/VerticalTabs/index.tsx
  packages/ui/src/2_molecules/index.ts
Labels: enhancement

#47 Accordion Component SOV-567
  .changeset/warm-icons-provide.md
  packages/ui/src/1_atoms/Accordion/Accordion.module.css
  packages/ui/src/1_atoms/Accordion/Accordion.stories.tsx
  packages/ui/src/1_atoms/Accordion/Accordion.test.tsx
  packages/ui/src/1_atoms/Accordion/Accordion.tsx
  packages/ui/src/1_atoms/Accordion/index.ts
  packages/ui/src/1_atoms/Icon/Icon.types.ts
  packages/ui/src/1_atoms/Icon/iconNames.ts
  packages/ui/src/1_atoms/Icon/iconSvgPaths.ts
  packages/ui/src/1_atoms/index.tsx
Labels: enhancement

#42 feat: simple table component
  .changeset/happy-buses-reply.md
  packages/ui/src/1_atoms/Icon/Icon.types.ts
  packages/ui/src/2_molecules/SimpleTable/SimpleTable.module.css
  packages/ui/src/2_molecules/SimpleTable/SimpleTable.stories.tsx
  packages/ui/src/2_molecules/SimpleTable/SimpleTable.test.tsx
  packages/ui/src/2_molecules/SimpleTable/SimpleTable.tsx
  packages/ui/src/2_molecules/SimpleTable/components/SimpleTableRow/SimpleTableRow.module.css
  packages/ui/src/2_molecules/SimpleTable/components/SimpleTableRow/SimpleTableRow.tsx
  packages/ui/src/2_molecules/SimpleTable/index.ts
  packages/ui/src/2_molecules/index.ts
Labels: enhancement

#52 chore: export TransactionId comps via index.ts
  packages/ui/src/2_molecules/TransactionId/index.ts
  packages/ui/src/2_molecules/index.ts
Labels: refactoring

#45 Feat/sov 789 d 2 header component
  .changeset/fifty-days-hope.md
  apps/frontend/src/styles/tailwindcss/components.css
  packages/ui/__mocks__/svgMock.js
  packages/ui/assets/images/logo-sovryn.svg
  packages/ui/jest.config.js
  packages/ui/src/1_atoms/Button/Button.test.tsx
  packages/ui/src/2_molecules/Header/Header.module.css
  packages/ui/src/2_molecules/Header/Header.stories.tsx
  packages/ui/src/2_molecules/Header/Header.test.tsx
  packages/ui/src/2_molecules/Header/Header.tsx
  packages/ui/src/2_molecules/Header/index.ts
  packages/ui/src/2_molecules/index.ts
  packages/ui/src/custom.d.ts
Labels: enhancement

#53 feat: add onboard walletconnect
  .changeset/poor-jars-crash.md
  .changeset/silly-bobcats-hope.md
  apps/frontend/craco.config.js
  apps/frontend/package.json
  apps/frontend/src/lib/connector.ts
  packages/ui/src/1_atoms/Icon/Icon.types.ts
  yarn.lock
Labels: enhancement

#57 [StatusItem] - add component
  .changeset/curly-socks-tickle.md
  packages/ui/src/1_atoms/Icon/iconSvgPaths.ts
  packages/ui/src/2_molecules/StatusItem/StatusItem.module.css
  packages/ui/src/2_molecules/StatusItem/StatusItem.stories.tsx
  packages/ui/src/2_molecules/StatusItem/StatusItem.test.tsx
  packages/ui/src/2_molecules/StatusItem/StatusItem.tsx
  packages/ui/src/2_molecules/StatusItem/StatusItem.types.ts
  packages/ui/src/2_molecules/StatusItem/StatusItem.utils.ts
  packages/ui/src/2_molecules/StatusItem/index.ts
  packages/ui/src/2_molecules/index.ts
Labels: enhancement

#56 fix: export missing components
  .changeset/fast-oranges-share.md
  packages/ui/src/2_molecules/TransactionId/TransactionId.tsx
  packages/ui/src/2_molecules/index.ts
Labels: bug

#55 SOV-568: radio button component implementation
  .changeset/fifty-days-hope.md
  .changeset/happy-buses-reply.md
  .changeset/serious-kiwis-shake.md
  .changeset/tidy-monkeys-tap.md
  .changeset/warm-icons-provide.md
  packages/tailwindcss-config/index.js
  packages/ui/src/2_molecules/RadioButton/RadioButton.module.css
  packages/ui/src/2_molecules/RadioButton/RadioButton.stories.tsx
  packages/ui/src/2_molecules/RadioButton/RadioButton.test.tsx
  packages/ui/src/2_molecules/RadioButton/RadioButton.tsx
  packages/ui/src/2_molecules/RadioButton/RadioButton.types.ts
  packages/ui/src/2_molecules/RadioButton/index.ts
  packages/ui/src/2_molecules/RadioButtonGroup/RadioButtonGroup.module.css
  packages/ui/src/2_molecules/RadioButtonGroup/RadioButtonGroup.stories.tsx
  packages/ui/src/2_molecules/RadioButtonGroup/RadioButtonGroup.test.tsx
  packages/ui/src/2_molecules/RadioButtonGroup/RadioButtonGroup.tsx
  packages/ui/src/2_molecules/RadioButtonGroup/RadioButtonGroup.types.ts
  packages/ui/src/2_molecules/RadioButtonGroup/index.ts
  packages/ui/src/2_molecules/index.ts
Labels: enhancement

#59 SOV-861 - refactor data-layout-id prop names to constant
  .changeset/tiny-chefs-brush.md
  packages/ui/jest.setup.js
  packages/ui/src/1_atoms/Accordion/Accordion.test.tsx
  packages/ui/src/1_atoms/Accordion/Accordion.tsx
  packages/ui/src/1_atoms/Badge/Badge.tsx
  packages/ui/src/1_atoms/Button/Button.tsx
  packages/ui/src/1_atoms/Heading/Heading.tsx
  packages/ui/src/1_atoms/Icon/Icon.tsx
  packages/ui/src/1_atoms/Input/Input.tsx
  packages/ui/src/1_atoms/InputBase/InputBase.tsx
  packages/ui/src/1_atoms/Link/Link.tsx
  packages/ui/src/1_atoms/Paragraph/Paragraph.tsx
  packages/ui/src/2_molecules/AddressTablePagination/AddressTablePagination.tsx
  packages/ui/src/2_molecules/Dialog/Dialog.tsx
  packages/ui/src/2_molecules/Dialog/components/DialogHeader/DialogHeader.tsx
  packages/ui/src/2_molecules/Dropdown/Dropdown.tsx
  packages/ui/src/2_molecules/Header/Header.tsx
  packages/ui/src/2_molecules/Menu/components/MenuItem/MenuItem.tsx
  packages/ui/src/2_molecules/NavMenuItem/NavMenuItem.tsx
  packages/ui/src/2_molecules/Overlay/Overlay.tsx
  packages/ui/src/2_molecules/SimpleTable/SimpleTable.tsx
  packages/ui/src/2_molecules/SimpleTable/components/SimpleTableRow/SimpleTableRow.tsx
  packages/ui/src/2_molecules/StatusItem/StatusItem.tsx
  packages/ui/src/2_molecules/Tabs/components/Tab/Tab.tsx
  packages/ui/src/2_molecules/Tooltip/Tooltip.test.tsx
  packages/ui/src/2_molecules/Tooltip/Tooltip.tsx
  packages/ui/src/2_molecules/TransactionId/TransactionId.tsx
  packages/ui/src/2_molecules/VerticalTabs/components/VerticalTabItem.tsx
  packages/ui/src/2_molecules/WalletContainer/WalletContainer.tsx
  packages/ui/src/2_molecules/WalletIdentity/WalletIdentity.test.tsx
  packages/ui/src/2_molecules/WalletIdentity/components/AddressBadge/AddressBadge.tsx
  packages/ui/src/types/index.ts
  packages/ui/src/utils/constants.ts
  packages/ui/src/utils/index.ts
Labels: refactoring
