Repository DistributedCollective/sovryn-dapp, pull requests merged in 2023-03, with the labels that each got.

#247 SOV-1870: update metadata
  .changeset/wet-seals-complain.md
  apps/frontend/public/assets/636103ef1f7e59d03648f98f_Borrow_hero_gradient.jpg
  apps/frontend/public/index.html
  apps/frontend/public/manifest.json
Labels: enhancement

#248 SOV-1884: notification dialog close bug
  .changeset/long-poems-sin.md
  apps/frontend/src/app/2_molecules/ConnectWalletButton/ConnectWalletButton.tsx
Labels: bug

#246 SOV-1702: fix pending icon spin direction
  .changeset/angry-birds-film.md
  apps/frontend/src/app/5_pages/ConvertPage/ConvertPage.tsx
  packages/tailwindcss-config/index.js
  packages/ui/src/1_atoms/Icon/iconSvgPaths.ts
Labels: bug

#260 SOV-1792: Fix collateral surplus history table
  .changeset/stupid-tigers-grow.md
  apps/frontend/src/app/3_organisms/CollateralSurplusWithdrawals/CollateralSurplusWithdrawals.tsx
  apps/frontend/src/utils/math.ts
Labels: bug

#262 SOV-1847: fix crashing amount input
  .changeset/fluffy-zebras-return.md
  apps/frontend/src/app/5_pages/ConvertPage/ConvertPage.tsx
  apps/frontend/src/hooks/useAmountInput.ts
Labels: bug

#263 SOV-1784: fix number format
  .changeset/happy-phones-promise.md
  apps/frontend/src/app/2_molecules/AmountRenderer/AmountRenderer.tsx
  apps/frontend/src/app/2_molecules/SystemStats/components/ZeroStats.tsx
  apps/frontend/src/app/5_pages/EarnPage/EarnPage.tsx
  apps/frontend/src/utils/math.ts
Labels: bug

#249 SOV-913: service worker + dapp update dialog
  .changeset/shaggy-wombats-switch.md
  apps/frontend/.env.example
  apps/frontend/.env.staging
  apps/frontend/craco.config.js
  apps/frontend/package.json
  apps/frontend/public/index.html
  apps/frontend/public/release.json
  apps/frontend/src/README.md
  apps/frontend/src/app/1_atoms/.gitkeep
  apps/frontend/src/app/2_molecules/ServiceWorkerProvider/ServiceWorkerProvider.tsx
  apps/frontend/src/index.tsx
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/react-app-env.d.ts
  apps/frontend/src/service-worker.ts
  apps/frontend/src/serviceWorkerRegistration.ts
  apps/frontend/src/types/global.ts
  apps/frontend/src/utils/constants.ts
  packages/tailwindcss-config/index.js
  packages/ui/src/2_molecules/Notification/Notification.module.css
  packages/ui/src/2_molecules/Notification/Notification.types.ts
  packages/ui/src/2_molecules/Notification/Notification.utils.ts
  yarn.lock
Labels: enhancement

#251 SOV-1694: Fix min collateral error value in LoC
  .changeset/fair-readers-attack.md
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/OpenCreditLine.tsx
  apps/frontend/src/utils/math.ts
Labels: bug

#265 SOV-1648: User's LOC is not highlighted in the chart
  .changeset/tasty-items-join.md
  apps/frontend/src/app/3_organisms/LOCChart/LOCChart.tsx
  apps/frontend/src/app/3_organisms/LOCChart/hooks/useGetTroves.ts
  apps/frontend/src/app/3_organisms/LOCChart/hooks/useGetUserOpenTrove.ts
  apps/frontend/src/app/3_organisms/LOCChart/types.ts
  apps/frontend/src/app/5_pages/ZeroPage/ZeroPage.tsx
  apps/frontend/src/utils/helpers.ts
Labels: enhancement

#257 SOV-1674: Unconfirmed email address warning
  .changeset/great-dryers-clean.md
  apps/frontend/src/app/3_organisms/EmailNotificationSettingsDialog/EmailNotificationSettingsDialog.tsx
  apps/frontend/src/app/3_organisms/EmailNotificationSettingsDialog/EmailNotificationSettingsDialog.types.ts
  apps/frontend/src/locales/en/translations.json
Labels: enhancement

#259 SOV-1646: Add BTC TXID to Fast BTC send flow
  .changeset/khaki-rats-deliver.md
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/SendFlow/components/StatusScreen.tsx
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/utils/graphql/rsk/generated.tsx
  apps/frontend/src/utils/graphql/rsk/operations/getBitcoinTxId.graphql
Labels: enhancement

#272 SOV-1805: refactor LOC button position
  .changeset/grumpy-starfishes-bow.md
  apps/frontend/src/app/2_molecules/LOCStatus/LOCStatus.tsx
  apps/frontend/src/app/5_pages/ZeroPage/ZeroPage.tsx
Labels: enhancement

#270 SOV-1703: show build id
  .changeset/neat-oranges-allow.md
  apps/frontend/src/app/2_molecules/ServiceWorkerProvider/ServiceWorkerProvider.tsx
  apps/frontend/src/app/3_organisms/Footer/Footer.tsx
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/utils/constants.ts
  apps/frontend/src/utils/helpers.ts
Labels: enhancement

#273 SOV-1913: add description meta tags
  .changeset/sixty-crabs-float.md
  apps/frontend/public/index.html
  apps/frontend/src/locales/en/translations.json
Labels: enhancement

#276 chore: added email landing pages
  .changeset/tiny-laws-own.md
  apps/frontend/src/app/2_molecules/EmailVerificationState/EmailVerificationState.tsx
  apps/frontend/src/app/3_organisms/Footer/Footer.tsx
  apps/frontend/src/app/3_organisms/Header/Header.tsx
  apps/frontend/src/app/4_templates/EmailVerificationStateContainer/EmailVerificationStateContainer.tsx
  apps/frontend/src/app/5_pages/EmailDuplicateVerifiedPage/EmailDuplicateVerifiedPage.tsx
  apps/frontend/src/app/5_pages/EmailErrorPage/EmailErrorPage.tsx
  apps/frontend/src/app/5_pages/EmailUnsubscribedAllPage/EmailUnsubscribedAllPage.tsx
  apps/frontend/src/app/5_pages/EmailUnsubscribedPage/EmailUnsubscribedPage.tsx
  apps/frontend/src/app/5_pages/EmailVerifiedPage/EmailVerifiedPage.tsx
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/router.tsx
  apps/frontend/src/utils/constants.ts
Labels: enhancement

#258 SOV-1824: Use ErrorBadge component for all input errors
  .changeset/kind-ligers-end.md
  apps/frontend/src/app/3_organisms/ZeroLocForm/CloseCreditLine.tsx
  apps/frontend/src/app/5_pages/ConvertPage/ConvertPage.tsx
  apps/frontend/src/app/5_pages/EarnPage/EarnPage.tsx
  packages/ui/src/2_molecules/FormGroup/FormGroup.module.css
  packages/ui/src/2_molecules/FormGroup/FormGroup.test.tsx
  packages/ui/src/2_molecules/FormGroup/FormGroup.tsx
Labels: enhancement

#268 SOV-1614: update default gas limits
  .changeset/weak-gorillas-drum.md
  apps/frontend/src/app/5_pages/EarnPage/EarnPage.tsx
  apps/frontend/src/app/5_pages/EarnPage/hooks/useHandleStabilityDeposit.ts
  apps/frontend/src/app/5_pages/RewardsPage/hooks/useHandleRewards.ts
  apps/frontend/src/utils/constants.ts
Labels: enhancement

#261 SOV-1481: Add Notification after transactions confirm/fail
  .changeset/nervous-cars-lie.md
  apps/frontend/src/app/3_organisms/TransactionStepDialog/TransactionStepDialog.tsx
  apps/frontend/src/app/3_organisms/TransactionStepDialog/components/TransactionStep/TransactionStep.tsx
  apps/frontend/src/app/3_organisms/TransactionStepDialog/components/TransactionSteps/TransactionSteps.tsx
  apps/frontend/src/app/3_organisms/TransactionStepDialog/utils.ts
  apps/frontend/src/locales/en/translations.json
Labels: enhancement

#267 SOV-1915: fix error ordering
  .changeset/chilled-beers-draw.md
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/AdjustCreditLine.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/OpenCreditLine.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/utils.ts
  packages/ui/src/2_molecules/ErrorList/ErrorList.tsx
Labels: bug

#277 SOV-1780: reset amount inputs on Convert page after tx
  .changeset/plenty-lies-sparkle.md
  apps/frontend/src/app/5_pages/ConvertPage/ConvertPage.tsx
  apps/frontend/src/app/5_pages/ConvertPage/hooks/useHandleConversion.ts
Labels: enhancement

#269 SOV-1949: show label in Transfer Gains tx on Tx History
  .changeset/soft-mirrors-wonder.md
  apps/frontend/src/app/3_organisms/TransactionHistoryFrame/TransactionHistoryFrame.tsx
  apps/frontend/src/locales/en/translations.json
Labels: bug

#278 SOV-1820: toWei not handling scientific notation values
  .changeset/four-forks-explain.md
  apps/frontend/src/utils/math.test.ts
  apps/frontend/src/utils/math.ts
Labels: bug

#280 SOV-1481: notification-tx-update
  .changeset/polite-geckos-tickle.md
  apps/frontend/src/app/3_organisms/TransactionStepDialog/utils.ts
  apps/frontend/src/locales/en/translations.json
Labels: enhancement

#279 SOV-1985: Update MAX Amount component
  .changeset/thin-spies-drum.md
  apps/frontend/src/app/2_molecules/AmountRenderer/AmountRenderer.tsx
  apps/frontend/src/app/2_molecules/MaxButton/MaxButton.tsx
  apps/frontend/src/utils/constants.ts
Labels: bug

#284 SOV-1910: cleanup
  .changeset/beige-sheep-explain.md
  .prettierrc
  CODE_OF_CONDUCT.md
  apps/frontend/src/app/2_molecules/CollateralRatio/CollateralRatio.tsx
  apps/frontend/src/app/2_molecules/DebugContent.tsx
  apps/frontend/src/app/2_molecules/ExampleBalanceCall.tsx
  apps/frontend/src/app/2_molecules/ExampleContractCall.tsx
  apps/frontend/src/app/2_molecules/ExampleProviderCall.tsx
  apps/frontend/src/app/2_molecules/ExampleTokenDetails.tsx
  apps/frontend/src/app/2_molecules/ExampleTypedDataSign.tsx
  apps/frontend/src/app/2_molecules/LOCStatus/LOCStatus.tsx
  apps/frontend/src/app/2_molecules/SmartTokens.tsx
  apps/frontend/src/app/2_molecules/SystemStats/components/EcosystemStats.tsx
  apps/frontend/src/app/2_molecules/SystemStats/components/ZeroStats.tsx
  apps/frontend/src/app/3_organisms/LOCChart/hooks/useGetRBTCPrice.ts
  apps/frontend/src/app/3_organisms/TransactionStepDialog/components/TransactionStep/TransactionStep.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/CloseCreditLine.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/CurrentTroveData.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/FormContent.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/hooks/useZeroData.ts
  apps/frontend/src/app/5_pages/App/App.tsx
  apps/frontend/src/app/5_pages/EarnPage/EarnPage.tsx
  apps/frontend/src/app/5_pages/RewardsPage/RewardsPage.tsx
  apps/frontend/src/app/5_pages/ZeroPage/ZeroPage.tsx
  apps/frontend/src/app/5_pages/ZeroPage/hooks/useHandleTrove.ts
  apps/frontend/src/app/5_pages/ZeroPage/loader.ts
  apps/frontend/src/app/5_pages/ZeroPage/utils/trove-manager.ts
  apps/frontend/src/app/5_pages/ZeroPage/utils/zero-provider.ts
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/router.tsx
  apps/frontend/src/store/.gitkeep
  apps/frontend/src/utils/liquity.ts
  packages/contracts/src/contracts/tokens/rsk.ts
  packages/contracts/src/contracts/tokens/rskTestnet.ts
Labels: refactoring

#281 SOV-1915: error message for LOC
  .changeset/tricky-humans-drum.md
  apps/frontend/src/app/3_organisms/ZeroLocForm/utils.ts
  apps/frontend/src/locales/en/translations.json
Labels: bug

#286 SOV-1763: Origination fee calculation/display in history table
  .changeset/forty-spoons-develop.md
  apps/frontend/src/app/3_organisms/TransactionHistoryFrame/TransactionHistoryFrame.tsx
Labels: bug

#287 SOV-1807: Update how "max borrow amount" on Adjust modal is calculated
  .changeset/empty-jeans-visit.md
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/AdjustCreditLine.tsx
Labels: enhancement

#285 SOV-1996: Ensure tooltips display full value
  .changeset/warm-radios-yell.md
  apps/frontend/src/app/2_molecules/AmountRenderer/AmountRenderer.tsx
Labels: enhancement

#292 SOV-2011: 404 page
  .changeset/six-swans-perform.md
  apps/frontend/src/app/3_organisms/Footer/Footer.tsx
  apps/frontend/src/app/4_templates/EmailVerificationStateContainer/EmailVerificationStateContainer.tsx
  apps/frontend/src/app/5_pages/ErrorPage/ErrorPage.tsx
  apps/frontend/src/app/5_pages/NotFoundPage/NotFoundPage.tsx
  apps/frontend/src/locales/en/translations.json
Labels: enhancement

#293 SOV-1581: LOC Dialog is using custom Secondary Tabs implementation
  .changeset/many-cheetahs-doubt.md
  apps/frontend/src/app/3_organisms/ZeroLocForm/Label.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/FormContent.tsx
Labels: enhancement

#296 fix: getting started popup issue
  apps/frontend/src/app/3_organisms/NetworkProvider/NetworkProvider.tsx
  apps/frontend/src/app/5_pages/ZeroPage/ZeroPage.tsx
Labels: bug

#289 SOV-1987 handle scientific numbers on AmountRenderer
  .changeset/olive-otters-design.md
  apps/frontend/src/app/2_molecules/AmountRenderer/AmountRenderer.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/AdjustCreditLine.tsx
  apps/frontend/src/utils/math.ts
Labels: bug

#294 SOV-1910: cleanup
  .changeset/early-eggs-sin.md
  apps/frontend/package.json
  apps/frontend/src/app/2_molecules/DashboardWelcomeBanner/components/ConnectedUserBanner/ConnectedUserBanner.tsx
  apps/frontend/src/app/2_molecules/SystemStats/components/EcosystemStats.tsx
  apps/frontend/src/app/2_molecules/SystemStats/components/ZeroStats.tsx
  apps/frontend/src/app/2_molecules/TransactionTypeRenderer/TransactionTypeRenderer.tsx
  apps/frontend/src/app/3_organisms/Footer/Footer.tsx
  apps/frontend/src/app/3_organisms/RewardHistory/RewardHistory.tsx
  apps/frontend/src/app/3_organisms/StabilityPoolHistoryFrame/StabilityPoolHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/TransactionHistoryFrame/TransactionHistoryFrame.tsx
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/utils/constants.ts
  packages/contracts/package.json
  yarn.lock
Labels: refactoring

#298 SOV-1910: update banner images
  .changeset/tough-apricots-reply.md
  apps/frontend/src/assets/images/Desktop_Banner_1.2.svg
  apps/frontend/src/assets/images/Mobile_Banner.svg
Labels: enhancement, do-not-merge

#300 SOV-2045: Fix history frame signs
  .changeset/spicy-toes-camp.md
  apps/frontend/src/app/3_organisms/StabilityPoolHistoryFrame/StabilityPoolHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/TransactionHistoryFrame/TransactionHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/TransactionHistoryFrame/utils.ts
  apps/frontend/src/locales/en/translations.json
Labels: bug

#302 fix: dapp crashes when gas has decimal
  apps/frontend/src/utils/helpers.ts
Labels: bug

#306 SOV-2049 fix permit issues
  .changeset/cold-yaks-judge.md
  apps/frontend/src/app/1_atoms/LedgerPermitLocked/LedgerPermitLocked.tsx
  apps/frontend/src/app/3_organisms/TransactionStepDialog/components/TransactionSteps/TransactionSteps.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/CloseCreditLine.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/FormContent.tsx
  apps/frontend/src/app/5_pages/EarnPage/EarnPage.tsx
  apps/frontend/src/hooks/useAccount.ts
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/utils/constants.ts
  apps/frontend/src/utils/permit/lib.ts
  apps/frontend/src/utils/permit/permit.ts
  apps/frontend/src/utils/permit/rpc.ts
Labels: bug

#307 SOV-1841: mainnet release
  .changeset/popular-adults-camp.md
  apps/frontend/public/release.json
Labels: enhancement

#297 SOV-2012: Add correct hash to Fast BTC receive flow
  .changeset/four-dolphins-invent.md
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/ReceiveFlow/ReceiveFlow.tsx
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/ReceiveFlow/components/StatusScreen.tsx
  apps/frontend/src/app/3_organisms/FastBtcDialog/contexts/deposit-context.ts
  apps/frontend/src/app/3_organisms/FundingHistoryFrame/utils.tsx
  apps/frontend/src/utils/graphql/rsk/generated.tsx
  apps/frontend/src/utils/graphql/rsk/operations/getFastBtcDepositRskTransaction.graphql
  apps/frontend/src/utils/graphql/rsk/schema.graphql
Labels: enhancement

#291 SOV-1943: new collateral ratio must be increased in recovery mode
  .changeset/tame-countries-act.md
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/AdjustCreditLine.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/utils.ts
  apps/frontend/src/locales/en/translations.json
Labels: bug

#316 SOV-2089: update zdk version/zero fees
  .changeset/wicked-rats-guess.md
  apps/frontend/package.json
  packages/contracts/package.json
  yarn.lock
Labels: bug, enhancement

#301 SOV-1988: consistent casting cleanup
  .changeset/wise-knives-change-contract.md
  .changeset/wise-knives-change.md
  README.md
  apps/frontend/package.json
  apps/frontend/src/app/2_molecules/AmountRenderer/AmountRenderer.tsx
  apps/frontend/src/app/2_molecules/AssetValue/AssetValue.tsx
  apps/frontend/src/app/2_molecules/AssetValue/types.ts
  apps/frontend/src/app/2_molecules/CollateralRatio/CollateralRatio.tsx
  apps/frontend/src/app/2_molecules/LOCStatus/LOCStatus.tsx
  apps/frontend/src/app/2_molecules/MaxButton/MaxButton.tsx
  apps/frontend/src/app/2_molecules/SystemStats/components/EcosystemStats.tsx
  apps/frontend/src/app/2_molecules/SystemStats/components/ZeroStats.tsx
  apps/frontend/src/app/2_molecules/SystemStats/hooks/useGetAssetBalance.ts
  apps/frontend/src/app/2_molecules/SystemStats/hooks/useGetAssetBalanceByAddress.ts
  apps/frontend/src/app/2_molecules/SystemStats/hooks/useGetTotalSupply.ts
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/SendFlow/components/AmountForm.tsx
  apps/frontend/src/app/3_organisms/TransactionStepDialog/TransactionStepDialog.tsx
  apps/frontend/src/app/3_organisms/TransactionStepDialog/components/TransactionStep/TransactionStep.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/CloseCreditLine.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/CurrentTroveData.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/Label.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/AdjustCreditLine.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/FormContent.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/OpenCreditLine.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/constants.ts
  apps/frontend/src/app/3_organisms/ZeroLocForm/hooks/useZeroData.ts
  apps/frontend/src/app/3_organisms/ZeroLocForm/utils.ts
  apps/frontend/src/app/5_pages/ConvertPage/ConvertPage.tsx
  apps/frontend/src/app/5_pages/ConvertPage/hooks/useGetMaximumAvailableAmount.ts
  apps/frontend/src/app/5_pages/EarnPage/EarnPage.tsx
  apps/frontend/src/app/5_pages/EarnPage/hooks/useHandleStabilityDeposit.ts
  apps/frontend/src/app/5_pages/RewardsPage/RewardsPage.tsx
  apps/frontend/src/app/5_pages/ZeroPage/ZeroPage.tsx
  apps/frontend/src/app/5_pages/ZeroPage/loader.ts
  apps/frontend/src/hooks/useAssetBalance.ts
  apps/frontend/src/hooks/useGasPrice.ts
  apps/frontend/src/hooks/useGetContract.ts
  apps/frontend/src/hooks/useLoadContract.ts
  apps/frontend/src/hooks/useMaxAssetBalance.ts
  apps/frontend/src/utils/helpers.ts
  apps/frontend/src/utils/math.ts
  packages/contracts/src/tokenDetails/index.ts
  packages/contracts/src/tokenDetails/logos/mynt.ts
  packages/contracts/src/types.ts
  packages/ui/src/1_atoms/DynamicValue/DynamicValue.tsx
  packages/utils/.babelrc.js
  packages/utils/.gitignore
  packages/utils/README.md
  packages/utils/package.json
  packages/utils/src/index.ts
  packages/utils/src/math/Decimal.test.ts
  packages/utils/src/math/Decimal.ts
  packages/utils/src/math/Percent.ts
  packages/utils/src/math/index.ts
  packages/utils/tsconfig.json
  packages/utils/tsup.config.js
  yarn.lock
Labels: refactoring

#314 SOV-1758: Implement new notification signup user flow
  .changeset/lovely-feet-deliver.md
  apps/frontend/src/app/3_organisms/EmailNotificationSettingsDialog/EmailNotificationSettingsDialog.tsx
  apps/frontend/src/app/3_organisms/EmailNotificationSettingsDialog/EmailNotificationSettingsDialog.utils.ts
  apps/frontend/src/app/3_organisms/EmailNotificationSettingsDialog/components/Subscriptions.tsx
  apps/frontend/src/app/3_organisms/EmailNotificationSettingsDialog/hooks/useHandleSubscriptions.ts
  apps/frontend/src/locales/en/translations.json
Labels: enhancement

#322 SOV-1919: Page/chart is cut after the page refresh
  .changeset/nervous-islands-walk.md
  packages/ui/src/2_molecules/Overlay/Overlay.tsx
Labels: enhancement

#323 SOV-2060: Long decimal precision on Transaction Dialog amounts
  .changeset/empty-beers-exist.md
  apps/frontend/src/app/3_organisms/TransactionStepDialog/components/TransactionStep/TransactionStep.tsx
Labels: enhancement

#324 SOV-2056: Convert page amount inputs not always resetting after tx
  .changeset/famous-ties-worry.md
  apps/frontend/src/app/5_pages/ConvertPage/ConvertPage.tsx
  apps/frontend/src/app/5_pages/ConvertPage/hooks/useHandleConversion.ts
Labels: enhancement
