Repository DistributedCollective/sovryn-dapp, pull requests merged in 2023-02, with the labels that each got.

#189 SOV-1446: Update Convert page copy
  .changeset/itchy-jars-sit.md
  apps/frontend/src/app/5_pages/ConvertPage/ConvertPage.tsx
  packages/ui/src/2_molecules/Header/Header.module.css
Labels: enhancement

#182 SOV-1515: opening and repaying trove using DLLR
  .changeset/rare-poems-hug.md
  apps/frontend/src/app/3_organisms/ZeroLocForm/AdjustCreditLine.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/types.ts
  apps/frontend/src/app/5_pages/ZeroPage/constants.ts
  apps/frontend/src/app/5_pages/ZeroPage/hooks/useHandleTrove.ts
  apps/frontend/src/app/5_pages/ZeroPage/utils/trove-manager.ts
Labels: bug

#191 SOV-1310: Zero welcome dashboard banner implementation
  .changeset/tall-bottles-share.md
  apps/frontend/src/app/2_molecules/DashboardWelcomeBanner/DashboardWelcomeBanner.tsx
  apps/frontend/src/app/2_molecules/DashboardWelcomeBanner/components/ConnectedUserBanner/ConnectedUserBanner.tsx
  apps/frontend/src/app/2_molecules/LOCStatus/LOCStatus.tsx
  apps/frontend/src/app/3_organisms/Header/Header.tsx
  apps/frontend/src/app/3_organisms/LOCChart/LOCChart.tsx
  apps/frontend/src/app/5_pages/ZeroPage/ZeroPage.tsx
  apps/frontend/src/assets/images/Desktop_Banner_1.2.svg
  apps/frontend/src/assets/images/Mobile_Banner.svg
  apps/frontend/src/hooks/useIsMobile.ts
  apps/frontend/src/styles/tailwindcss/variables.css
  apps/frontend/src/utils/helpers.ts
Labels: enhancement

#185 SOV-1440: Integrate Getting Started popup
  .changeset/tiny-buckets-reply.md
  apps/frontend/src/app/3_organisms/GettingStartedPopup/GettingStartedPopup.module.css
  apps/frontend/src/app/3_organisms/GettingStartedPopup/GettingStartedPopup.tsx
  apps/frontend/src/app/5_pages/ZeroPage/ZeroPage.tsx
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/utils/constants.ts
Labels: enhancement

#190 SOV-1484: Update styling
  .changeset/mighty-cameras-doubt.md
  apps/frontend/src/app/3_organisms/Header/Header.tsx
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/styles/tailwindcss/variables.css
Labels: enhancement

#192 SOV-1673: Fix "close line of credit" modal, SOV-1678: fix option
  .changeset/strong-lemons-refuse.md
  apps/frontend/src/app/3_organisms/TransactionHistoryFrame/TransactionHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/CloseCreditLine.tsx
  apps/frontend/src/app/5_pages/ZeroPage/ZeroPage.tsx
  apps/frontend/src/utils/constants.ts
Labels: enhancement

#195 SOV-1610: Use BTC instead RBTC everywhere
  .changeset/spotty-ladybugs-wonder.md
  apps/frontend/src/app/2_molecules/LOCStatus/LOCStatus.tsx
  apps/frontend/src/app/2_molecules/SystemStats/components/EcosystemStats.tsx
  apps/frontend/src/app/2_molecules/SystemStats/components/ZeroStats.tsx
  apps/frontend/src/app/3_organisms/CollateralSurplusWithdrawals/CollateralSurplusWithdrawals.tsx
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/ReceiveFlow/components/StatusScreen.tsx
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/ReceiveFlow/components/TransferPolicies.tsx
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/SendFlow/components/AmountForm.tsx
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/SendFlow/components/ReviewScreen.tsx
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/SendFlow/components/StatusScreen.tsx
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/SendFlow/components/TransferPolicies.tsx
  apps/frontend/src/app/3_organisms/FastBtcDialog/constants.ts
  apps/frontend/src/app/3_organisms/LOCChart/LOCChart.tsx
  apps/frontend/src/app/3_organisms/RedemptionsHistoryFrame/RedemptionsHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/TransactionHistoryFrame/TransactionHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/AdjustCreditLine.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/CloseCreditLine.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/CurrentTroveData.tsx
  apps/frontend/src/app/5_pages/ZeroPage/hooks/useClaimCollateralSurplus.ts
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/utils/constants.ts
  packages/ui/src/2_molecules/AmountInput/AmountInput.stories.tsx
  packages/ui/src/2_molecules/Table/Table.stories.tsx
  packages/ui/src/2_molecules/TableBase/TableBase.stories.tsx
  packages/ui/src/2_molecules/TableBase/TableBase.test.tsx
Labels: bug

#183 SOV-1118: Zero: SP transactions history frame
  .changeset/cuddly-pans-grow.md
  apps/frontend/src/app/2_molecules/TransactionTypeRenderer/TransactionTypeRenderer.tsx
  apps/frontend/src/app/3_organisms/StabilityPoolHistoryFrame/StabilityPoolHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/StabilityPoolHistoryFrame/hooks/useGetStabilityPoolHistory.ts
  apps/frontend/src/app/3_organisms/StabilityPoolHistoryFrame/index.ts
  apps/frontend/src/app/5_pages/HistoryPage/HistoryPage.tsx
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/utils/graphql/zero/generated.tsx
  apps/frontend/src/utils/graphql/zero/operations/getStabilityPool.graphql
Labels: enhancement

#197 SOV-1590: Remove hardcoded value in statistics
  .changeset/soft-dogs-rush.md
  apps/frontend/src/app/2_molecules/SystemStats/components/EcosystemStats.tsx
  apps/frontend/src/app/2_molecules/SystemStats/components/ZeroStats.tsx
  apps/frontend/src/utils/math.ts
Labels: bug

#199 SOV-1492: Update Email Notification dialog copy
  .changeset/great-suns-beam.md
  apps/frontend/src/app/3_organisms/EmailNotificationSettingsDialog/EmailNotificationSettingsDialog.tsx
  apps/frontend/src/locales/en/translations.json
Labels: enhancement

#187 SOV-1517: fix number inputs
  .changeset/early-pets-explain.md
  apps/frontend/src/app/3_organisms/ZeroLocForm/AdjustCreditLine.tsx
  apps/frontend/src/locales/en/translations.json
  packages/ui/package.json
  packages/ui/src/1_atoms/Input/Input.stories.tsx
  packages/ui/src/1_atoms/Input/Input.test.tsx
  packages/ui/src/1_atoms/InputBase/InputBase.tsx
  packages/ui/src/1_atoms/InputBase/utils.ts
  packages/ui/src/2_molecules/AmountInput/AmountInput.stories.tsx
  packages/ui/src/2_molecules/AmountInput/AmountInput.test.tsx
  packages/ui/src/2_molecules/AmountInput/AmountInput.tsx
  packages/ui/src/utils/helpers.ts
  yarn.lock
Labels: bug

#194 Batch of LOC issues
  .changeset/rotten-cars-deny.md
  apps/frontend/src/app/3_organisms/ZeroLocForm/AdjustCreditLine.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/CurrentTroveData.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/AdjustCreditLine.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/FormContent.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/OpenCreditLine.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/hooks/useZeroData.ts
  apps/frontend/src/app/3_organisms/ZeroLocForm/types.ts
  apps/frontend/src/app/3_organisms/ZeroLocForm/utils.ts
  apps/frontend/src/app/5_pages/ZeroPage/ZeroPage.tsx
  apps/frontend/src/hooks/useCall.ts
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/utils/constants.ts
  packages/ui/src/2_molecules/FormGroup/FormGroup.tsx
Labels: bug

#202 SOV-1452: Define gas limits
  .changeset/fuzzy-mirrors-tie.md
  apps/frontend/src/app/5_pages/ConvertPage/hooks/useHandleConversion.ts
  apps/frontend/src/app/5_pages/RewardsPage/hooks/useHandleRewards.ts
  apps/frontend/src/app/5_pages/ZeroPage/hooks/useHandleTrove.ts
  apps/frontend/src/utils/constants.ts
Labels: enhancement

#193 SOV-1122: Conversions history frame
  .changeset/young-crews-nail.md
  apps/frontend/.env.example
  apps/frontend/.env.staging
  apps/frontend/codegen.fetch.yml
  apps/frontend/codegen.yml
  apps/frontend/src/app/3_organisms/CollateralSurplusWithdrawals/CollateralSurplusWithdrawals.tsx
  apps/frontend/src/app/3_organisms/ConversionsHistoryFrame/ConversionsHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/ConversionsHistoryFrame/components/AssetAmountCell/AssetAmountCell.tsx
  apps/frontend/src/app/3_organisms/ConversionsHistoryFrame/hooks/useGetConversionsHistory.ts
  apps/frontend/src/app/3_organisms/ConversionsHistoryFrame/utils.tsx
  apps/frontend/src/app/3_organisms/Header/Header.tsx
  apps/frontend/src/app/3_organisms/RedemptionsHistoryFrame/RedemptionsHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/TransactionHistoryFrame/TransactionHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/TransactionHistoryFrame/hooks/useGetTroves.ts
  apps/frontend/src/app/5_pages/HistoryPage/HistoryPage.tsx
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/utils/clients.ts
  apps/frontend/src/utils/constants.ts
  apps/frontend/src/utils/graphql/mynt/generated.tsx
  apps/frontend/src/utils/graphql/mynt/operations/getConversions.graphql
  apps/frontend/src/utils/graphql/mynt/schema.graphql
  apps/frontend/src/utils/graphql/rsk/generated.tsx
  apps/frontend/src/utils/graphql/rsk/schema.graphql
  apps/frontend/src/utils/graphql/zero/generated.tsx
  apps/frontend/src/utils/graphql/zero/schema.graphql
Labels: enhancement

#205 SOV-1701: Update footer links
  .changeset/shiny-paws-design.md
  apps/frontend/src/app/3_organisms/Footer/Footer.tsx
  apps/frontend/src/utils/constants.ts
Labels: enhancement

#206 SOV-1701: Update footer logo
  .changeset/blue-wombats-reflect.md
  apps/frontend/src/app/3_organisms/Footer/Footer.tsx
  apps/frontend/src/assets/images/Bitcoin-logo-small.svg
Labels: enhancement

#201 SOV-1586: trigger funding flow from anywhere within dapp
  .changeset/spicy-ties-cough.md
  apps/frontend/src/app/2_molecules/DashboardWelcomeBanner/components/ConnectedUserBanner/ConnectedUserBanner.tsx
  apps/frontend/src/app/3_organisms/Header/Header.tsx
  apps/frontend/src/app/3_organisms/NetworkProvider/NetworkProvider.tsx
  apps/frontend/src/app/3_organisms/SharedStateProvider/SharedStateProvider.tsx
  apps/frontend/src/index.tsx
  apps/frontend/src/store/rxjs/shared-state.ts
Labels: enhancement

#208 SOV-1755: Hide funding button on testnet
  .changeset/fresh-buckets-sniff.md
  apps/frontend/.env.example
  apps/frontend/src/app/3_organisms/Header/Header.tsx
  apps/frontend/src/utils/helpers.ts
Labels: enhancement

#210 SOV-1768: toWei method for really small numbers
  .changeset/real-pillows-leave.md
  apps/frontend/src/app/5_pages/EarnPage/EarnPage.tsx
  apps/frontend/src/utils/math.test.ts
  apps/frontend/src/utils/math.ts
Labels: bug

#204 SOV-1551: refresh dapp info when block changes
  .changeset/eighty-mayflies-lie.md
  apps/frontend/src/app/2_molecules/DebugContent.tsx
  apps/frontend/src/app/2_molecules/SystemStats/components/ZeroStats.tsx
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/SendFlow/components/ReviewScreen.tsx
  apps/frontend/src/app/3_organisms/TransactionStepDialog/components/TransactionStep/TransactionStep.tsx
  apps/frontend/src/app/5_pages/ConvertPage/ConvertPage.tsx
  apps/frontend/src/app/5_pages/ConvertPage/hooks/useGetMaximumAvailableAmount.ts
  apps/frontend/src/app/5_pages/RewardsPage/RewardsPage.tsx
  apps/frontend/src/hooks/useAssetBalance.ts
  apps/frontend/src/index.tsx
  apps/frontend/src/store/rxjs/provider-cache.ts
Labels: enhancement

#212 SOV-1664: Zero Dashboard Chart Fix
  .changeset/chilled-crabs-compare.md
  apps/frontend/src/app/3_organisms/LOCChart/LOCChart.tsx
  apps/frontend/src/app/3_organisms/LOCChart/types.ts
  apps/frontend/src/utils/graphql/zero/generated.tsx
  apps/frontend/src/utils/graphql/zero/operations/getTroves.graphql
  apps/frontend/src/utils/graphql/zero/operations/getTrovesAbove.graphql
  apps/frontend/src/utils/graphql/zero/operations/getTrovesBelow.graphql
  apps/frontend/src/utils/graphql/zero/operations/getUserOpenTrove.graphql
Labels: bug

#215 SOV-1501: Fix broken border on Tooltip when shown in modals
  .changeset/happy-tomatoes-accept.md
  packages/ui/src/2_molecules/Tooltip/Tooltip.module.css
Labels: enhancement

#179 SOV-1521: deduct fees from collateral
  .changeset/bright-flowers-applaud.md
  .changeset/sharp-cars-wink.md
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/AdjustCreditLine.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/FormContent.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/OpenCreditLine.tsx
  apps/frontend/src/app/5_pages/ZeroPage/ZeroPage.tsx
  apps/frontend/src/hooks/useAsync.ts
  apps/frontend/src/hooks/useGasPrice.ts
  apps/frontend/src/hooks/useMaxAssetBalance.ts
  packages/ui/src/2_molecules/AmountInput/AmountInput.tsx
Labels: bug

#220 Fast BTC fixes
  .changeset/many-trainers-tap.md
  apps/frontend/src/app/3_organisms/FastBtcDialog/FastBtcDialog.tsx
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/ReceiveFlow/components/StatusScreen.tsx
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/SendFlow/components/AmountForm.tsx
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/SendFlow/components/StatusScreen.tsx
Labels: bug

#224 SOV-1579: message and typed data signing
  .changeset/clever-forks-reply.md
  apps/frontend/src/app/2_molecules/DebugContent.tsx
  apps/frontend/src/app/2_molecules/ExampleTypedDataSign.tsx
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/SendFlow/components/ConfirmationScreens.tsx
  apps/frontend/src/app/3_organisms/TransactionStepDialog/TransactionStepDialog.types.ts
  apps/frontend/src/app/3_organisms/TransactionStepDialog/components/TransactionStep/TransactionStep.tsx
  apps/frontend/src/app/3_organisms/TransactionStepDialog/components/TransactionSteps/TransactionSteps.tsx
  apps/frontend/src/app/3_organisms/TransactionStepDialog/helpers.ts
  apps/frontend/src/app/5_pages/ConvertPage/hooks/useHandleConversion.ts
  apps/frontend/src/app/5_pages/EarnPage/hooks/useHandleStabilityDeposit.ts
  apps/frontend/src/app/5_pages/RewardsPage/hooks/useHandleRewards.ts
  apps/frontend/src/app/5_pages/ZeroPage/hooks/useClaimCollateralSurplus.ts
  apps/frontend/src/app/5_pages/ZeroPage/hooks/useHandleTrove.ts
  apps/frontend/src/utils/helpers.ts
Labels: enhancement

#218 SOV-1488: refactor error badge component
  .changeset/empty-moles-report.md
  apps/frontend/src/app/1_atoms/ErrorBadge/ErrorBadge.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/AdjustCreditLine.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/FormContent.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/OpenCreditLine.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/utils.ts
  packages/ui/src/1_atoms/ErrorBadge/ErrorBadge.module.css
  packages/ui/src/1_atoms/ErrorBadge/ErrorBadge.stories.tsx
  packages/ui/src/1_atoms/ErrorBadge/ErrorBadge.test.tsx
  packages/ui/src/1_atoms/ErrorBadge/ErrorBadge.tsx
  packages/ui/src/1_atoms/ErrorBadge/ErrorBadge.types.ts
  packages/ui/src/1_atoms/ErrorBadge/ErrorBadge.utils.tsx
  packages/ui/src/1_atoms/ErrorBadge/index.tsx
  packages/ui/src/1_atoms/index.tsx
  packages/ui/src/2_molecules/ErrorList/ErrorList.stories.tsx
  packages/ui/src/2_molecules/ErrorList/ErrorList.test.tsx
  packages/ui/src/2_molecules/ErrorList/ErrorList.tsx
  packages/ui/src/2_molecules/ErrorList/index.tsx
  packages/ui/src/2_molecules/index.ts
Labels: enhancement

#230 SOV-1136: fix funding history
  apps/frontend/src/app/3_organisms/FundingHistoryFrame/FundingHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/FundingHistoryFrame/types.ts
  apps/frontend/src/app/3_organisms/FundingHistoryFrame/utils.tsx
  apps/frontend/src/locales/en/translations.json
Labels: bug

#216 SOV-1767: dynamic collateral amount
  .changeset/strong-camels-prove.md
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/OpenCreditLine.tsx
Labels: bug

#207 SOV-1464: default amount input is empty string instead of 0
  .changeset/odd-spies-admire.md
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/AdjustCreditLine.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/FormContent.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/OpenCreditLine.tsx
  apps/frontend/src/app/5_pages/ConvertPage/ConvertPage.tsx
  apps/frontend/src/app/5_pages/EarnPage/EarnPage.tsx
  apps/frontend/src/hooks/useAmountInput.ts
  apps/frontend/src/hooks/useWeiAmountInput.ts
  packages/ui/src/1_atoms/InputBase/InputBase.tsx
  packages/ui/src/2_molecules/AmountInput/AmountInput.tsx
Labels: bug

#234 SOV-1626: Replace useTranslation() hook usage with direct "t" import
  .changeset/pink-vans-argue.md
  apps/frontend/src/app/2_molecules/CollateralRatio/CollateralRatio.tsx
  apps/frontend/src/app/2_molecules/ConnectWalletButton/ConnectWalletButton.tsx
  apps/frontend/src/app/2_molecules/DebugContent.tsx
  apps/frontend/src/app/2_molecules/ExportCSV/ExportCSV.tsx
  apps/frontend/src/app/2_molecules/LOCStatus/LOCStatus.tsx
  apps/frontend/src/app/2_molecules/SocialLinks/SocialLinks.tsx
  apps/frontend/src/app/2_molecules/SystemStats/components/EcosystemStats.tsx
  apps/frontend/src/app/2_molecules/SystemStats/components/ZeroStats.tsx
  apps/frontend/src/app/2_molecules/TransactionTypeRenderer/TransactionTypeRenderer.tsx
  apps/frontend/src/app/3_organisms/CollateralSurplusWithdrawals/CollateralSurplusWithdrawals.tsx
  apps/frontend/src/app/3_organisms/EmailNotificationSettingsDialog/EmailNotificationSettingsDialog.tsx
  apps/frontend/src/app/3_organisms/EmailNotificationSettingsDialog/components/Subscriptions.tsx
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/Instructions.tsx
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/Limits.tsx
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/ReceiveFlow/components/AddressForm.tsx
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/SendFlow/components/AmountForm.tsx
  apps/frontend/src/app/3_organisms/GettingStartedPopup/GettingStartedPopup.tsx
  apps/frontend/src/app/3_organisms/Header/Header.tsx
  apps/frontend/src/app/3_organisms/LOCChart/LOCChart.tsx
  apps/frontend/src/app/3_organisms/RedemptionsHistoryFrame/RedemptionsHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/RewardHistory/RewardHistory.tsx
  apps/frontend/src/app/3_organisms/StabilityPoolHistoryFrame/StabilityPoolHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/TransactionHistoryFrame/TransactionHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/TransactionStepDialog/components/TransactionSteps/TransactionSteps.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/CloseCreditLine.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/CurrentTroveData.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/AdjustCreditLine.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/FormContent.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/OpenCreditLine.tsx
  apps/frontend/src/app/5_pages/ConvertPage/ConvertPage.tsx
  apps/frontend/src/app/5_pages/EarnPage/EarnPage.tsx
  apps/frontend/src/app/5_pages/ErrorPage/ErrorPage.tsx
  apps/frontend/src/app/5_pages/HistoryPage/HistoryPage.tsx
  apps/frontend/src/app/5_pages/RewardsPage/RewardsPage.tsx
  apps/frontend/src/app/5_pages/RewardsPage/hooks/useHandleRewards.ts
  apps/frontend/src/app/5_pages/ZeroPage/hooks/useHandleTrove.ts
  apps/frontend/src/hooks/useWrongNetworkCheck.tsx
Labels: enhancement

#226 SOV-1360: integrate new maintenance states
  .changeset/gorgeous-waves-type.md
  apps/frontend/src/app/1_atoms/DappLocked/DappLocked.tsx
  apps/frontend/src/app/3_organisms/CollateralSurplusWithdrawals/CollateralSurplusWithdrawals.tsx
  apps/frontend/src/app/3_organisms/ConversionsHistoryFrame/ConversionsHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/ReceiveFlow/components/MainScreen.tsx
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/SendFlow/components/AddressForm.tsx
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/SendFlow/components/AmountForm.tsx
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/SendFlow/components/MainScreen.tsx
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/SendFlow/components/ReviewScreen.tsx
  apps/frontend/src/app/3_organisms/RedemptionsHistoryFrame/RedemptionsHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/RewardHistory/RewardHistory.tsx
  apps/frontend/src/app/3_organisms/StabilityPoolHistoryFrame/StabilityPoolHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/TransactionHistoryFrame/TransactionHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/CloseCreditLine.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/FormContent.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/utils.ts
  apps/frontend/src/app/4_templates/PageContainer/PageContainer.tsx
  apps/frontend/src/app/5_pages/ConvertPage/ConvertPage.tsx
  apps/frontend/src/app/5_pages/EarnPage/EarnPage.tsx
  apps/frontend/src/app/5_pages/RewardsPage/RewardsPage.tsx
  apps/frontend/src/locales/en/translations.json
  packages/ui/src/1_atoms/ErrorBadge/ErrorBadge.tsx
  packages/ui/src/1_atoms/ErrorBadge/ErrorBadge.types.ts
  packages/ui/src/2_molecules/ErrorList/ErrorList.tsx
Labels: enhancement

#228 SOV-1636: update README.md
  .changeset/two-apples-build.md
  CODE_OF_CONDUCT.md
  LICENSE
  README.md
  apps/frontend/package.json
Labels: documentation, enhancement

#225 SOV-1666: add data attributes to tx flow
  .changeset/long-knives-clap.md
  apps/frontend/src/app/2_molecules/LanguageSelector/LanguageSelector.tsx
  apps/frontend/src/app/3_organisms/CollateralSurplusWithdrawals/CollateralSurplusWithdrawals.tsx
  apps/frontend/src/app/3_organisms/ConversionsHistoryFrame/ConversionsHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/FastBtcDialog/FastBtcDialog.tsx
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/MobileCloseButton.tsx
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/ReceiveFlow/ReceiveFlow.tsx
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/ReceiveFlow/components/AddressForm.tsx
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/ReceiveFlow/components/MainScreen.tsx
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/ReceiveFlow/components/StatusScreen.tsx
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/SendFlow/SendFlow.tsx
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/SendFlow/components/AddressForm.tsx
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/SendFlow/components/AmountForm.tsx
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/SendFlow/components/MainScreen.tsx
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/SendFlow/components/ReviewScreen.tsx
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/SendFlow/components/StatusScreen.tsx
  apps/frontend/src/app/3_organisms/RedemptionsHistoryFrame/RedemptionsHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/RewardHistory/RewardHistory.tsx
  apps/frontend/src/app/3_organisms/StabilityPoolHistoryFrame/StabilityPoolHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/TransactionStepDialog/components/TransactionStep/TransactionStep.tsx
  apps/frontend/src/app/3_organisms/TransactionStepDialog/components/TransactionSteps/TransactionSteps.tsx
  apps/frontend/src/app/5_pages/RewardsPage/RewardsPage.tsx
Labels: enhancement

#236 SOV-1497: Update external link icon color
  .changeset/dry-scissors-deliver.md
  packages/ui/src/2_molecules/Menu/components/MenuItem/MenuItem.module.css
Labels: enhancement

#233 SOV-1661: Copy TX ID -> standard browser confirmation is shown
  .changeset/orange-walls-attend.md
  apps/frontend/src/app/2_molecules/TxIdWithNotification/TransactionIdWithNotification.tsx
  apps/frontend/src/app/3_organisms/CollateralSurplusWithdrawals/CollateralSurplusWithdrawals.tsx
  apps/frontend/src/app/3_organisms/ConversionsHistoryFrame/components/TransactionIdRenderer/TransactionIdRenderer.tsx
  apps/frontend/src/app/3_organisms/ConversionsHistoryFrame/utils.tsx
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/ReceiveFlow/components/StatusScreen.tsx
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/SendFlow/components/ReviewScreen.tsx
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/SendFlow/components/StatusScreen.tsx
  apps/frontend/src/app/3_organisms/RedemptionsHistoryFrame/RedemptionsHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/RewardHistory/RewardHistory.tsx
  apps/frontend/src/app/3_organisms/StabilityPoolHistoryFrame/StabilityPoolHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/TransactionHistoryFrame/TransactionHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/TransactionStepDialog/components/TransactionStep/TransactionStep.tsx
  apps/frontend/src/hooks/useCopyAddress.ts
  apps/frontend/src/index.tsx
  packages/ui/src/2_molecules/TransactionId/TransactionId.tsx
Labels: enhancement

#232 SOV-1578: single transaction DLLR
  .changeset/chilled-otters-complain.md
  apps/frontend/package.json
  apps/frontend/src/app/2_molecules/DashboardWelcomeBanner/components/ConnectedUserBanner/ConnectedUserBanner.tsx
  apps/frontend/src/app/2_molecules/ExampleBalanceCall.tsx
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/SendFlow/components/AmountForm.tsx
  apps/frontend/src/app/3_organisms/Header/Header.tsx
  apps/frontend/src/app/3_organisms/LOCChart/LOCChart.tsx
  apps/frontend/src/app/3_organisms/TransactionStepDialog/TransactionStepDialog.types.ts
  apps/frontend/src/app/3_organisms/TransactionStepDialog/components/TransactionStep/TransactionStep.tsx
  apps/frontend/src/app/3_organisms/TransactionStepDialog/components/TransactionSteps/TransactionSteps.tsx
  apps/frontend/src/app/3_organisms/TransactionStepDialog/helpers.ts
  apps/frontend/src/app/3_organisms/ZeroLocForm/CloseCreditLine.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/AdjustCreditLine.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/OpenCreditLine.tsx
  apps/frontend/src/app/5_pages/ConvertPage/ConvertPage.tsx
  apps/frontend/src/app/5_pages/ConvertPage/hooks/useGetDefaultSourceToken.ts
  apps/frontend/src/app/5_pages/ConvertPage/hooks/useGetMaximumAvailableAmount.ts
  apps/frontend/src/app/5_pages/ConvertPage/hooks/useGetSourceTokenBalance.ts
  apps/frontend/src/app/5_pages/ConvertPage/hooks/useHandleConversion.ts
  apps/frontend/src/app/5_pages/EarnPage/EarnPage.tsx
  apps/frontend/src/app/5_pages/EarnPage/hooks/useHandleStabilityDeposit.ts
  apps/frontend/src/app/5_pages/ZeroPage/ZeroPage.tsx
  apps/frontend/src/app/5_pages/ZeroPage/hooks/useHandleTrove.ts
  apps/frontend/src/app/5_pages/ZeroPage/utils/trove-manager.ts
  apps/frontend/src/hooks/useAssetBalance.ts
  apps/frontend/src/hooks/useMaxAssetBalance.ts
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/utils/constants.ts
  apps/frontend/src/utils/liquity.ts
  apps/frontend/src/utils/transactions.ts
  yarn.lock
Labels: enhancement

#227 SOV-1458: updated LOC Chart
  .changeset/sweet-vans-change.md
  apps/frontend/src/app/3_organisms/LOCChart/LOCChart.tsx
  apps/frontend/src/app/3_organisms/LOCChart/hooks/useGetChartOptions.ts
  apps/frontend/src/app/3_organisms/LOCChart/hooks/useGetGlobalsEntity.ts
  apps/frontend/src/app/3_organisms/LOCChart/hooks/useGetLowestTroves.ts
  apps/frontend/src/app/3_organisms/LOCChart/hooks/useGetTroves.ts
  apps/frontend/src/app/3_organisms/LOCChart/hooks/useGetTrovesPositions.ts
  apps/frontend/src/app/3_organisms/LOCChart/types.ts
  apps/frontend/src/app/3_organisms/LOCChart/utils.ts
  apps/frontend/src/app/5_pages/EarnPage/hooks/useHandleStabilityDeposit.ts
  apps/frontend/src/app/5_pages/ZeroPage/ZeroPage.tsx
  apps/frontend/src/utils/graphql/rsk/generated.tsx
  apps/frontend/src/utils/graphql/rsk/schema.graphql
  apps/frontend/src/utils/graphql/zero/generated.tsx
  apps/frontend/src/utils/graphql/zero/operations/getLowestTroves.graphql
  apps/frontend/src/utils/graphql/zero/operations/getTotalRedistributedDebt.graphql
  apps/frontend/src/utils/graphql/zero/operations/getTrove.graphql
  apps/frontend/src/utils/graphql/zero/operations/getTroves.graphql
  apps/frontend/src/utils/graphql/zero/operations/getTrovesAbove.graphql
  apps/frontend/src/utils/graphql/zero/operations/getTrovesBelow.graphql
  apps/frontend/src/utils/graphql/zero/operations/getUserOpenTrove.graphql
  apps/frontend/src/utils/graphql/zero/schema.graphql
  apps/frontend/src/utils/transactions.ts
Labels: enhancement

#240 SOV-1788: convert amount loses decimal precision
  .changeset/giant-buttons-promise.md
  apps/frontend/src/app/5_pages/ConvertPage/hooks/useGetMaximumAvailableAmount.ts
  apps/frontend/src/app/5_pages/ConvertPage/hooks/useGetSourceTokenBalance.ts
Labels: bug

#235 SOV-1622: staging env
  .changeset/cuddly-turtles-knock.md
  apps/frontend/.env.example
  apps/frontend/.env.staging
  apps/frontend/src/config/chains.ts
  apps/frontend/src/utils/helpers.ts
Labels: enhancement

#243 SOV-1712: Rewards 'Transfer to LOC' button fix
  .changeset/itchy-dodos-cough.md
  apps/frontend/src/hooks/zero/useGetOpenTrove.ts
Labels: bug

#245 SOV-1803: add page titles
  .changeset/curly-rules-protect.md
  apps/frontend/package.json
  apps/frontend/src/app/5_pages/ConvertPage/ConvertPage.tsx
  apps/frontend/src/app/5_pages/EarnPage/EarnPage.tsx
  apps/frontend/src/app/5_pages/HistoryPage/HistoryPage.tsx
  apps/frontend/src/app/5_pages/PrivacyPolicy/PrivacyPolicy.tsx
  apps/frontend/src/app/5_pages/RewardsPage/RewardsPage.tsx
  apps/frontend/src/app/5_pages/TermsOfUse/TermsOfUse.tsx
  apps/frontend/src/app/5_pages/ZeroPage/ZeroPage.tsx
  apps/frontend/src/index.tsx
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/router.tsx
  yarn.lock
Labels: enhancement

#244 SOV-1911: fix chart loading with connected wallet
  .changeset/gentle-rice-whisper.md
  apps/frontend/src/app/3_organisms/LOCChart/LOCChart.tsx
Labels: bug

#242 SOV-1611: "TX ID" should be called "TXID"
  .changeset/short-comics-teach.md
  apps/frontend/src/locales/en/translations.json
Labels: enhancement

#211 SOV-1775: reserve amount should be included for origination fee calculation
  .changeset/gentle-penguins-boil.md
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/OpenCreditLine.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/utils.ts
  apps/frontend/src/utils/math.ts
Labels: bug

#238 SOV-1486: Create AssetValue component
  .changeset/green-seahorses-attack.md
  apps/frontend/src/app/2_molecules/AssetValue/AssetValue.module.css
  apps/frontend/src/app/2_molecules/AssetValue/AssetValue.tsx
  apps/frontend/src/app/2_molecules/AssetValue/types.ts
  apps/frontend/src/app/2_molecules/ExampleBalanceCall.tsx
  apps/frontend/src/app/2_molecules/ExampleProviderCall.tsx
  yarn.lock
Labels: enhancement

#252 SOV-1923: update Zero SDK package versions
  .changeset/lazy-papayas-hide.md
  apps/frontend/package.json
  apps/frontend/src/app/3_organisms/ZeroLocForm/utils.ts
  yarn.lock
Labels: enhancement
