Repository DistributedCollective/sovryn-dapp, pull requests merged in 2023-11, with the labels that each got.

#662 SOV-3323 lend my lending balance
  .changeset/shy-jeans-report.md
  apps/frontend/src/app/2_molecules/AmountRenderer/AmountRender.test.tsx
  apps/frontend/src/app/2_molecules/AmountRenderer/AmountRenderer.tsx
  apps/frontend/src/app/2_molecules/AmountRenderer/AmountRenderer.utils.tsx
  apps/frontend/src/app/5_pages/LendPage/components/LendFrame/components/LendFrameBalance/LendFrameBalance.tsx
Labels: bug

#671 SOV-3449: Proposals bugs
  apps/frontend/src/app/5_pages/BitocracyPage/BitocracyPage.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/components/NewProposalButton/NewProposalButton.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/components/NewProposalForm/components/ParametersStep/ParametersStep.utils.ts
  apps/frontend/src/app/5_pages/BitocracyPage/components/NewProposalForm/components/ParametersStep/components/Parameter/Parameter.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/components/Proposals/Proposals.tsx
  apps/frontend/src/app/5_pages/StakePage/components/PersonalStakingStatistics/PersonalStakingStatistics.tsx
  apps/frontend/src/hooks/useGetVotingPowerShare.ts
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/utils/graphql/rsk/generated.tsx
  apps/frontend/src/utils/graphql/rsk/operations/getProposals.graphql
Labels: bug

#654 SOV-3003: Update mobile lending
  .changeset/nine-bobcats-end.md
  apps/frontend/src/app/2_molecules/FixedInterestPoolRowSubTitle/FixedInterestPoolRowSubTitle.tsx
  apps/frontend/src/app/5_pages/LendPage/components/LendFrame/LendFrame.tsx
  apps/frontend/src/app/5_pages/LendPage/components/LendFrame/LendFrame.utils.tsx
  apps/frontend/src/app/5_pages/LendPage/components/NextSupplyInterestRate/NextSupplyInterestRate.tsx
  packages/ui/src/2_molecules/Table/Table.types.ts
  packages/ui/src/2_molecules/Table/components/TableMobile/TableMobile.tsx
  packages/ui/src/2_molecules/Table/components/TableMobile/components/TableMobileRow.tsx
Labels: enhancement

#655 SOV-3324: fix nav menu toggle
  .changeset/honest-maps-push.md
  apps/frontend/src/app/3_organisms/Header/components/NavItem/NavDropdown.tsx
  apps/frontend/src/app/3_organisms/Header/components/NavItem/NavItem.tsx
Labels: bug

#673 SOV-3458: Proposal bugs
  apps/frontend/src/app/3_organisms/ProposalExecutableDetails/ProposalExecutableDetails.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/components/NewProposalForm/components/TreasuryStep/TreasuryStep.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/components/NewProposalForm/components/TreasuryStep/components/Parameter/Parameter.utils.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/components/ProposalStatus/ProposalStatus.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/contexts/NewProposalContext.tsx
Labels: bug

#650 SOV-3361: refresh vote block
  .changeset/shiny-worms-return.md
  apps/frontend/src/app/3_organisms/ProposalVotingResults/ProposalVotingResults.tsx
  apps/frontend/src/app/5_pages/ProposalPage/components/CastVote/CastVote.tsx
Labels: bug

#675 SOV-3333: improve wallet discoverability in wallet connection flow
  .changeset/fluffy-ears-juggle.md
  apps/frontend/package.json
  yarn.lock
Labels: enhancement

#677 SOV-3465: Fix new proposal button on mobile
  apps/frontend/src/app/5_pages/BitocracyPage/components/NewProposalButton/NewProposalButton.tsx
Labels: bug

#679 SOV-3459: Validate custom value
  apps/frontend/src/app/5_pages/BitocracyPage/components/NewProposalForm/components/ParametersStep/ParametersStep.utils.ts
  apps/frontend/src/app/5_pages/BitocracyPage/components/NewProposalForm/components/ParametersStep/components/Parameter/Parameter.tsx
Labels: bug

#683 SOV-3465: Fix mobile view
  apps/frontend/src/app/5_pages/BitocracyPage/components/NewProposalButton/NewProposalButton.tsx
Labels: bug

#682 SOV-3394: Market Making Base Page
  .changeset/quick-avocados-push.md
  apps/frontend/package.json
  apps/frontend/src/app/2_molecules/AssetPairRenderer/AssetPairRenderer.module.css
  apps/frontend/src/app/2_molecules/AssetPairRenderer/AssetPairRenderer.tsx
  apps/frontend/src/app/2_molecules/AssetPairRenderer/AssetPairRenderer.types.ts
  apps/frontend/src/app/2_molecules/BannersCarousel/BannersCarousel.tsx
  apps/frontend/src/app/2_molecules/BannersCarousel/components/CustomLeftArrow/CustomLeftArrow.module.css
  apps/frontend/src/app/2_molecules/BannersCarousel/components/CustomLeftArrow/CustomLeftArrow.tsx
  apps/frontend/src/app/2_molecules/BannersCarousel/components/CustomRightArrow/CustomRightArrow.module.css
  apps/frontend/src/app/2_molecules/BannersCarousel/components/CustomRightArrow/CustomRightArrow.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/MarketMakingPage.constants.ts
  apps/frontend/src/app/5_pages/MarketMakingPage/MarketMakingPage.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolsTable/PoolsTable.constants.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolsTable/PoolsTable.module.css
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolsTable/PoolsTable.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/Promotions/Promotions.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/utils/AmmLiquidityPool.ts
  apps/frontend/src/app/5_pages/MarketMakingPage/utils/AmmLiquidityPoolDictionary.ts
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/utils/graphql/mynt/generated.tsx
  apps/frontend/src/utils/graphql/rsk/generated.tsx
  apps/frontend/src/utils/graphql/zero/generated.tsx
  yarn.lock
Labels: enhancement, do-not-merge

#672 SOV-3401: Amm pool deposit and adjust modal
  apps/frontend/src/app/2_molecules/CurrentStatistics/CurrentStatistics.module.css
  apps/frontend/src/app/2_molecules/CurrentStatistics/CurrentStatistics.tsx
  apps/frontend/src/app/2_molecules/LabelWithTabsAndMaxButton/LabelWithTabsAndMaxButton.tsx
  apps/frontend/src/app/5_pages/BorrowPage/components/AdjustLoanForm/AdjustLoanForm.constants.tsx
  apps/frontend/src/app/5_pages/BorrowPage/components/AdjustLoanForm/AdjustLoanForm.tsx
  apps/frontend/src/app/5_pages/LendPage/components/AdjustModal/AdjustLendingModalContainer.tsx
  apps/frontend/src/app/5_pages/LendPage/components/AdjustModal/CurrentStats.tsx
  apps/frontend/src/app/5_pages/LendPage/components/AdjustModal/Label.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/AdjustAndDepositModal/AdjustAndDepositModal.constants.ts
  apps/frontend/src/app/5_pages/MarketMakingPage/components/AdjustAndDepositModal/AdjustAndDepositModal.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/AdjustAndDepositModal/AdjustAndDepositModal.types.ts
  apps/frontend/src/app/5_pages/MarketMakingPage/components/AdjustAndDepositModal/components/CurrentBalance/CurrentBalance.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/AdjustAndDepositModal/components/NewPoolStatistics/NewPoolStatistics.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolsTable/PoolsTable.constants.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolsTable/components/PoolsTableAction/PoolsTableAction.tsx
  apps/frontend/src/constants/general.ts
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/utils/graphql/mynt/generated.tsx
  apps/frontend/src/utils/graphql/rsk/generated.tsx
  apps/frontend/src/utils/graphql/zero/generated.tsx
  apps/frontend/src/utils/helpers.ts
  yarn.lock
Labels: enhancement

#686 SOV-3391: Carousel Promo Cards issues
  .changeset/light-dryers-applaud.md
  apps/frontend/src/app/2_molecules/BannersCarousel/BannersCarousel.module.css
  apps/frontend/src/app/2_molecules/BannersCarousel/BannersCarousel.tsx
  apps/frontend/src/app/2_molecules/BannersCarousel/components/CustomLeftArrow/CustomLeftArrow.module.css
  apps/frontend/src/app/2_molecules/BannersCarousel/components/CustomLeftArrow/CustomLeftArrow.tsx
  apps/frontend/src/app/2_molecules/BannersCarousel/components/CustomRightArrow/CustomRightArrow.module.css
  apps/frontend/src/app/2_molecules/BannersCarousel/components/CustomRightArrow/CustomRightArrow.tsx
  apps/frontend/src/app/2_molecules/PromoCard/PromoCard.module.css
  apps/frontend/src/app/5_pages/MarketMakingPage/MarketMakingPage.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/Promotions/Promotions.tsx
Labels: bug

#685 SOV-3371: update maintenance mode state for Zero - Open LOC
  .changeset/sweet-gorillas-drop.md
  apps/frontend/src/app/5_pages/ZeroPage/ZeroPage.tsx
  apps/frontend/src/locales/en/translations.json
Labels: enhancement

#680 SOV-3372: update alpha links
  .changeset/wicked-kings-tie.md
  apps/frontend/src/app/3_organisms/Header/components/ProductLinks/ProductLinks.tsx
Labels: enhancement

#690 SOV-3369: Add Enkrypt Wallet to list of browser wallets
  .changeset/dirty-maps-fix.md
  apps/frontend/package.json
Labels: enhancement

#681 SOV-3283: add fixed rate mynt converter
  .changeset/fuzzy-monkeys-sneeze.md
  apps/frontend/src/app/5_pages/ConvertPage/ConvertPage.tsx
  packages/contracts/src/abis/fixedRateConverter.json
  packages/contracts/src/contracts/protocol/rsk.ts
  packages/contracts/src/contracts/protocol/rskTestnet.ts
  packages/sdk/src/_tests/swaps/smart-router.test.ts
  packages/sdk/src/swaps/smart-router/config.ts
  packages/sdk/src/swaps/smart-router/index.ts
  packages/sdk/src/swaps/smart-router/routes/mynt-fixed-rate-route.ts
Labels: enhancement

#684 SOV-3392: update Table Row component styling
  .changeset/gentle-houses-rescue.md
  packages/ui/src/2_molecules/TableBase/TableBase.tsx
  packages/ui/src/2_molecules/TableRow/TableRow.module.css
  packages/ui/src/2_molecules/TableRow/TableRow.tsx
Labels: enhancement

#678 UPDATE: SOV-3361: resolve data refresh
  .changeset/shiny-worms-return.md
  apps/frontend/src/app/5_pages/ProposalPage/ProposalPage.tsx
Labels: enhancement

#687 SOV-3403: MM Adjust (Withdraw Deposit)
  apps/frontend/src/app/5_pages/MarketMakingPage/MarketMakingPage.types.ts
  apps/frontend/src/app/5_pages/MarketMakingPage/components/AdjustAndDepositModal/AdjustAndDepositModal.constants.ts
  apps/frontend/src/app/5_pages/MarketMakingPage/components/AdjustAndDepositModal/AdjustAndDepositModal.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/AdjustAndDepositModal/AdjustAndDepositModal.utils.ts
  apps/frontend/src/app/5_pages/MarketMakingPage/components/AdjustAndDepositModal/components/CurrentBalance/CurrentBalance.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/AdjustAndDepositModal/components/NewPoolStatistics/NewPoolStatistics.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/AdjustAndDepositModal/hooks/useGetPoolBalance.ts
  apps/frontend/src/app/5_pages/MarketMakingPage/components/AdjustAndDepositModal/hooks/useGetPoolBalanceAndRewards.ts
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolsTable/PoolsTable.constants.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolsTable/components/PoolsTableAction/PoolsTableAction.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/hooks/useGetAccumulatedReward.ts
  apps/frontend/src/app/5_pages/MarketMakingPage/hooks/useGetExpectedTokenAmount.ts
  apps/frontend/src/app/5_pages/MarketMakingPage/hooks/useGetUserInfo.ts
  apps/frontend/src/app/5_pages/MarketMakingPage/hooks/useHandleMarketMaking.ts
  apps/frontend/src/constants/gasLimits.ts
  apps/frontend/src/locales/en/translations.json
Labels: enhancement

#695 SOV-3397: High Level Pool Stats Integration (part 2)
  .changeset/new-lies-study.md
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolStatistics/PoolStatistics.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolStatistics/hooks/useGetConversionFee.ts
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolStatistics/hooks/useGetProtocolFee.ts
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolsTable/PoolsTable.tsx
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/utils/graphql/rsk/generated.tsx
  apps/frontend/src/utils/graphql/rsk/operations/getConversionFee.graphql
  apps/frontend/src/utils/graphql/rsk/operations/getProtocolFee.graphql
  apps/frontend/src/utils/graphql/rsk/schema.graphql
Labels: enhancement, do-not-merge

#697 SOV-3389: add context link into MM
  apps/frontend/src/app/5_pages/MarketMakingPage/components/AdjustAndDepositModal/AdjustAndDepositModal.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolsTable/PoolsTable.constants.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolsTable/PoolsTable.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolsTable/components/PoolsTableReturns/PoolsTableReturns.tsx
  apps/frontend/src/locales/en/translations.json
  packages/ui/src/2_molecules/ContextLink/index.ts
  packages/ui/src/2_molecules/index.ts
  yarn.lock
Labels: enhancement

#692 SOV-3405: Market making history table
  apps/frontend/src/app/3_organisms/EarnHistoryFrame/EarnHistory.constants.ts
  apps/frontend/src/app/3_organisms/EarnHistoryFrame/EarnHistory.tsx
  apps/frontend/src/app/3_organisms/EarnHistoryFrame/EarnHistory.types.ts
  apps/frontend/src/app/3_organisms/EarnHistoryFrame/components/MarketMakingHistoryFrame/MarketMakingHistory.utils.tsx
  apps/frontend/src/app/3_organisms/EarnHistoryFrame/components/MarketMakingHistoryFrame/MarketMakingHistoryFrame.constants.tsx
  apps/frontend/src/app/3_organisms/EarnHistoryFrame/components/MarketMakingHistoryFrame/MarketMakingHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/EarnHistoryFrame/components/MarketMakingHistoryFrame/hooks/useGetMarketMakingHistory.ts
  apps/frontend/src/app/3_organisms/RewardHistory/RewardHistory.tsx
  apps/frontend/src/app/3_organisms/RewardHistory/RewardHistory.types.ts
  apps/frontend/src/app/3_organisms/RewardHistory/RewardHistory.utils.ts
  apps/frontend/src/app/3_organisms/RewardHistory/components/RewardsEarnedHistory/RewardsEarnedHistory.tsx
  apps/frontend/src/app/3_organisms/RewardHistory/components/RewardsEarnedHistory/RewardsEarnedHistory.utils.tsx
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/utils/graphql/rsk/generated.tsx
  apps/frontend/src/utils/graphql/rsk/operations/getLiquidityHistory.graphql
Labels: enhancement

#698 SOV-3396: High Level Pool Stats Integration (part 1)
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolsTable/PoolsTable.constants.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolsTable/components/PoolsTableReturns/PoolsTableReturns.module.css
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolsTable/components/PoolsTableReturns/PoolsTableReturns.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolsTable/components/PoolsTableTradeVolume/PoolsTableTradeVolume.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/hooks/useGetReturnRate.ts
  apps/frontend/src/app/5_pages/MarketMakingPage/hooks/useGetTradeVolume.ts
  apps/frontend/src/constants/infrastructure.ts
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/utils/graphql/rsk/generated.tsx
  apps/frontend/src/utils/graphql/rsk/operations/getTradeVolume.graphql
  apps/frontend/src/utils/helpers.ts
Labels: enhancement

#701 SOV-3393: Promo card integration
  .changeset/shaggy-pans-hide.md
  apps/frontend/src/app/2_molecules/BannersCarousel/BannersCarousel.tsx
  apps/frontend/src/app/2_molecules/PromoCard/PromoCard.tsx
  apps/frontend/src/app/5_pages/LendPage/components/LendFrame/LendFrame.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/MarketMakingPage.constants.ts
  apps/frontend/src/app/5_pages/MarketMakingPage/MarketMakingPage.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/MarketMakingPage.types.ts
  apps/frontend/src/app/5_pages/MarketMakingPage/MarketMakingPage.utils.ts
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolsTable/PoolsTable.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/Promotions/Promotions.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/hooks/useGetPromotionsData.ts
  apps/frontend/src/hooks/useFetch.ts
  apps/frontend/src/utils/graphql/rsk/generated.tsx
  apps/frontend/src/utils/graphql/rsk/operations/getLiquidityMiningAllocationPoints.graphql
  packages/ui/src/2_molecules/Table/Table.types.ts
  packages/ui/src/2_molecules/Table/components/TableDesktop/TableDesktop.tsx
  packages/ui/src/2_molecules/TableRow/TableRow.tsx
Labels: enhancement

#696 SOV-3399: Pool volume chart
  apps/frontend/src/app/5_pages/LendPage/components/LendFrame/components/LendFrameChart/LendFrameChart.utils.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolDetails/PoolDetails.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolDetails/components/PoolChart/PoolChart.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolDetails/components/PoolChart/PoolChart.utils.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolDetails/components/PoolChart/hooks/useGetPoolVolumeData.ts
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolsTable/PoolsTable.tsx
  apps/frontend/src/constants/infrastructure.ts
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/types/global.ts
Labels: enhancement
