Repository DistributedCollective/sovryn-dapp, pull requests merged in 2023-09, with the labels that each got.

#555 SOV-2995: update open loans table
  .changeset/young-timers-sniff.md
  apps/frontend/src/app/5_pages/BorrowPage/BorrowPage.tsx
  apps/frontend/src/app/5_pages/BorrowPage/components/OpenLoansTable/OpenLoansTable.tsx
Labels: bug

#552 SOV-2922: voting proposals page
  .changeset/proud-rivers-give.md
  apps/frontend/src/app/5_pages/BitocracyPage/BitocracyPage.constants.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/BitocracyPage.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/BitocracyPage.types.ts
  apps/frontend/src/app/5_pages/BitocracyPage/BitocracyPage.utils.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/components/LiveProposals/LiveProposals.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/components/PastProposals/PastProposals.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/components/ProposalCardsMobile/ProposalCardsMobile.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/components/ProposalStatus/ProposalStatus.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/components/ProposalTitle/ProposalTitle.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/components/ProposalType/ProposalType.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/components/ProposalViewButton/ProposalViewButton.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/components/Proposals/Proposals.constants.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/components/Proposals/Proposals.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/components/Proposals/Proposals.utils.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/hooks/useGetProposals.ts
  apps/frontend/src/assets/images/ProposalStatuses/icon-active.svg
  apps/frontend/src/assets/images/ProposalStatuses/icon-executed.svg
  apps/frontend/src/assets/images/ProposalStatuses/icon-pending.svg
  apps/frontend/src/assets/images/ProposalStatuses/icon-rejected.svg
  apps/frontend/src/assets/images/ProposalStatuses/icon-succeed.svg
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/utils/graphql/rsk/generated.tsx
  apps/frontend/src/utils/graphql/rsk/operations/getProposals.graphql
  apps/frontend/src/utils/graphql/rsk/schema.graphql
  packages/contracts/src/contracts/protocol/rsk.ts
  packages/contracts/src/contracts/protocol/rskTestnet.ts
Labels: enhancement

#541 SOV-2862: Staking extend delegate issue
  .changeset/neat-kiwis-invent.md
  apps/frontend/src/app/5_pages/StakePage/components/StakesFrame/hooks/useGetStakes.ts
Labels: bug

#559 SOV-3025: fix reward link redirect on stake page
  .changeset/big-pianos-enjoy.md
  apps/frontend/src/app/5_pages/StakePage/components/AddStakeRenderer/AddStakeRenderer.tsx
Labels: enhancement

#542 SOV-3018/SOV-3020: Export funding data
  .changeset/early-moles-kneel.md
  apps/frontend/src/app/3_organisms/FundingHistoryFrame/FundingHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/FundingHistoryFrame/FundingHistoryFrame.types.ts
  apps/frontend/src/app/3_organisms/FundingHistoryFrame/FundingHistoryFrame.utils.tsx
Labels: bug

#556 SOV-2921: improve zero redemption route in smart-router package
  .changeset/metal-cars-report.md
  apps/frontend/package.json
  packages/sdk/package.json
  packages/sdk/src/swaps/smart-router/routes/zero-redemption-route.ts
  packages/sdk/src/swaps/smart-router/smart-router.ts
  yarn.lock
Labels: chore

#572 Update maintenance state ids
  .changeset/poor-paws-join.md
  apps/frontend/src/hooks/useMaintenance.ts
Labels: bug, chore

#574 SOV-3130: lower max checkpoint limit for rbtc
  apps/frontend/src/constants/general.ts
  apps/frontend/src/utils/helpers.ts
Labels: bug

#573 SOV-3120: Add maintenance states for Borrow - Extend
  apps/frontend/src/hooks/useMaintenance.ts
Labels: bug

#563 SOV-2989: Develop D2 Borrow page - Extend loan modal
  .changeset/nasty-foxes-look.md
  apps/frontend/src/app/2_molecules/DatePicker/DatePicker.module.css
  apps/frontend/src/app/2_molecules/DatePicker/DatePicker.tsx
  apps/frontend/src/app/3_organisms/BorrowLoan/BorrowLoan.utils.ts
  apps/frontend/src/app/3_organisms/BorrowLoan/components/AdjustLoanForm/AdjustLoanForm.tsx
  apps/frontend/src/app/3_organisms/BorrowLoan/components/ExtendLoanForm/ExtendLoanForm.constants.tsx
  apps/frontend/src/app/3_organisms/BorrowLoan/components/ExtendLoanForm/ExtendLoanForm.tsx
  apps/frontend/src/app/3_organisms/BorrowLoan/components/ExtendLoanForm/ExtendLoanForm.utils.tsx
  apps/frontend/src/app/3_organisms/BorrowLoan/components/ExtendLoanForm/components/CurrentLoanData/CurrentLoanData.tsx
  apps/frontend/src/app/3_organisms/BorrowLoan/components/ExtendLoanForm/hooks/useExtendLoan.ts
  apps/frontend/src/app/3_organisms/BorrowLoanForm/components/AdvancedSettings/AdvancedSettings.tsx
  apps/frontend/src/app/5_pages/BorrowPage/components/OpenLoansTable/OpenLoansTable.constants.tsx
  apps/frontend/src/app/5_pages/BorrowPage/components/OpenLoansTable/OpenLoansTable.types.ts
  apps/frontend/src/app/5_pages/BorrowPage/components/OpenLoansTable/components/ExtendLoanButton/ExtendLoanButton.tsx
  apps/frontend/src/app/5_pages/BorrowPage/components/OpenLoansTable/components/ExtendLoanDialog/ExtendLoanDialog.tsx
  apps/frontend/src/app/5_pages/BorrowPage/components/OpenLoansTable/hooks/useGetOpenLoans.ts
  apps/frontend/src/locales/en/translations.json
  packages/contracts/src/abis/protocol.json
Labels: enhancement

#558 SOV-3019: fix issue with total numbers
  .changeset/wild-wasps-drum.md
  apps/frontend/src/app/3_organisms/ConversionsHistoryFrame/components/BaseConversionsHistoryFrame/BaseConversionsHistoryFrame.tsx
Labels: bug

#578 SOV-3143: Fix repaying tiny position
  .changeset/dry-ligers-jump.md
  apps/frontend/src/app/3_organisms/BorrowLoan/components/AdjustLoanForm/AdjustLoanForm.tsx
  apps/frontend/src/app/3_organisms/BorrowLoan/components/AdjustLoanForm/hooks/useCloseWithDepositIsTinyPosition.ts
  packages/contracts/src/abis/protocol.json
Labels: bug

#579 SOV-3145: Fix extend modal allowance
  .changeset/tall-moles-applaud.md
  apps/frontend/src/app/3_organisms/BorrowLoan/components/ExtendLoanForm/hooks/useExtendLoan.ts
Labels: bug

#581 SOV-3089: Fix Loan modal titles
  .changeset/few-garlics-raise.md
  apps/frontend/src/locales/en/translations.json
Labels: bug

#585 SOV-2659: Adjust IPFS deployment
  .changeset/sweet-flies-press.md
  .github/workflows/pinata_unpin_content/action.yml
  .github/workflows/pinata_unpin_content/index.js
  .github/workflows/release-frontend-build-ipfs.yml
Labels: bug

#587 SOV-2659: IPFS - make unpinning a prerequisite for build upload
  .changeset/big-rabbits-kiss.md
  .github/workflows/release-frontend-build-ipfs.yml
Labels: bug

#590 SOV-3171: borrow history export order
  .changeset/beige-waves-shake.md
  apps/frontend/src/app/3_organisms/BorrowHistory/components/CloseWithDepositLoanFrame/hooks/useGetCloseDepositLoans.ts
  apps/frontend/src/app/3_organisms/BorrowHistory/components/CloseWithSwapLoanFrame/hooks/useGetCloseWithSwapLoans.ts
  apps/frontend/src/app/3_organisms/BorrowHistory/components/CollateralSurplusFrame/CollateralSurplusHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/BorrowHistory/components/CollateralSurplusFrame/hooks/useGetCollateralSurplusWithdrawals.ts
  apps/frontend/src/app/3_organisms/BorrowHistory/components/DepositCollateralLoanFrame/hooks/useGetDepositCollateralLoans.ts
  apps/frontend/src/app/3_organisms/BorrowHistory/components/LiquidationLoanFrame/hooks/useGetLiquidationLoans.ts
  apps/frontend/src/app/3_organisms/BorrowHistory/components/NewLoanFrame/NewLoanHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/BorrowHistory/components/RolloverLoanFrame/hooks/useGetRolloverLoans.ts
  apps/frontend/src/app/3_organisms/BorrowHistory/components/TransactionHistoryFrame/TransactionHistoryFrame.tsx
Labels: bug

#592 SOV-2756: Clean up Babelfish token config
  .changeset/big-grapes-stare.md
  apps/frontend/src/app/2_molecules/SystemStats/types.ts
  packages/contracts/src/contracts/tokens/rsk.ts
  packages/contracts/src/contracts/tokens/rskTestnet.ts
  packages/contracts/src/types.ts
Labels: chore

#582 SOV-2942: fix adjust stake data refresh
  .changeset/six-tips-tease.md
  apps/frontend/src/app/5_pages/StakePage/components/AdjustStakeRenderer/AdjustStakeRenderer.tsx
  apps/frontend/src/app/5_pages/StakePage/components/StakesFrame/StakesFrame.constants.tsx
  apps/frontend/src/app/5_pages/StakePage/components/StakesFrame/StakesFrame.tsx
  apps/frontend/src/app/5_pages/StakePage/components/StakesFrame/hooks/useGetStakes.ts
Labels: bug

#577 SOV-2993: Vesting reward history
  .changeset/nervous-brooms-guess.md
  apps/frontend/src/app/3_organisms/RewardHistory/RewardHistory.tsx
  apps/frontend/src/app/3_organisms/RewardHistory/RewardHistory.types.ts
  apps/frontend/src/app/3_organisms/RewardHistory/RewardHistory.utils.ts
  apps/frontend/src/app/3_organisms/RewardHistory/components/VestingRewards/VestingRewards.constants.tsx
  apps/frontend/src/app/3_organisms/RewardHistory/components/VestingRewards/VestingRewards.tsx
  apps/frontend/src/app/3_organisms/RewardHistory/components/VestingRewards/VestingRewards.utils.tsx
  apps/frontend/src/app/3_organisms/RewardHistory/components/VestingRewards/hooks/useGetVestingContractsId.ts
  apps/frontend/src/app/3_organisms/RewardHistory/components/VestingRewards/hooks/useGetVestingHistoryItems.ts
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/utils/graphql/rsk/generated.tsx
  apps/frontend/src/utils/graphql/rsk/operations/getVestingContractsId.graphql
  apps/frontend/src/utils/graphql/rsk/operations/getVestingHistoryItems.graphql
Labels: enhancement

#606 SOV-3077: Prevent reward SOV claiming
  .changeset/thin-jobs-pull.md
  apps/frontend/src/app/5_pages/RewardsPage/components/StabilityPool/StabilityPool.tsx
  apps/frontend/src/app/5_pages/RewardsPage/components/Staking/Staking.constants.tsx
  apps/frontend/src/app/5_pages/RewardsPage/components/Staking/Staking.tsx
  apps/frontend/src/app/5_pages/RewardsPage/components/Staking/components/WithdrawLiquidFee/WithdrawLiquidFee.tsx
  apps/frontend/src/app/5_pages/RewardsPage/components/Staking/hooks/useGetFilteredDates.ts
  apps/frontend/src/app/5_pages/RewardsPage/components/Staking/hooks/useGetVestingAddresses.ts
  apps/frontend/src/locales/en/translations.json
Labels: enhancement

#595 SOV-3021: update tooltip component
  .changeset/dirty-fireants-exist.md
  packages/ui/src/2_molecules/Tooltip/Tooltip.module.css
Labels: enhancement

#553 SOV-2787: updated notification service api
  .changeset/soft-birds-hunt.md
  apps/frontend/src/app/3_organisms/EmailNotificationSettingsDialog/EmailNotificationSettingsDialog.tsx
  apps/frontend/src/utils/helpers.ts
Labels: bug
