Repository DistributedCollective/sovryn-dapp, pull requests merged in 2023-12, with the labels that each got.

#706 SOV-3513: Refetch user info in adjust dialog
  apps/frontend/src/app/5_pages/MarketMakingPage/components/AdjustAndDepositModal/AdjustAndDepositModal.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/AdjustAndDepositModal/components/CurrentBalance/CurrentBalance.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/hooks/useGetUserInfo.ts
  apps/frontend/src/app/5_pages/MarketMakingPage/hooks/useHandleMarketMaking.ts
Labels: bug

#703 SOV-3390: reimplement increasing debt without adding collateral
  .changeset/gold-turkeys-behave.md
  apps/frontend/src/app/5_pages/BorrowPage/BorrowPage.utils.tsx
  apps/frontend/src/app/5_pages/BorrowPage/components/AdjustLoanForm/AdjustLoanForm.constants.tsx
  apps/frontend/src/app/5_pages/BorrowPage/components/AdjustLoanForm/AdjustLoanForm.tsx
  apps/frontend/src/app/5_pages/BorrowPage/components/AdjustLoanForm/AdjustLoanForm.types.ts
  apps/frontend/src/app/5_pages/BorrowPage/components/AdjustLoanForm/AdjustLoanForm.utils.tsx
  apps/frontend/src/app/5_pages/BorrowPage/components/AdjustLoanForm/hooks/useDrawdown.ts
  apps/frontend/src/app/5_pages/BorrowPage/components/OpenLoansTable/OpenLoansTable.types.ts
  apps/frontend/src/app/5_pages/BorrowPage/components/OpenLoansTable/hooks/useGetOpenLoans.ts
Labels: enhancement

#709 SOV-3546: Liquidity and balance
  apps/frontend/src/app/5_pages/MarketMakingPage/components/AdjustAndDepositModal/AdjustAndDepositModal.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/AdjustAndDepositModal/components/CurrentBalance/CurrentBalance.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolsTable/PoolsTable.constants.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolsTable/PoolsTable.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolsTable/components/CurrentBalance/CurrentBalance.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolsTable/components/CurrentBalanceRenderer/CurrentBalanceRenderer.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolsTable/components/PoolsTableLiquidity/PoolsTableLiquidity.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/hooks/useGetPoolLiquidity.ts
Labels: enhancement

#712 SOV-3411: Market Making Integration & Testing
  apps/frontend/src/app/3_organisms/EarnHistoryFrame/components/MarketMakingHistoryFrame/MarketMakingHistory.utils.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/MarketMakingPage.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/AdjustAndDepositModal/AdjustAndDepositModal.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/AdjustAndDepositModal/components/NewPoolStatistics/NewPoolStatistics.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/AdjustAndDepositModal/hooks/useGetMaxDeposit.ts
  apps/frontend/src/app/5_pages/MarketMakingPage/components/AdjustAndDepositModal/hooks/useGetPoolsBalance.ts
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolsTable/PoolsTable.constants.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolsTable/PoolsTable.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolsTable/components/CurrentBalance/CurrentBalance.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolsTable/components/CurrentBalanceRenderer/CurrentBalanceRenderer.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolsTable/components/PoolsTableAction/PoolsTableAction.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolsTable/components/PoolsTableTradeVolume/PoolsTableTradeVolume.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/Promotions/Promotions.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/hooks/useGetExpectedTokenAmount.ts
  apps/frontend/src/app/5_pages/MarketMakingPage/hooks/useGetReturnRate.ts
  apps/frontend/src/locales/en/translations.json
  packages/ui/src/2_molecules/ContextLink/ContextLink.test.tsx
  packages/ui/src/2_molecules/ContextLink/ContextLink.tsx
Labels: enhancement

#714 SOV-3531: Refactor charts
  apps/frontend/src/app/2_molecules/Chart/Chart.constants.ts
  apps/frontend/src/app/2_molecules/Chart/Chart.tsx
  apps/frontend/src/app/2_molecules/Chart/Chart.types.ts
  apps/frontend/src/app/2_molecules/Chart/Chart.utils.tsx
  apps/frontend/src/app/5_pages/LendPage/components/LendFrame/components/LendFrameChart/LendFrameChart.constants.ts
  apps/frontend/src/app/5_pages/LendPage/components/LendFrame/components/LendFrameChart/LendFrameChart.tsx
  apps/frontend/src/app/5_pages/LendPage/components/LendFrame/components/LendFrameChart/LendFrameChart.types.ts
  apps/frontend/src/app/5_pages/LendPage/components/LendFrame/components/LendFrameChart/LendFrameChart.utils.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolDetails/components/PoolChart/PoolChart.constants.ts
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolDetails/components/PoolChart/PoolChart.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolDetails/components/PoolChart/PoolChart.utils.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolDetails/components/PoolChart/hooks/useGetPoolVolumeData.ts
Labels: chore

#704 SOV-3404: Rewards claiming
  apps/frontend/src/app/5_pages/RewardsPage/RewardsPage.tsx
  apps/frontend/src/app/5_pages/RewardsPage/components/LiquidityMining/LiquidityMining.constants.tsx
  apps/frontend/src/app/5_pages/RewardsPage/components/LiquidityMining/LiquidityMining.tsx
  apps/frontend/src/app/5_pages/RewardsPage/components/LiquidityMining/components/LiquidityMiningAction/LiquidityMiningAction.tsx
  apps/frontend/src/app/5_pages/RewardsPage/components/LiquidityMining/components/LiquidityMiningMobile/LiquidityMiningMobile.tsx
  apps/frontend/src/app/5_pages/RewardsPage/components/LiquidityMining/components/LiquidityMiningMobile/LiquidityMiningMobile.utils.tsx
  apps/frontend/src/app/5_pages/RewardsPage/components/LiquidityMining/hooks/useGetLendingRewards.ts
  apps/frontend/src/app/5_pages/RewardsPage/components/LiquidityMining/hooks/useGetLiquidityRewards.ts
  apps/frontend/src/app/5_pages/RewardsPage/components/LiquidityMining/hooks/useGetTradingRewards.ts
  apps/frontend/src/app/5_pages/RewardsPage/components/LiquidityMining/hooks/useHandleRewards.ts
  apps/frontend/src/constants/gasLimits.ts
  apps/frontend/src/constants/links.ts
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/utils/graphql/rsk/generated.tsx
  apps/frontend/src/utils/graphql/rsk/operations/getTradingRewards.graphql
Labels: enhancement

#717 Fix final market making issues
  apps/frontend/src/app/2_molecules/CurrentStatistics/CurrentStatistics.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/AdjustAndDepositModal/AdjustAndDepositModal.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolDetails/PoolDetails.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolsTable/PoolsTable.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/Promotions/Promotions.tsx
  apps/frontend/src/locales/en/translations.json
Labels: bug

#708 SOV-3464: proposal timer format
  .changeset/rotten-ties-double.md
  apps/frontend/src/app/5_pages/ProposalPage/components/VoteTimer/VoteTimer.tsx
Labels: bug

#711 SOV-3416: Use mempool.space instead of BlockCypher for bitcoin block explorer links
  .changeset/ten-shirts-act.md
  apps/frontend/src/app/3_organisms/FundingHistoryFrame/FundingHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/StakingHistoryFrame/components/StakingDelegateChanges/StakingDelegateChanges.tsx
  apps/frontend/src/app/3_organisms/StakingHistoryFrame/components/StakingExtendedDuration/StakingExtendedDuration.tsx
  apps/frontend/src/app/3_organisms/StakingHistoryFrame/components/StakingHistory/StakingHistory.tsx
  apps/frontend/src/app/3_organisms/StakingHistoryFrame/components/StakingWithdraws/StakingWithdraws.tsx
  apps/frontend/src/app/3_organisms/StakingHistoryFrame/components/VestingDelegateChanges/VestingDelegateChanges.tsx
  apps/frontend/src/constants/infrastructure.ts
Labels: bug, enhancement

#724 SOV-3535: Show correct values with fixed conversion rate routes
  .changeset/tiny-queens-smoke.md
  apps/frontend/src/app/5_pages/ConvertPage/ConvertPage.constants.ts
  apps/frontend/src/app/5_pages/ConvertPage/ConvertPage.tsx
Labels: bug

#718 SOV-3527: change page titles
  .changeset/sweet-schools-cheer.md
  apps/frontend/public/index.html
  apps/frontend/src/app/5_pages/ConvertPage/ConvertPage.tsx
  apps/frontend/src/app/5_pages/StakePage/StakePage.tsx
  apps/frontend/src/locales/en/translations.json
Labels: enhancement

#727 SOV-3618: Add quick launch section
  apps/frontend/src/app/5_pages/LandingPage/LandingPage.tsx
  apps/frontend/src/app/5_pages/LandingPage/components/QuickLaunch/QuickLaunch.tsx
  apps/frontend/src/assets/images/QuickLaunch/borrow_bg.svg
  apps/frontend/src/assets/images/QuickLaunch/earn_bg.svg
  apps/frontend/src/assets/images/QuickLaunch/lend_bg.svg
  apps/frontend/src/assets/images/QuickLaunch/stake_bg.svg
  apps/frontend/src/locales/en/translations.json
Labels: enhancement

#722 SOV-3550: proposal title formatting
  .changeset/tender-brooms-study.md
  apps/frontend/src/app/5_pages/ProposalPage/ProposalPage.tsx
  apps/frontend/src/app/5_pages/ProposalPage/components/ProposalInfo/ProposalInfo.tsx
Labels: bug
