Repository DistributedCollective/sovryn-dapp, pull requests merged in 2023-05, with the labels that each got.

#369 SOV-2312: bump lib-ethers version
  apps/frontend/package.json
  packages/contracts/package.json
  yarn.lock
Labels: enhancement

#347 SOV-2207: Fix undercollateralized error show on Earn page
  .changeset/witty-cameras-beam.md
  apps/frontend/src/app/5_pages/EarnPage/EarnPage.tsx
Labels: bug

#358 SOV-2232: vertical tab shows broken border
  .changeset/mean-crews-type.md
  packages/ui/src/2_molecules/VerticalTabs/VerticalTabs.module.css
  packages/ui/src/2_molecules/VerticalTabs/VerticalTabs.stories.tsx
  packages/ui/src/2_molecules/VerticalTabs/VerticalTabs.tsx
Labels: bug

#365 SOV-2083: add links to alpha
  .changeset/afraid-gorillas-watch.md
  apps/frontend/src/app/3_organisms/Footer/Footer.tsx
  apps/frontend/src/app/3_organisms/Header/Header.tsx
  apps/frontend/src/app/3_organisms/Header/components/ProductLink/ProductLink.module.css
  apps/frontend/src/app/3_organisms/Header/components/ProductLink/ProductLink.tsx
  apps/frontend/src/app/3_organisms/Header/components/ProductLinks/ProductLinks.module.css
  apps/frontend/src/app/3_organisms/Header/components/ProductLinks/ProductLinks.tsx
  apps/frontend/src/assets/images/apps-icon.svg
  apps/frontend/src/assets/images/exit-app-icon.svg
  apps/frontend/src/constants/links.ts
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/utils/helpers.ts
Labels: enhancement

#354 SOV-2184: update banner image on mobile
  .changeset/seven-jeans-swim.md
  apps/frontend/src/assets/images/Mobile_Banner.svg
Labels: enhancement

#366 SOV-2258: Fix Min collateral validation message
  .changeset/heavy-scissors-prove.md
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/AdjustCreditLine.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/OpenCreditLine.tsx
Labels: enhancement

#356 SOV-2150: fix animated balance
  .changeset/violet-rice-smash.md
  apps/frontend/src/app/2_molecules/AmountRenderer/AmountRenderer.tsx
Labels: enhancement

#364 SOV-2216: new loader
  .changeset/mean-peas-unite.md
  apps/frontend/src/app/1_atoms/ErrorRenderer/ErrorRenderer.tsx
  apps/frontend/src/app/1_atoms/LoaderWithLogo/LoaderWithLogo.tsx
  apps/frontend/src/app/5_pages/ErrorPage/ErrorPage.tsx
  apps/frontend/src/app/5_pages/NotFoundPage/NotFoundPage.tsx
  apps/frontend/src/locales/en/translations.json
  packages/ui/src/1_atoms/Lottie/animation-map.ts
  packages/ui/src/1_atoms/Lottie/animations/error-404.json
  packages/ui/src/1_atoms/Lottie/animations/error.json
  packages/ui/src/1_atoms/Lottie/animations/loading.json
Labels: enhancement

#351 SOV-2229: update token lists
  .changeset/ninety-ways-count.md
  apps/frontend/src/app/2_molecules/AssetValue/types.ts
  packages/contracts/src/contracts/tokens/rsk.ts
  packages/contracts/src/contracts/tokens/rskTestnet.ts
  packages/contracts/src/tokenDetails/index.ts
  packages/contracts/src/tokenDetails/logos/bnbs.ts
  packages/contracts/src/tokenDetails/logos/bpro.ts
  packages/contracts/src/tokenDetails/logos/eths.ts
  packages/contracts/src/tokenDetails/logos/fish.ts
  packages/contracts/src/tokenDetails/logos/moc.ts
  packages/contracts/src/tokenDetails/logos/rif.ts
  packages/contracts/src/tokenDetails/logos/rusdt.ts
  packages/contracts/src/types.ts
Labels: enhancement

#368 SOV-2042: wallet flashing on re-connect
  .changeset/four-carpets-thank.md
  apps/frontend/package.json
  yarn.lock
Labels: enhancement

#350 SOV-1314: Add maximum origination fee rate setting
  .changeset/shiny-moons-share.md
  apps/frontend/src/app/2_molecules/AdvancedSettings/AdvancedSettings.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/AdjustCreditLine.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/FormContent.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/OpenCreditLine.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/types.ts
  apps/frontend/src/app/5_pages/ZeroPage/hooks/useHandleTrove.ts
  apps/frontend/src/app/5_pages/ZeroPage/utils/trove-manager.ts
  apps/frontend/src/locales/en/translations.json
Labels: enhancement

#387 SOV-2360: show loading screen while maintenance states are loading
  .changeset/small-coats-sparkle.md
  apps/frontend/src/contexts/MaintenanceModeContext.tsx
Labels: bug

#392 fix: skip approval step if there is enough allowance
  .changeset/red-cycles-retire.md
  packages/sdk/src/_tests/config.ts
  packages/sdk/src/_tests/swaps/routes/amm-swap-route.test.ts
  packages/sdk/src/_tests/swaps/routes/moc-integration-route.test.ts
  packages/sdk/src/_tests/swaps/routes/mynt-basset-route.test.ts
  packages/sdk/src/_tests/swaps/routes/zero-redemption-route.test.ts
  packages/sdk/src/_tests/swaps/smart-router.test.ts
  packages/sdk/src/internal/utils.ts
  packages/sdk/src/swaps/smart-router/routes/amm-swap-route.ts
  packages/sdk/src/swaps/smart-router/routes/mynt-basset-route.ts
  packages/sdk/src/swaps/smart-router/routes/zero-redemption-route.ts
Labels: bug

#395 SOV-2291: adding test description for props in Badge component
  packages/ui/.storybook/preview.js
  packages/ui/src/1_atoms/Badge/Badge.stories.tsx
Labels: documentation
