Repository DistributedCollective/sovryn-dapp, pull requests merged in 2023-10, with the labels that each got.

#550 SOV-3117: reward claiming
  .changeset/friendly-laws-type.md
  .changeset/nice-crabs-jam.md
  .changeset/smart-llamas-care.md
  apps/frontend/src/app/5_pages/RewardsPage/components/Staking/Staking.tsx
  apps/frontend/src/app/5_pages/RewardsPage/components/Staking/components/WithdrawAllFees/WithdrawAllFees.tsx
  apps/frontend/src/app/5_pages/RewardsPage/components/Staking/components/WithdrawAllFees/WithdrawlAllFees.types.ts
  apps/frontend/src/app/5_pages/RewardsPage/components/Staking/components/WithdrawFee/WithdrawFee.tsx
  apps/frontend/src/app/5_pages/RewardsPage/hooks/useGetFeesEarned.ts
  apps/frontend/src/constants/gasLimits.ts
  apps/frontend/src/hooks/useMulticall.ts
  apps/frontend/src/locales/en/translations.json
  packages/contracts/src/abis/feeSharing.json
  packages/contracts/src/abis/protocol.json
  packages/contracts/src/types.ts
  packages/contracts/src/utils/global.ts
  packages/ui/src/2_molecules/Table/Table.types.ts
  packages/ui/src/2_molecules/Table/components/TableDesktop/TableDesktop.tsx
Labels: enhancement

#610 SOV-3226: Fix bitocracy alerts button
  .changeset/shiny-years-leave.md
  apps/frontend/src/app/2_molecules/ConnectWalletButton/ConnectWalletButton.tsx
  apps/frontend/src/app/3_organisms/SharedStateProvider/SharedStateProvider.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/BitocracyPage.tsx
  apps/frontend/src/store/rxjs/shared-state.ts
Labels: bug

#580 SOV-3012: Bitocracy alerts
  .changeset/fifty-baboons-fry.md
  apps/frontend/src/app/2_molecules/ConnectWalletButton/ConnectWalletButton.tsx
  apps/frontend/src/app/3_organisms/EmailNotificationSettingsDialog/EmailNotificationSettingsDialog.types.ts
  apps/frontend/src/app/3_organisms/EmailNotificationSettingsDialog/components/Subscriptions.tsx
  apps/frontend/src/app/3_organisms/EmailNotificationSettingsDialog/contexts/EmailNotificationSettingsContext.tsx
  apps/frontend/src/app/3_organisms/EmailNotificationSettingsDialog/hooks/useHandleSubscriptions.ts
  apps/frontend/src/locales/en/translations.json
Labels: enhancement

#598 SOV-3002: fix tooltip positioning
  .changeset/fifty-singers-burn.md
  packages/ui/src/2_molecules/Tooltip/Tooltip.utils.ts
Labels: bug

#602 SOV-3073: fix mobile navigation header
  .changeset/large-masks-hide.md
  apps/frontend/src/app/2_molecules/NavLink/NavLink.tsx
  apps/frontend/src/app/3_organisms/Header/Header.constants.tsx
  apps/frontend/src/app/3_organisms/Header/Header.tsx
  apps/frontend/src/app/3_organisms/Header/components/NavItem/NavDropdown.module.css
  apps/frontend/src/app/3_organisms/Header/components/NavItem/NavDropdown.tsx
  apps/frontend/src/app/3_organisms/Header/components/NavItem/NavItem.tsx
  packages/ui/src/2_molecules/Dropdown/index.ts
Labels: bug

#605 fix: SOV-3139 dropdown positioning
  .changeset/stupid-cougars-invent.md
  apps/frontend/src/app/3_organisms/BorrowHistory/BorrowHistory.tsx
  apps/frontend/src/app/3_organisms/ConversionsHistoryFrame/ConvertHistory.tsx
  apps/frontend/src/app/3_organisms/EarnHistoryFrame/EarnHistory.tsx
  apps/frontend/src/app/3_organisms/RewardHistory/components/RewardsEarnedHistory/RewardsEarnedHistory.tsx
  apps/frontend/src/app/3_organisms/RewardHistory/components/StabilityPoolRewards/StabilityPoolRewards.tsx
  apps/frontend/src/app/3_organisms/RewardHistory/components/StabilityPoolSubsidies/StabilityPoolSubsidies.tsx
  apps/frontend/src/app/3_organisms/StakingHistoryFrame/components/StakingDelegateChanges/StakingDelegateChanges.tsx
  apps/frontend/src/app/3_organisms/StakingHistoryFrame/components/StakingExtendedDuration/StakingExtendedDuration.tsx
  apps/frontend/src/app/3_organisms/StakingHistoryFrame/components/StakingHistory/StakingHistory.tsx
  apps/frontend/src/app/3_organisms/StakingHistoryFrame/components/StakingWithdraws/StakingWithdraws.tsx
  apps/frontend/src/app/5_pages/HistoryPage/HistoryPage.module.css
  apps/frontend/src/app/5_pages/HistoryPage/HistoryPage.tsx
  packages/ui/src/2_molecules/Dropdown/Dropdown.utils.ts
Labels: bug

#608 SOV-3022: Update staking loading data
  .changeset/clean-papayas-doubt.md
  apps/frontend/src/app/3_organisms/BorrowHistory/components/CloseWithDepositLoanFrame/CloseWithDepositLoanFrame.tsx
  apps/frontend/src/app/3_organisms/BorrowHistory/components/CloseWithSwapLoanFrame/CloseWithSwapLoanFrame.tsx
  apps/frontend/src/app/3_organisms/BorrowHistory/components/CollateralSurplusFrame/CollateralSurplusHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/BorrowHistory/components/DepositCollateralLoanFrame/DepositCollateralLoanFrame.tsx
  apps/frontend/src/app/3_organisms/BorrowHistory/components/LiquidationLoanFrame/LiquidationLoanFrame.tsx
  apps/frontend/src/app/3_organisms/BorrowHistory/components/NewLoanFrame/NewLoanHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/BorrowHistory/components/RolloverLoanFrame/RolloverLoanHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/BorrowHistory/components/TransactionHistoryFrame/TransactionHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/ConversionsHistoryFrame/components/MyntConversionsHistoryFrame/MyntConversionsHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/ConversionsHistoryFrame/components/ZeroConversionsHistoryFrame/ZeroConversionsHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/EarnHistoryFrame/components/LendingHistoryFrame/LendingHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/EarnHistoryFrame/components/StabilityPoolHistoryFrame/StabilityPoolHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/FundingHistoryFrame/FundingHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/RedemptionsHistoryFrame/RedemptionsHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/RewardHistory/components/RewardsEarnedHistory/RewardsEarnedHistory.tsx
  apps/frontend/src/app/3_organisms/RewardHistory/components/StabilityPoolRewards/StabilityPoolRewards.tsx
  apps/frontend/src/app/3_organisms/RewardHistory/components/StabilityPoolSubsidies/StabilityPoolSubsidies.tsx
  apps/frontend/src/app/3_organisms/RewardHistory/components/VestingRewards/VestingRewards.tsx
  apps/frontend/src/app/3_organisms/StakingHistoryFrame/components/StakingDelegateChanges/StakingDelegateChanges.tsx
  apps/frontend/src/app/3_organisms/StakingHistoryFrame/components/StakingExtendedDuration/StakingExtendedDuration.tsx
  apps/frontend/src/app/3_organisms/StakingHistoryFrame/components/StakingHistory/StakingHistory.tsx
  apps/frontend/src/app/3_organisms/StakingHistoryFrame/components/StakingWithdraws/StakingWithdraws.tsx
  apps/frontend/src/app/3_organisms/StakingHistoryFrame/components/VestingDelegateChanges/VestingDelegateChanges.tsx
  apps/frontend/src/app/5_pages/BorrowPage/components/BorrowAssetsTable/BorrowAssetsTable.tsx
  apps/frontend/src/app/5_pages/BorrowPage/components/OpenLoansTable/OpenLoansTable.tsx
  apps/frontend/src/app/5_pages/LendPage/components/LendFrame/LendFrame.tsx
  apps/frontend/src/app/5_pages/RewardsPage/components/StabilityPool/StabilityPool.tsx
  apps/frontend/src/app/5_pages/RewardsPage/components/Staking/Staking.tsx
  apps/frontend/src/app/5_pages/RewardsPage/components/Vesting/Vesting.tsx
  apps/frontend/src/app/5_pages/StakePage/components/StakesFrame/StakesFrame.tsx
  apps/frontend/src/app/5_pages/StakePage/components/StakesFrame/hooks/useGetStakes.ts
  apps/frontend/src/app/5_pages/StakePage/components/VestingStakesFrame/VestingStakesFrame.tsx
  apps/frontend/src/locales/en/translations.json
  packages/ui/src/2_molecules/Table/Table.types.ts
  packages/ui/src/2_molecules/Table/components/TableDesktop/TableDesktop.module.css
  packages/ui/src/2_molecules/Table/components/TableDesktop/TableDesktop.tsx
  packages/ui/src/2_molecules/Table/components/TableMobile/TableMobile.module.css
  packages/ui/src/2_molecules/Table/components/TableMobile/TableMobile.tsx
Labels: enhancement

#613 SOV-3136: update lend page text
  .changeset/gold-squids-agree.md
  apps/frontend/src/app/2_molecules/FixedInterestPoolRowTitle/FixedInterestPoolRowTitle.tsx
  apps/frontend/src/app/5_pages/LendPage/components/AdjustModal/AdjustLendingModalContainer.tsx
  apps/frontend/src/app/5_pages/LendPage/components/AdjustModal/CurrentStats.tsx
  apps/frontend/src/app/5_pages/LendPage/components/AdjustModal/LendingForm.tsx
  apps/frontend/src/app/5_pages/LendPage/components/LendFrame/LendFrame.constants.tsx
  apps/frontend/src/app/5_pages/LendPage/components/LendFrame/components/LendFrameAction/LendFrameAction.tsx
  apps/frontend/src/app/5_pages/LendPage/components/LendFrame/components/LendFrameChart/LendFrameChart.tsx
  apps/frontend/src/app/5_pages/LendPage/components/LendFrame/components/LendFrameChart/LendFrameChart.types.ts
  apps/frontend/src/app/5_pages/LendPage/components/LendFrame/components/LendFrameChart/LendFrameChart.utils.tsx
  apps/frontend/src/app/5_pages/LendPage/components/LendFrame/components/LendFrameChart/hooks/useGetLendFrameChartOptions.ts
  apps/frontend/src/app/5_pages/LendPage/components/LendModal/CurrentStats.tsx
  apps/frontend/src/app/5_pages/LendPage/components/LendModal/LendingForm.tsx
  apps/frontend/src/app/5_pages/LendPage/components/LendModal/LendingModalContainer.tsx
  apps/frontend/src/locales/en/translations.json
Labels: enhancement

#599 SOV-3137: Stability pool updates
  .changeset/smart-dancers-listen.md
  apps/frontend/src/app/5_pages/EarnPage/EarnPage.tsx
  apps/frontend/src/locales/en/translations.json
Labels: enhancement

#607 SOV-3074: fix decimal places on total rewards tooltip
  .changeset/fair-rice-carry.md
  apps/frontend/src/app/2_molecules/AmountRenderer/AmountRenderer.tsx
Labels: bug

#617 SOV-3197: Increase gas limit for delegating vesting stake
  .changeset/fresh-rats-hope.md
  apps/frontend/src/constants/gasLimits.ts
Labels: bug

#618 SOV-3034: rewards page banner update
  .changeset/tame-cars-enjoy.md
  apps/frontend/src/app/5_pages/RewardsPage/RewardsPage.tsx
Labels: enhancement

#625 SOV-3225: Proposal row click
  .changeset/fresh-goats-begin.md
  apps/frontend/src/app/5_pages/BitocracyPage/components/ProposalCardsMobile/ProposalCardsMobile.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/components/ProposalTitle/ProposalTitle.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/components/ProposalViewButton/ProposalViewButton.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/components/Proposals/Proposals.tsx
  apps/frontend/src/router.tsx
Labels: bug

#627 SOV-3011: Voting - Proposal CSV export
  .changeset/pink-monkeys-wash.md
  apps/frontend/src/app/3_organisms/ProposalVotingResults/ProposalVotingResults.tsx
  apps/frontend/src/utils/graphql/rsk/generated.tsx
  apps/frontend/src/utils/graphql/rsk/operations/getProposal.graphql
Labels: enhancement

#616 SOV-3239: Support/Reject button in Cast your vote
  .changeset/olive-olives-obey.md
  apps/frontend/src/app/5_pages/ProposalPage/ProposalPage.types.ts
  apps/frontend/src/app/5_pages/ProposalPage/components/CastVote/CastVote.tsx
  apps/frontend/src/app/5_pages/ProposalPage/hooks/useGetProposalById.ts
  apps/frontend/src/app/5_pages/ProposalPage/hooks/useGetUserVote.ts
  apps/frontend/src/app/5_pages/ProposalPage/hooks/useVote.ts
  apps/frontend/src/constants/gasLimits.ts
  packages/contracts/src/abis/governor.json
  packages/contracts/src/abis/governorOwner.json
  packages/contracts/src/contracts/protocol/rsk.ts
  packages/contracts/src/contracts/protocol/rskTestnet.ts
Labels: enhancement

#583 SOV-3010: Individual Proposal page
  .changeset/angry-mails-enjoy.md
  .changeset/fresh-goats-begin.md
  .changeset/giant-ducks-laugh.md
  .changeset/many-fishes-hang.md
  .changeset/olive-olives-obey.md
  .changeset/pink-buckets-rhyme.md
  .changeset/pink-monkeys-wash.md
  .changeset/yellow-tips-sip.md
  apps/frontend/package.json
  apps/frontend/src/app/3_organisms/ProposalVotingPower/ProposalVotingPower.tsx
  apps/frontend/src/app/3_organisms/ProposalVotingPower/ProposalVotingPower.utils.tsx
  apps/frontend/src/app/3_organisms/ProposalVotingResults/ProposalVotingResults.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/BitocracyPage.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/BitocracyPage.utils.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/components/ProposalCardsMobile/ProposalCardsMobile.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/components/ProposalStatus/ProposalStatus.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/components/ProposalTitle/ProposalTitle.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/components/ProposalViewButton/ProposalViewButton.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/components/Proposals/Proposals.constants.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/components/Proposals/Proposals.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/hooks/useProposalStatus.ts
  apps/frontend/src/app/5_pages/ProposalPage/ProposalPage.tsx
  apps/frontend/src/app/5_pages/ProposalPage/ProposalPage.types.ts
  apps/frontend/src/app/5_pages/ProposalPage/ProposalPage.utils.ts
  apps/frontend/src/app/5_pages/ProposalPage/components/CastVote/CastVote.tsx
  apps/frontend/src/app/5_pages/ProposalPage/components/ExecutableDetails/ExecutableDetails.tsx
  apps/frontend/src/app/5_pages/ProposalPage/components/ProposalAction/ProposalAction.tsx
  apps/frontend/src/app/5_pages/ProposalPage/components/ProposalAction/ProposalAction.types.ts
  apps/frontend/src/app/5_pages/ProposalPage/components/ProposalAction/hooks/useHandleProposal.ts
  apps/frontend/src/app/5_pages/ProposalPage/components/ProposalInfo/ProposalInfo.tsx
  apps/frontend/src/app/5_pages/ProposalPage/components/VoteTimer/VoteTimer.tsx
  apps/frontend/src/app/5_pages/ProposalPage/hooks/useGetProposalById.ts
  apps/frontend/src/app/5_pages/ProposalPage/hooks/useGetUserVote.ts
  apps/frontend/src/app/5_pages/ProposalPage/hooks/useVote.ts
  apps/frontend/src/constants/gasLimits.ts
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/router.tsx
  apps/frontend/src/utils/graphql/rsk/generated.tsx
  apps/frontend/src/utils/graphql/rsk/operations/getProposal.graphql
  apps/frontend/src/utils/graphql/rsk/operations/getVote.graphql
  packages/contracts/src/abis/governor.json
  packages/contracts/src/contracts/protocol/rsk.ts
  packages/contracts/src/contracts/protocol/rskTestnet.ts
  yarn.lock
Labels: enhancement

#609 SOV-3148: proposal creation form
  .changeset/bright-beers-swim.md
  apps/frontend/src/app/5_pages/BitocracyPage/components/NewProposalForm/NewProposalForm.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/components/NewProposalForm/components/ProposalDataForm/ProposalDataForm.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/components/NewProposalForm/components/ProposalInitialStep/ProposalInitialStep.tsx
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/utils/helpers.ts
Labels: enhancement

#629 SOV-3303: fix Dropdown horizontal positioning bug
  .changeset/odd-carrots-notice.md
  packages/ui/src/2_molecules/Dropdown/Dropdown.utils.ts
Labels: enhancement

#630 SOV-3319: Fix proposal type
  .changeset/brave-experts-cover.md
  apps/frontend/src/app/5_pages/BitocracyPage/components/ProposalType/ProposalType.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/hooks/useIsExecutableProposal.ts
  apps/frontend/src/app/5_pages/ProposalPage/components/ExecutableDetails/ExecutableDetails.tsx
  apps/frontend/src/app/5_pages/ProposalPage/components/ProposalAction/ProposalAction.tsx
Labels: bug

#631 SOV-3312: Fix small bugs
  .changeset/small-fishes-work.md
  apps/frontend/src/app/3_organisms/ProposalVotingPower/ProposalVotingPower.utils.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/BitocracyPage.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/components/Proposals/Proposals.tsx
  apps/frontend/src/app/5_pages/ProposalPage/ProposalPage.tsx
Labels: bug

#632 SOV-3288: Show the current state of voting
  .changeset/thin-geckos-fail.md
  apps/frontend/src/app/5_pages/BitocracyPage/BitocracyPage.utils.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/components/ProposalStatus/ProposalStatus.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/hooks/useProposalStatus.ts
  apps/frontend/src/app/5_pages/ProposalPage/ProposalPage.tsx
  apps/frontend/src/locales/en/translations.json
Labels: enhancement

#636 SOV-3327: Fix status labels
  .changeset/moody-fans-attack.md
  apps/frontend/src/locales/en/translations.json
Labels: bug

#626 SOV-3289: itoken claiming
  .changeset/fluffy-eels-wait.md
  apps/frontend/src/app/5_pages/RewardsPage/components/Staking/components/WithdrawAllFees/WithdrawAllFees.tsx
  apps/frontend/src/app/5_pages/RewardsPage/hooks/useGetFeesEarned.ts
Labels: bug

#639 SOV-3334: Fix cast vote mobile
  .changeset/happy-carrots-fold.md
  apps/frontend/src/app/5_pages/ProposalPage/components/CastVote/CastVote.tsx
  apps/frontend/src/constants/gasLimits.ts
Labels: bug

#642 SOV-3319: Fix status message for non-executable proposals
  apps/frontend/src/app/5_pages/BitocracyPage/components/ProposalStatus/ProposalStatus.tsx
  apps/frontend/src/locales/en/translations.json
Labels: bug

#651 SOV-3364: Fix localisations
  .changeset/khaki-tables-walk.md
  apps/frontend/src/app/3_organisms/BorrowLoanForm/components/NewLoanForm/NewLoanForm.tsx
  apps/frontend/src/app/5_pages/ProposalPage/components/CastVote/CastVote.tsx
Labels: bug

#628 SOV-3223: Close menu when menu option is clicked
  .changeset/quiet-rivers-destroy.md
  apps/frontend/src/app/2_molecules/MenuItemWithRouter/MenuItemWithRouter.tsx
  apps/frontend/src/app/3_organisms/Header/Header.tsx
  apps/frontend/src/app/3_organisms/Header/components/NavItem/NavDropdown.module.css
  apps/frontend/src/app/3_organisms/Header/components/NavItem/NavDropdown.tsx
  apps/frontend/src/app/3_organisms/Header/components/NavItem/NavItem.tsx
Labels: enhancement

#634 SOV-3210: update twitter logo
  .changeset/shy-hornets-provide.md
  README.md
  apps/frontend/src/constants/links.ts
  apps/frontend/src/locales/en/translations.json
  packages/ui/src/1_atoms/Icon/iconSvgPaths.ts
Labels: enhancement

#644 SOV-3224: fix expand mobile table
  .changeset/lovely-melons-divide.md
  packages/ui/src/2_molecules/Table/components/TableMobile/components/TableMobileRow.tsx
Labels: bug

#647 SOV-3240: remove analytics
  .changeset/purple-turtles-act.md
  apps/frontend/.env.example
  apps/frontend/.env.production
  apps/frontend/.env.staging
  apps/frontend/public/index.html
  apps/frontend/src/styles/tailwindcss/overrides.css
Labels: enhancement

#648 SOV-3285: use Convert page as default landing page
  .changeset/warm-parents-move.md
  apps/frontend/src/router.tsx
Labels: enhancement

#656 SOV-3375: fix broken localisations
  .changeset/bright-papayas-refuse.md
  apps/frontend/src/app/2_molecules/ServiceWorkerProvider/ServiceWorkerProvider.tsx
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/Instructions.tsx
  apps/frontend/src/app/3_organisms/LOCChart/hooks/useGetChartOptions.ts
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/FormContent.tsx
  apps/frontend/src/app/5_pages/EmailErrorPage/EmailErrorPage.tsx
  apps/frontend/src/app/5_pages/NotFoundPage/NotFoundPage.tsx
Labels: bug

#657 SOV-3333: update vertical tabs style
  .changeset/neat-books-sparkle.md
  packages/ui/src/2_molecules/VerticalTabs/VerticalTabs.stories.tsx
  packages/ui/src/2_molecules/VerticalTabs/VerticalTabs.types.ts
  packages/ui/src/2_molecules/VerticalTabs/components/VerticalTabItem.module.css
  packages/ui/src/2_molecules/VerticalTabs/components/VerticalTabItem.tsx
Labels: enhancement

#660 SOV-3345: Codebase cleanup
  .changeset/yellow-elephants-dress.md
  apps/frontend/package.json
  apps/frontend/src/app/2_molecules/CollateralRatio/CollateralRatio.tsx
  apps/frontend/src/app/2_molecules/ConnectWalletButton/ConnectWalletButton.tsx
  apps/frontend/src/app/2_molecules/LanguageSelector/LanguageSelector.module.css
  apps/frontend/src/app/2_molecules/LanguageSelector/LanguageSelector.tsx
  apps/frontend/src/app/2_molecules/SocialLinks/SocialLinks.tsx
  apps/frontend/src/app/2_molecules/WalletBalance/WalletBalance.module.css
  apps/frontend/src/app/2_molecules/WalletBalance/WalletBalance.tsx
  apps/frontend/src/app/2_molecules/index.tsx
  apps/frontend/src/app/3_organisms/FundingHistoryFrame/index.ts
  apps/frontend/src/app/3_organisms/LOCChart/hooks/useGetRBTCPrice.ts
  apps/frontend/src/app/3_organisms/LOCChart/types.ts
  apps/frontend/src/app/3_organisms/LOCChart/utils.ts
  apps/frontend/src/app/3_organisms/RedemptionsHistoryFrame/RedemptionsHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/RedemptionsHistoryFrame/hooks/useGetRedemptionsHistory.ts
  apps/frontend/src/app/3_organisms/RedemptionsHistoryFrame/index.ts
  apps/frontend/src/app/3_organisms/RewardHistory/components/StabilityPoolRewards/utils.ts
  apps/frontend/src/app/3_organisms/ZeroLocForm/constants.ts
  apps/frontend/src/app/3_organisms/ZeroLocForm/types.ts
  apps/frontend/src/app/3_organisms/index.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/BitocracyPage.utils.tsx
  apps/frontend/src/app/5_pages/BorrowPage/BorrowPage.utils.tsx
  apps/frontend/src/app/5_pages/BorrowPage/components/AdjustLoanForm/AdjustLoanForm.tsx
  apps/frontend/src/app/5_pages/BorrowPage/components/BorrowAssetsTable/components/AssetTooltipComponent/AssetTooltipComponent.tsx
  apps/frontend/src/app/5_pages/BorrowPage/components/NewLoanForm/NewLoanForm.utils.tsx
  apps/frontend/src/app/5_pages/BorrowPage/components/OpenLoansTable/OpenLoansTable.types.ts
  apps/frontend/src/app/5_pages/ConvertPage/hooks/useGetDefaultSourceToken.ts
  apps/frontend/src/app/5_pages/LendPage/components/LendFrame/components/LendFrameChart/LendFrameChart.types.ts
  apps/frontend/src/app/5_pages/LendPage/components/LendFrame/components/LendFrameChart/hooks/useGetLendFrameChartOptions.ts
  apps/frontend/src/app/5_pages/LendPage/hooks/useHandleLending.ts
  apps/frontend/src/app/5_pages/ProposalPage/ProposalPage.utils.ts
  apps/frontend/src/app/5_pages/RewardsPage/components/Staking/Staking.utils.ts
  apps/frontend/src/app/5_pages/RewardsPage/components/Staking/components/WithdrawFee/WithdrawFee.tsx
  apps/frontend/src/app/5_pages/RewardsPage/hooks/useGetNextPositiveCheckpoint.ts
  apps/frontend/src/app/5_pages/RewardsPage/hooks/useGetTokenCheckpoints.ts
  apps/frontend/src/app/5_pages/RewardsPage/hooks/useGetTotalTokenCheckpoints.ts
  apps/frontend/src/app/5_pages/StakePage/components/StakesFrame/StakesFrame.types.ts
  apps/frontend/src/app/5_pages/StakePage/components/VestingStakesFrame/hooks/useGetVestingStakes.ts
  apps/frontend/src/app/5_pages/StakePage/components/VestingStakesFrame/hooks/useGetVestingsFish.ts
  apps/frontend/src/constants/general.ts
  apps/frontend/src/hooks/index.ts
  apps/frontend/src/hooks/useQueryReturn.ts
  apps/frontend/src/hooks/useTheme.ts
  apps/frontend/src/store/rxjs/provider-cache.ts
  apps/frontend/src/types/tailwind.ts
  apps/frontend/src/utils/helpers.ts
  apps/frontend/src/utils/math.ts
  apps/frontend/src/utils/tokens.ts
  package.json
  packages/ui/src/1_atoms/InputBase/utils.ts
  packages/ui/src/utils/helpers.ts
  turbo.json
  yarn.lock
Labels: chore

#658 SOV-3234: Proposal creation - Parameter Proposal Details
  .changeset/smart-drinks-smoke.md
  apps/frontend/src/app/3_organisms/ProposalExecutableDetails/components/ProposalRenderDetail/ProposalRenderDetail.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/components/NewProposalForm/NewProposalForm.constants.ts
  apps/frontend/src/app/5_pages/BitocracyPage/components/NewProposalForm/NewProposalForm.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/components/NewProposalForm/NewProposalForm.types.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/components/NewProposalForm/components/ParametersStep/ParametersStep.constants.ts
  apps/frontend/src/app/5_pages/BitocracyPage/components/NewProposalForm/components/ParametersStep/ParametersStep.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/components/NewProposalForm/components/ParametersStep/ParametersStep.types.ts
  apps/frontend/src/app/5_pages/BitocracyPage/components/NewProposalForm/components/ParametersStep/ParametersStep.utils.ts
  apps/frontend/src/app/5_pages/BitocracyPage/components/NewProposalForm/components/ParametersStep/components/Parameter/Parameter.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/components/NewProposalForm/components/ParametersStep/components/Parameter/hooks/useGetCurrentParameterValue.ts
  apps/frontend/src/app/5_pages/BitocracyPage/components/NewProposalForm/components/PreviewProposal/PreviewProposal.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/components/NewProposalForm/components/PreviewProposal/components/ExecutableDetail/ExecutableDetail.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/components/NewProposalForm/components/PreviewProposal/components/ExecutableDetails.tsx/ExecutableDetails.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/components/NewProposalForm/components/ProposalDataForm/ProposalDataForm.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/components/NewProposalForm/components/ProposalInitialStep/ProposalInitialStep.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/components/NewProposalForm/components/TreasuryStep/TreasuryStep.constants.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/components/NewProposalForm/components/TreasuryStep/TreasuryStep.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/contexts/ProposalContext.types.ts
  apps/frontend/src/locales/en/translations.json
  packages/contracts/src/abis/LoanTokenSettingsLowerAdmin.json
  packages/contracts/src/abis/loanTokenLogicBeacon.json
  packages/contracts/src/contracts/loan-tokens/rskTestnet.ts
  packages/contracts/src/contracts/protocol/rsk.ts
  packages/contracts/src/contracts/protocol/rskTestnet.ts
Labels: enhancement

#663 SOV-3422: increase suggested gas limit for claiming rewards
  .changeset/hungry-kangaroos-lie.md
  apps/frontend/src/constants/gasLimits.ts
Labels: enhancement

#665 SOV-3417: Fix proclamation type bugs
  apps/frontend/src/app/5_pages/BitocracyPage/components/NewProposalForm/NewProposalForm.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/components/NewProposalForm/components/ProposalDataForm/ProposalDataForm.tsx
Labels: bug

#666 SOV-3419: Fix custom contract/parameter data
  apps/frontend/src/app/5_pages/BitocracyPage/components/NewProposalForm/components/ParametersStep/components/Parameter/Parameter.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/components/NewProposalForm/components/ParametersStep/components/Parameter/hooks/useGetCurrentParameterValue.ts
Labels: bug
