Repository DistributedCollective/sovryn-dapp, pull requests merged in 2023-08, with the labels that each got.

#482 SOV-2747: Add lend token contracts
  .changeset/plenty-comics-turn.md
  packages/contracts/src/abis/loanTokenLogicStandard.json
  packages/contracts/src/abis/loanTokenLogicWRBTC.json
  packages/contracts/src/contracts/index.ts
  packages/contracts/src/contracts/lend-tokens/index.ts
  packages/contracts/src/contracts/lend-tokens/rsk.ts
  packages/contracts/src/contracts/lend-tokens/rskTestnet.ts
  packages/contracts/src/utils/getters.test.ts
  packages/contracts/src/utils/getters.ts
Labels: enhancement

#481 SOV-2747: Borrow page - active loans
  .changeset/heavy-cats-float.md
  apps/frontend/src/app/5_pages/BorrowPage/components/OpenLoansTable/OpenLoans.utils.tsx
  apps/frontend/src/app/5_pages/BorrowPage/components/OpenLoansTable/OpenLoansTable.constants.tsx
  apps/frontend/src/app/5_pages/BorrowPage/components/OpenLoansTable/OpenLoansTable.tsx
  apps/frontend/src/app/5_pages/BorrowPage/components/OpenLoansTable/OpenLoansTable.types.ts
  apps/frontend/src/app/5_pages/BorrowPage/components/OpenLoansTable/components/ExtendLoanButton/ExtendLoanButton.tsx
  apps/frontend/src/app/5_pages/BorrowPage/components/OpenLoansTable/hooks/useGetOpenLoans.ts
  apps/frontend/src/utils/graphql/rsk/generated.tsx
  apps/frontend/src/utils/graphql/rsk/operations/getActiveLoans.graphql
  apps/frontend/src/utils/graphql/rsk/schema.graphql
Labels: enhancement

#473 SOV-2803: use correct staking contract
  .changeset/little-monkeys-float.md
  apps/frontend/src/app/5_pages/StakePage/hooks/useHandleAdjustStake.ts
  apps/frontend/src/app/5_pages/StakePage/hooks/useHandleStake.ts
Labels: bug

#480 SOV-2884 - SOV-2859: fix staking issues
  apps/frontend/src/app/3_organisms/StakeForm/components/AdjustStakeForm/AdjustStakeForm.tsx
  apps/frontend/src/app/3_organisms/StakeForm/components/AdjustVestingStakeForm/AdjustVestingStakeForm.tsx
Labels: bug

#475 SOV-2830: Vesting stakes loading and reset issue
  .changeset/curvy-cameras-vanish.md
  apps/frontend/src/app/5_pages/StakePage/components/VestingStakesFrame/hooks/useGetVestingStakes.ts
  apps/frontend/src/app/5_pages/StakePage/components/VestingStakesFrame/hooks/useGetVestings.ts
  apps/frontend/src/app/5_pages/StakePage/components/VestingStakesFrame/hooks/useGetVestingsFish.ts
Labels: bug

#470 SOV-2875 / SOV-2876: Fix Staking pagination
  .changeset/early-buckets-share.md
  apps/frontend/src/app/5_pages/StakePage/components/StakesFrame/StakesFrame.tsx
Labels: bug

#476 SOV-2802: Fix vesting stakes voting power
  .changeset/many-mangos-burn.md
  apps/frontend/src/app/5_pages/StakePage/components/StakesFrame/hooks/useGetVestingStakeVotingPower.ts
  apps/frontend/src/app/5_pages/StakePage/components/VestingStakesFrame/components/VotingPowerCellRenderer.tsx
Labels: bug

#494 Fix AmountInput exceptions
  .changeset/witty-kids-allow.md
  apps/frontend/src/hooks/useWeiAmountInput.ts
Labels: bug

#495 SOV-2960 - SOV-2961: Fix lending frame issues
  apps/frontend/src/app/5_pages/LendPage/components/AcceptedCollateral/AcceptedCollateral.tsx
  apps/frontend/src/app/5_pages/LendPage/components/AcceptedCollateral/components/AssetTooltipContent.tsx
  apps/frontend/src/app/5_pages/LendPage/components/AdjustModal/AdjustLendingModalContainer.tsx
  apps/frontend/src/app/5_pages/LendPage/components/AdjustModal/CurrentStats.tsx
  apps/frontend/src/app/5_pages/LendPage/components/AdjustModal/Label.tsx
  apps/frontend/src/app/5_pages/LendPage/components/AdjustModal/LendingForm.tsx
  apps/frontend/src/app/5_pages/LendPage/components/LendFrame/components/LendFrameBalance/LendFrameBalance.tsx
  apps/frontend/src/app/5_pages/LendPage/components/LendFrame/components/LendFrameChart/LendFrameChart.utils.tsx
  apps/frontend/src/app/5_pages/LendPage/components/LendFrame/components/LendFrameDetails/LendFrameDetails.tsx
  apps/frontend/src/app/5_pages/LendPage/components/LendFrame/components/LendFrameInterestEarned/LendFrameInterestEarned.tsx
Labels: bug

#496 SOV-2964: Fix new lend APY calculation
  .changeset/perfect-starfishes-run.md
  apps/frontend/src/app/5_pages/LendPage/components/AdjustModal/LendingForm.tsx
Labels: bug

#498 SOV-2965: Fix Lend CSV export
  .changeset/rotten-llamas-wink.md
  apps/frontend/src/app/3_organisms/EarnHistoryFrame/components/LendingHistoryFrame/LendingHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/EarnHistoryFrame/components/LendingHistoryFrame/LendingHistoryFrame.types.ts
  apps/frontend/src/utils/graphql/rsk/generated.tsx
  apps/frontend/src/utils/graphql/rsk/operations/getLendHistory.graphql
Labels: bug

#491 SOV-2820: add dropdown earn menu
  .changeset/flat-brooms-occur.md
  apps/frontend/src/app/3_organisms/Header/Header.constants.tsx
  apps/frontend/src/app/3_organisms/Header/Header.tsx
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/router.tsx
Labels: enhancement

#509 SOV-2975: Fix submenu items refresh
  .changeset/quiet-doors-flow.md
  apps/frontend/src/app/2_molecules/MenuItemWithRouter/MenuItemWithRouter.module.css
  apps/frontend/src/app/2_molecules/MenuItemWithRouter/MenuItemWithRouter.tsx
  apps/frontend/src/app/3_organisms/Header/Header.tsx
Labels: bug

#497 SOV-2863: Update staking stats on new block
  .changeset/ninety-houses-wash.md
  apps/frontend/src/app/5_pages/StakePage/components/PersonalStakingStatistics/hooks/useGetPersonalStakingStatistics.ts
  apps/frontend/src/app/5_pages/StakePage/hooks/useGetStakingBalanceOf.ts
  apps/frontend/src/hooks/index.ts
  apps/frontend/src/hooks/useCacheCall.ts
Labels: bug

#508 SOV-2858: Fix staked SOV section in personal statistics
  .changeset/new-cougars-cross.md
  apps/frontend/src/app/3_organisms/StakeForm/components/AddStakeForm/AddStakeForm.tsx
  apps/frontend/src/app/5_pages/StakePage/components/PersonalStakingStatistics/PersonalStakingStatistics.tsx
  apps/frontend/src/app/5_pages/StakePage/components/VestingStakesFrame/VestingStakesFrame.tsx
  apps/frontend/src/app/5_pages/StakePage/components/VestingStakesFrame/hooks/useGetVestingStakes.ts
  apps/frontend/src/app/5_pages/StakePage/components/VestingStakesFrame/hooks/useGetVestings.ts
  apps/frontend/src/app/5_pages/StakePage/hooks/useGetTotalVestingsBalance.ts
Labels: bug

#488 SOV-2771: Remove trailing zero on Convert page
  .changeset/rotten-lions-taste.md
  apps/frontend/src/app/5_pages/ConvertPage/ConvertPage.tsx
  apps/frontend/src/utils/helpers.ts
Labels: enhancement

#522 SOV-2886: Vesting table available balance display fix
  .changeset/ninety-trees-sneeze.md
  apps/frontend/src/app/5_pages/RewardsPage/components/Vesting/Vesting.tsx
  apps/frontend/src/app/5_pages/RewardsPage/components/Vesting/components/UnlockedBalance/UnlockedBalance.tsx
  apps/frontend/src/app/5_pages/RewardsPage/components/Vesting/components/WithdrawButton/WithdrawButton.tsx
  apps/frontend/src/app/5_pages/RewardsPage/components/Vesting/hooks/useGetLastTokensWithdraw.ts
  apps/frontend/src/app/5_pages/RewardsPage/components/Vesting/hooks/useGetUnlockedBalance.ts
  apps/frontend/src/constants/gasLimits.ts
Labels: bug

#519 SOV-2877: fix personal staking stats display
  .changeset/rotten-mayflies-joke.md
  apps/frontend/src/app/5_pages/StakePage/StakePage.tsx
Labels: bug

#525 SOV-2878: Fix gas fee error message
  .changeset/sixty-mirrors-kneel.md
  apps/frontend/src/app/3_organisms/TransactionStepDialog/components/TransactionSteps/TransactionSteps.tsx
Labels: bug

#523 SOV-2919: Fix Buy SOV CTA
  .changeset/giant-coins-lay.md
  apps/frontend/src/app/5_pages/StakePage/components/StakingRewards/StakingRewards.tsx
Labels: enhancement

#524 SOV-2805: staking and rewards ux updates
  .changeset/silver-garlics-float.md
  apps/frontend/src/app/3_organisms/StakeForm/components/AddStakeForm/AddStakeForm.tsx
  apps/frontend/src/app/3_organisms/StakeForm/components/AdjustStakeForm/AdjustStakeForm.tsx
  apps/frontend/src/app/3_organisms/StakeForm/components/MaxDuration/MaxDuration.tsx
  apps/frontend/src/app/5_pages/RewardsPage/RewardsPage.tsx
  apps/frontend/src/app/5_pages/RewardsPage/components/Banner/Banner.tsx
  apps/frontend/src/app/5_pages/RewardsPage/components/MaxStakingAPR/MaxStakingAPR.tsx
  apps/frontend/src/app/5_pages/StakePage/components/StakingRewards/StakingRewards.tsx
  apps/frontend/src/constants/links.ts
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/styles/tailwindcss/utilities.css
Labels: enhancement

#520 SOV-2915: Fix stake-related history tables
  .changeset/gold-suits-lick.md
  apps/frontend/src/app/3_organisms/RewardHistory/components/RewardsEarnedHistory/RewardsEarnedHistory.tsx
  apps/frontend/src/app/3_organisms/StakingHistoryFrame/components/StakingDelegateChanges/StakingDelegateChanges.tsx
  apps/frontend/src/app/3_organisms/StakingHistoryFrame/components/StakingExtendedDuration/StakingExtendedDuration.tsx
  apps/frontend/src/app/3_organisms/StakingHistoryFrame/components/StakingHistory/StakingHistory.tsx
  apps/frontend/src/app/3_organisms/StakingHistoryFrame/components/StakingWithdraws/StakingWithdraws.tsx
Labels: enhancement

#529 SOV-2982: Hide FISH vesting contracts from Vesting rewards
  .changeset/wild-monkeys-breathe.md
  apps/frontend/src/app/5_pages/RewardsPage/components/Vesting/Vesting.tsx
Labels: enhancement

#530 SOV-3006: Fix vesting unlocked balance
  .changeset/tough-schools-juggle.md
  apps/frontend/src/app/5_pages/RewardsPage/components/Vesting/hooks/useGetUnlockedBalance.ts
Labels: bug

#532 SOV-3017: broken rewards banner links
  .changeset/sharp-ants-work.md
  apps/frontend/src/app/3_organisms/Header/components/ProductLinks/ProductLinks.tsx
  apps/frontend/src/app/5_pages/RewardsPage/RewardsPage.tsx
  apps/frontend/src/utils/helpers.ts
Labels: bug

#533 SOV-3016: Fix incorrect undercollateralized error
  .changeset/ninety-jars-type.md
  apps/frontend/src/app/5_pages/EarnPage/EarnPage.tsx
  apps/frontend/src/app/5_pages/RewardsPage/components/StabilityPool/StabilityPool.tsx
  apps/frontend/src/hooks/zero/useIsSystemInRecoveryMode.ts
  apps/frontend/src/hooks/zero/useUnderCollateralizedTrovesExist.ts
Labels: bug

#534 SOV-2878: Fix "Estimated gas fee exceeds BTC balance" error false positives
  .changeset/shiny-starfishes-jam.md
  apps/frontend/src/app/3_organisms/TransactionStepDialog/components/TransactionSteps/TransactionSteps.tsx
Labels: bug

#537 Fix Total Staked SOV stat on Staking page
  .changeset/unlucky-oranges-unite.md
  apps/frontend/src/app/5_pages/StakePage/components/StakingStatistics/StakingStatistics.tsx
  apps/frontend/src/app/5_pages/StakePage/components/StakingStatistics/hooks/useGetStakingStatistics.ts
Labels: bug

#501 SOV-2747: Finalize Borrow page
  .changeset/soft-schools-collect.md
  apps/frontend/src/app/3_organisms/Header/Header.constants.tsx
  apps/frontend/src/app/5_pages/BorrowPage/BorrowPage.tsx
  apps/frontend/src/app/5_pages/BorrowPage/components/BorrowAssetsTable/BorrowAssetsTable.constants.tsx
  apps/frontend/src/app/5_pages/BorrowPage/components/BorrowAssetsTable/BorrowAssetsTable.tsx
  apps/frontend/src/app/5_pages/BorrowPage/components/BorrowAssetsTable/components/AcceptedCollateral/AcceptedCollateral.tsx
  apps/frontend/src/app/5_pages/BorrowPage/components/BorrowAssetsTable/components/AvailableSupply/AvailableSupply.tsx
  apps/frontend/src/app/5_pages/LendPage/components/AcceptedCollateral/AcceptedCollateral.tsx
  apps/frontend/src/app/5_pages/LendPage/components/LendFrame/LendFrame.constants.tsx
  apps/frontend/src/app/5_pages/LendPage/components/LendFrame/LendFrame.tsx
  apps/frontend/src/app/5_pages/LendPage/components/LendFrame/LendFrame.types.ts
  apps/frontend/src/app/5_pages/LendPage/components/LendFrame/LendFrame.utils.tsx
  apps/frontend/src/app/5_pages/LendPage/components/LendFrame/components/LendFrameBalance/LendFrameBalance.tsx
  apps/frontend/src/app/5_pages/LendPage/components/LendFrame/components/LendFrameChart/LendFrameChart.utils.tsx
  apps/frontend/src/app/5_pages/LendPage/components/LendFrame/components/LendFrameChart/hooks/useGetLendFrameChartOptions.ts
  apps/frontend/src/app/5_pages/LendPage/components/LendFrame/components/LendFrameInterestEarned/LendFrameInterestEarned.tsx
  apps/frontend/src/app/5_pages/LendPage/components/LendModal/CurrentStats.tsx
  apps/frontend/src/app/5_pages/LendPage/hooks/useHandleLending.ts
  apps/frontend/src/app/5_pages/LendPage/utils/LendingPool.ts
  apps/frontend/src/app/5_pages/LendPage/utils/LendingPoolDictionary.ts
  apps/frontend/src/constants/lending.ts
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/router.tsx
Labels: enhancement

#546 SOV-2750: Borrow History
  .changeset/wise-buses-accept.md
  apps/frontend/src/app/2_molecules/AssetRenderer/AssetRenderer.tsx
  apps/frontend/src/app/3_organisms/BorrowHistory/BorrowHistory.tsx
  apps/frontend/src/app/3_organisms/BorrowHistory/BorrowHistory.types.ts
  apps/frontend/src/app/3_organisms/BorrowHistory/BorrowHistory.utils.ts
  apps/frontend/src/app/3_organisms/BorrowHistory/components/CollateralSurplusFrame/CollateralSurplusHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/BorrowHistory/components/CollateralSurplusFrame/hooks/useGetCollateralSurplusWithdrawals.ts
  apps/frontend/src/app/3_organisms/BorrowHistory/components/LoanFrame/LoanHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/BorrowHistory/components/LoanFrame/hooks/useGetLoans.ts
  apps/frontend/src/app/3_organisms/BorrowHistory/components/TransactionHistoryFrame/TransactionHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/BorrowHistory/components/TransactionHistoryFrame/hooks/useGetTroves.ts
  apps/frontend/src/app/3_organisms/BorrowHistory/components/TransactionHistoryFrame/index.ts
  apps/frontend/src/app/3_organisms/BorrowHistory/components/TransactionHistoryFrame/utils.ts
  apps/frontend/src/app/3_organisms/EarnHistoryFrame/components/StabilityPoolHistoryFrame/StabilityPoolHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/LOCHistory/LOCHistory.utils.ts
  apps/frontend/src/app/3_organisms/index.tsx
  apps/frontend/src/app/5_pages/HistoryPage/HistoryPage.tsx
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/utils/graphql/rsk/generated.tsx
  apps/frontend/src/utils/graphql/rsk/operations/getBorrowHistory.graphql
Labels: enhancement

#544 SOV-2935: bump wallet connect version
  .changeset/shy-dingos-boil.md
  apps/frontend/package.json
  yarn.lock
Labels: chore

#540 SOV-2988: Update Get Started button location
  .changeset/empty-dodos-remain.md
  apps/frontend/src/app/2_molecules/DashboardWelcomeBanner/DashboardWelcomeBanner.tsx
  apps/frontend/src/app/2_molecules/DashboardWelcomeBanner/components/ConnectedUserBanner/ConnectedUserBanner.tsx
  apps/frontend/src/app/3_organisms/Header/Header.tsx
  apps/frontend/src/app/5_pages/ZeroPage/ZeroPage.tsx
Labels: enhancement

#548 Zero page layout fixes
  .changeset/mean-lobsters-grab.md
  apps/frontend/src/app/5_pages/ZeroPage/ZeroPage.tsx
  apps/frontend/src/app/5_pages/ZeroPage/components/OpenLocButton/OpenLocButton.tsx
Labels: bug
