Repository DistributedCollective/sovryn-dapp, pull requests merged in 2023-04, with the labels that each got.

#326 SOV-1769: Make sure all transaction headers are left aligned
  .changeset/fair-hornets-cheer.md
  apps/frontend/src/app/3_organisms/CollateralSurplusWithdrawals/CollateralSurplusWithdrawals.tsx
  apps/frontend/src/app/3_organisms/ConversionsHistoryFrame/utils.tsx
  apps/frontend/src/app/3_organisms/FundingHistoryFrame/utils.tsx
  apps/frontend/src/app/3_organisms/RedemptionsHistoryFrame/RedemptionsHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/RewardHistory/RewardHistory.tsx
  apps/frontend/src/app/3_organisms/StabilityPoolHistoryFrame/StabilityPoolHistoryFrame.tsx
  apps/frontend/src/app/3_organisms/TransactionHistoryFrame/TransactionHistoryFrame.tsx
Labels: enhancement

#329 SOV-2061: D2 DLLR stats not staying in sync
  .changeset/smooth-bugs-destroy.md
  apps/frontend/src/app/2_molecules/SystemStats/hooks/useGetTotalSupply.ts
Labels: enhancement

#327 SOV-1814: Exception in console when disconnecting wallet
  .changeset/unlucky-melons-punch.md
  apps/frontend/src/app/5_pages/EarnPage/EarnPage.tsx
  apps/frontend/src/app/5_pages/RewardsPage/RewardsPage.tsx
Labels: enhancement

#325 SOV-2064: fix maintenance mode
  .changeset/pretty-rivers-approve.md
  apps/frontend/public/index.html
  apps/frontend/src/app/1_atoms/DappLocked/DappLocked.tsx
  apps/frontend/src/contexts/MaintenanceModeContext.tsx
  apps/frontend/src/hooks/useMaintenance.ts
  apps/frontend/src/utils/graphql/mynt/generated.tsx
  apps/frontend/src/utils/graphql/rsk/generated.tsx
  apps/frontend/src/utils/graphql/zero/generated.tsx
Labels: bug, enhancement

#321 SOV-2024: fix tooltip on mobile
  .changeset/breezy-rats-sleep.md
  packages/ui/src/2_molecules/Tooltip/Tooltip.module.css
  packages/ui/src/2_molecules/Tooltip/Tooltip.tsx
Labels: enhancement

#319 SOV-2025: add loader screens
  .changeset/great-taxis-shake.md
  apps/frontend/public/index.html
  apps/frontend/public/logo192.png
  apps/frontend/public/logo512.png
  apps/frontend/src/app/0_meta/DeferredDataLoader/withDeferredRouterData.tsx
  apps/frontend/src/app/0_meta/LoaderProvider/LoaderProvider.tsx
  apps/frontend/src/app/1_atoms/ErrorRenderer/ErrorRenderer.tsx
  apps/frontend/src/app/1_atoms/LoaderWithLogo/LoaderWithLogo.tsx
  apps/frontend/src/app/3_organisms/FastBtcDialog/hooks/useDepositSocket.ts
  apps/frontend/src/app/4_templates/PageContainer/PageContainer.tsx
  apps/frontend/src/app/5_pages/ErrorPage/ErrorPage.tsx
  apps/frontend/src/app/5_pages/NotFoundPage/NotFoundPage.tsx
  apps/frontend/src/app/5_pages/ZeroPage/ZeroPage.tsx
  apps/frontend/src/app/5_pages/ZeroPage/loader.ts
  apps/frontend/src/index.tsx
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/router.tsx
  apps/frontend/src/styles/tailwindcss/base.css
  apps/frontend/src/styles/tailwindcss/components.css
  apps/frontend/src/utils/helpers.ts
  apps/frontend/src/utils/loadable.tsx
  apps/frontend/src/wdyr.ts
  packages/tailwindcss-config/index.js
  packages/ui/.storybook/tailwind.css
  packages/ui/src/1_atoms/Badge/Badge.module.css
  packages/ui/src/1_atoms/Button/Button.module.css
  packages/ui/src/1_atoms/Input/Input.module.css
  packages/ui/src/1_atoms/Link/Link.module.css
  packages/ui/src/1_atoms/Lottie/animation-map.ts
  packages/ui/src/1_atoms/Lottie/animations/bug-hunting.json
  packages/ui/src/1_atoms/Lottie/index.ts
  packages/ui/src/2_molecules/Dropdown/Dropdown.module.css
  packages/ui/src/2_molecules/Menu/Menu.module.css
  packages/ui/src/2_molecules/WalletIdentity/WalletIdentity.module.css
Labels: enhancement

#331 SOV-1876: disable closing LoC when in Recovery mode
  .changeset/plenty-boats-own.md
  apps/frontend/src/app/3_organisms/ZeroLocForm/CloseCreditLine.tsx
  apps/frontend/src/app/5_pages/ZeroPage/ZeroPage.tsx
  apps/frontend/src/locales/en/translations.json
Labels: enhancement

#333 SOV-1875: Disable Stability Pool withdrawals when Troves with ICR < MCR
  .changeset/little-bags-develop.md
  apps/frontend/src/app/2_molecules/SystemStats/components/ZeroStats.tsx
  apps/frontend/src/app/2_molecules/SystemStats/utils.ts
  apps/frontend/src/app/3_organisms/LOCChart/LOCChart.tsx
  apps/frontend/src/app/3_organisms/LOCChart/types.ts
  apps/frontend/src/app/3_organisms/LOCChart/utils.ts
  apps/frontend/src/app/5_pages/EarnPage/EarnPage.tsx
  apps/frontend/src/hooks/zero/useGetRBTCPrice.ts
  apps/frontend/src/hooks/zero/useGetTroves.ts
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/utils/helpers.ts
Labels: enhancement

#336 SOV-2129: add liquity base contract
  .changeset/curvy-crabs-compete.md
  packages/contracts/src/contracts/zero/rsk.ts
  packages/contracts/src/contracts/zero/rskTestnet.ts
Labels: enhancement

#335 SOV-1584: AmountInput -> iOS -> Unexpected border appears
  .changeset/sweet-walls-train.md
  packages/ui/src/1_atoms/Input/Input.module.css
  packages/ui/src/2_molecules/AmountInput/AmountInput.module.css
Labels: bug

#337 SOV-1986: fix asset balance refreshing
  .changeset/wild-wasps-fix.md
  apps/frontend/src/app/3_organisms/LOCChart/hooks/useGetChartOptions.ts
  apps/frontend/src/hooks/useAssetBalance.ts
Labels: enhancement

#342 SOV-2131: fix max buttons
  .changeset/pretty-humans-leave.md
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/AdjustCreditLine.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/OpenCreditLine.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/utils.ts
Labels: bug

#346 SOV-2219: infinite cRatio on adjust collateral
  .changeset/twelve-pigs-juggle.md
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/AdjustCreditLine.tsx
Labels: enhancement

#352 SOV-2281: fix failing LOC transactions
  .changeset/fifty-avocados-type.md
  apps/frontend/.env.example
  apps/frontend/.env.staging
  apps/frontend/src/app/3_organisms/TransactionStepDialog/components/TransactionSteps/TransactionSteps.tsx
  apps/frontend/src/app/3_organisms/TransactionStepDialog/utils.ts
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/AdjustCreditLine.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/OpenCreditLine.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/constants.ts
  apps/frontend/src/constants/infrastructure.ts
  apps/frontend/src/types/global.ts
  apps/frontend/src/utils/simulator/helpers.ts
  apps/frontend/src/utils/simulator/simulateTx.ts
  apps/frontend/src/utils/simulator/types.ts
Labels: bug

#353 SOV-2280: Fix chart when LOC is closed
  .changeset/good-shoes-grow.md
  apps/frontend/src/app/3_organisms/LOCChart/LOCChart.tsx
  apps/frontend/src/app/5_pages/ZeroPage/ZeroPage.tsx
Labels: bug

#361 SOV-2224: bump onboard-react package version
  apps/frontend/package.json
  yarn.lock
Labels: chore

#359 SOV-2293: Add risk opt-in checkbox
  .changeset/afraid-bottles-grin.md
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/FormContent.tsx
  apps/frontend/src/constants/links.ts
  apps/frontend/src/locales/en/translations.json
  packages/ui/src/1_atoms/Checkbox/Checkbox.tsx
Labels: enhancement

#362 SOV-2117: Add stability pool subsidies details to the Earn and Rewards pages
  .changeset/young-ladybugs-add.md
  apps/frontend/package.json
  apps/frontend/src/app/5_pages/EarnPage/EarnPage.tsx
  apps/frontend/src/app/5_pages/EarnPage/hooks/useGetSubsidiesAPR.ts
  apps/frontend/src/app/5_pages/RewardsPage/RewardsPage.tsx
  apps/frontend/src/app/5_pages/RewardsPage/hooks/useGetSovGain.ts
  apps/frontend/src/app/5_pages/RewardsPage/hooks/useHandleRewards.ts
  apps/frontend/src/constants/currencies.ts
  apps/frontend/src/constants/gasLimits.ts
  apps/frontend/src/locales/en/translations.json
  packages/contracts/package.json
  packages/contracts/src/contracts/zero/rsk.ts
  packages/contracts/src/contracts/zero/rskTestnet.ts
  yarn.lock
Labels: enhancement
