Repository DistributedCollective/sovryn-dapp, pull requests merged in 2023-06, with the labels that each got.

#399 SOV-2451: cross app menu overlap fix
  .changeset/unlucky-worms-yell.md
  apps/frontend/src/app/0_meta/.gitkeep
  apps/frontend/src/app/3_organisms/Header/components/ProductLinks/ProductLinks.module.css
  yarn.lock
Labels: bug

#376 SOV-2305: Pull Zero contract details from @sovryn-zero/contracts package
  .changeset/sharp-nails-study.md
  packages/contracts/package.json
  packages/contracts/src/contracts/tokens/rsk.ts
  packages/contracts/src/contracts/tokens/rskTestnet.ts
  packages/contracts/src/contracts/zero/index.ts
  packages/contracts/src/contracts/zero/rsk.ts
  packages/contracts/src/contracts/zero/rskTestnet.ts
  yarn.lock
Labels: enhancement

#408 SOV-2365: upgrade onboard packages
  .changeset/pretty-hounds-bow.md
  apps/frontend/package.json
  yarn.lock
Labels: chore

#403 SOV-2477: resolve storybook embed issue
  .changeset/two-papayas-sit.md
  .github/workflows/chromatic.yml
  .gitignore
  packages/ui/package.json
  packages/ui/src/1_atoms/InputBase/utils.ts
  yarn.lock
Labels: enhancement

#409 SOV-2445: Create documentation for Atoms in Gitbook (part 1)
  .changeset/cuddly-steaks-smile.md
  packages/ui/src/1_atoms/Accordion/Accordion.stories.tsx
  packages/ui/src/1_atoms/Accordion/Accordion.tsx
  packages/ui/src/1_atoms/Badge/Badge.stories.tsx
  packages/ui/src/1_atoms/Button/Button.stories.tsx
  packages/ui/src/1_atoms/Checkbox/Checkbox.stories.tsx
  packages/ui/src/1_atoms/DynamicValue/DynamicValue.stories.tsx
  packages/ui/src/1_atoms/ErrorBadge/ErrorBadge.stories.tsx
  packages/ui/src/1_atoms/Heading/Heading.stories.tsx
Labels: documentation

#411 SOV-2447: create documentation for Molecules (part 1)
  .changeset/clean-lizards-hug.md
  packages/ui/src/2_molecules/AmountInput/AmountInput.stories.tsx
  packages/ui/src/2_molecules/Dialog/Dialog.stories.tsx
  packages/ui/src/2_molecules/Dialog/Dialog.tsx
  packages/ui/src/2_molecules/Dropdown/Dropdown.stories.tsx
  packages/ui/src/2_molecules/Dropdown/Dropdown.tsx
  packages/ui/src/2_molecules/ErrorList/ErrorList.stories.tsx
  packages/ui/src/2_molecules/Footer/Footer.stories.tsx
  packages/ui/src/2_molecules/FormGroup/FormGroup.stories.tsx
  packages/ui/src/2_molecules/Header/Header.stories.tsx
  packages/ui/src/2_molecules/HelperButton/HelperButton.stories.tsx
  packages/ui/src/2_molecules/Menu/Menu.stories.tsx
  packages/ui/src/2_molecules/NavMenuItem/NavMenuItem.stories.tsx
  packages/ui/src/2_molecules/NavMenuItem/NavMenuItem.tsx
  packages/ui/src/2_molecules/Notification/Notification.stories.tsx
  packages/ui/src/2_molecules/NotificationStack/NotificationStack.stories.tsx
  packages/ui/src/2_molecules/Overlay/Overlay.stories.tsx
  packages/ui/src/2_molecules/Overlay/Overlay.tsx
  packages/ui/src/2_molecules/Pagination/Pagination.stories.tsx
Labels: documentation

#422 SOV-2679: resolve Exodus wallet icon display issue
  .changeset/nervous-needles-divide.md
  apps/frontend/package.json
  yarn.lock
Labels: bug

#423 SOV-2606: bump dependencies to support WalletConnect v2
  .changeset/large-peaches-repeat.md
  apps/frontend/package.json
  apps/frontend/src/lib/connector.ts
  yarn.lock
Labels: chore

#421 SOV-2437: Reward Page - Wallet Disconnect Data Reset
  .changeset/nervous-donuts-rescue.md
  apps/frontend/src/app/5_pages/RewardsPage/RewardsPage.tsx
  apps/frontend/src/app/5_pages/RewardsPage/hooks/useGetSovGain.ts
Labels: bug

#420 SOV-2436: Stability Pool Page - Wallet Disconnect Data Reset
  .changeset/six-coins-own.md
  apps/frontend/src/app/5_pages/EarnPage/EarnPage.tsx
Labels: bug

#410 SOV-2483: Max button on FastBTC "send" amount
  .changeset/spicy-bananas-study.md
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/SendFlow/components/AmountForm.tsx
Labels: enhancement

#413 SOV-2484: add loading state for fastbtc deposit address request
  .changeset/bright-beers-shop.md
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/ReceiveFlow/components/MainScreen.tsx
  apps/frontend/src/locales/en/translations.json
Labels: enhancement

#415 SOV-2490: fastBTC address validation
  .changeset/rich-rockets-grow.md
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/Instructions.tsx
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/SendFlow/components/AddressForm.tsx
  apps/frontend/src/locales/en/translations.json
Labels: enhancement

#416 SOV-2392: wrong pending icon
  .changeset/strange-planes-doubt.md
  apps/frontend/src/app/2_molecules/StatusIcon/StatusIcon.tsx
  apps/frontend/src/assets/images/pending-tx.svg
Labels: enhancement

#418 SOV-2444: prevent withdraw while there are troves with ICR < MCR
  .changeset/tough-owls-know.md
  apps/frontend/src/app/5_pages/RewardsPage/RewardsPage.tsx
  apps/frontend/src/locales/en/translations.json
Labels: bug

#419 SOV-2448: create documentation for Molecules (part 2)
  .changeset/wet-cheetahs-work.md
  packages/ui/src/1_atoms/Accordion/Accordion.stories.tsx
  packages/ui/src/1_atoms/Badge/Badge.stories.tsx
  packages/ui/src/1_atoms/Button/Button.stories.tsx
  packages/ui/src/1_atoms/Checkbox/Checkbox.stories.tsx
  packages/ui/src/1_atoms/ErrorBadge/ErrorBadge.stories.tsx
  packages/ui/src/1_atoms/Heading/Heading.stories.tsx
  packages/ui/src/1_atoms/HealthBar/HealthBar.stories.tsx
  packages/ui/src/1_atoms/Icon/Icon.stories.tsx
  packages/ui/src/1_atoms/Input/Input.stories.tsx
  packages/ui/src/1_atoms/Link/Link.stories.tsx
  packages/ui/src/1_atoms/Paragraph/Paragraph.stories.tsx
  packages/ui/src/1_atoms/Toggle/Toggle.stories.tsx
  packages/ui/src/2_molecules/Dialog/Dialog.stories.tsx
  packages/ui/src/2_molecules/Dropdown/Dropdown.stories.tsx
  packages/ui/src/2_molecules/ErrorList/ErrorList.stories.tsx
  packages/ui/src/2_molecules/FormGroup/FormGroup.stories.tsx
  packages/ui/src/2_molecules/HelperButton/HelperButton.stories.tsx
  packages/ui/src/2_molecules/Menu/Menu.stories.tsx
  packages/ui/src/2_molecules/NavMenuItem/NavMenuItem.stories.tsx
  packages/ui/src/2_molecules/Notification/Notification.stories.tsx
  packages/ui/src/2_molecules/NotificationStack/NotificationStack.stories.tsx
  packages/ui/src/2_molecules/Overlay/Overlay.stories.tsx
  packages/ui/src/2_molecules/Pagination/Pagination.stories.tsx
  packages/ui/src/2_molecules/RadioButton/RadioButton.stories.tsx
  packages/ui/src/2_molecules/RadioButtonGroup/RadioButtonGroup.stories.tsx
  packages/ui/src/2_molecules/Select/Select.stories.tsx
  packages/ui/src/2_molecules/SimpleTable/SimpleTable.stories.tsx
  packages/ui/src/2_molecules/StatusItem/StatusItem.stories.tsx
  packages/ui/src/2_molecules/Table/Table.stories.tsx
  packages/ui/src/2_molecules/TableBase/TableBase.stories.tsx
  packages/ui/src/2_molecules/Tabs/Tabs.stories.tsx
  packages/ui/src/2_molecules/Tooltip/Tooltip.stories.tsx
  packages/ui/src/2_molecules/Tooltip/Tooltip.tsx
  packages/ui/src/2_molecules/TransactionId/TransactionId.stories.tsx
  packages/ui/src/2_molecules/VerticalTabs/VerticalTabs.stories.tsx
  packages/ui/src/2_molecules/VerticalTabsMobile/VerticalTabsMobile.stories.tsx
  packages/ui/src/2_molecules/WalletContainer/WalletContainer.stories.tsx
  packages/ui/src/2_molecules/WalletContainer/WalletContainer.tsx
  packages/ui/src/2_molecules/WalletIdentity/WalletIdentity.stories.tsx
Labels: documentation

#400 SOV-2474: convert page
  .changeset/five-spoons-run.md
  .changeset/gentle-drinks-argue.md
  .changeset/grumpy-impalas-smell.md
  .changeset/moody-cooks-appear.md
  .changeset/olive-paws-check.md
  .changeset/poor-ducks-protect.md
  .changeset/popular-poets-sort.md
  .vscode/settings.json
  apps/frontend/package.json
  apps/frontend/src/app/2_molecules/AmountRenderer/AmountRenderer.tsx
  apps/frontend/src/app/2_molecules/AssetRenderer/AssetRenderer.tsx
  apps/frontend/src/app/2_molecules/MaxButton/MaxButton.tsx
  apps/frontend/src/app/3_organisms/FastBtcDialog/components/SendFlow/components/AmountForm.tsx
  apps/frontend/src/app/3_organisms/RewardHistory/components/StabilityPoolRewards/utils.ts
  apps/frontend/src/app/3_organisms/TransactionStepDialog/TransactionStepDialog.types.ts
  apps/frontend/src/app/3_organisms/TransactionStepDialog/components/TransactionStep/TransactionStep.tsx
  apps/frontend/src/app/3_organisms/TransactionStepDialog/components/TransactionSteps/TransactionSteps.tsx
  apps/frontend/src/app/3_organisms/TransactionStepDialog/helpers.ts
  apps/frontend/src/app/3_organisms/ZeroLocForm/CloseCreditLine.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/Label.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/AdjustCreditLine.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/FormContent.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/OpenCreditLine.tsx
  apps/frontend/src/app/5_pages/ConvertPage/ConvertPage.tsx
  apps/frontend/src/app/5_pages/ConvertPage/ConvertPage.types.ts
  apps/frontend/src/app/5_pages/ConvertPage/hooks/useConversionMaintenance.ts
  apps/frontend/src/app/5_pages/ConvertPage/hooks/useGetMaximumAvailableAmount.ts
  apps/frontend/src/app/5_pages/ConvertPage/hooks/useHandleConversion.ts
  apps/frontend/src/app/5_pages/EarnPage/hooks/useHandleStabilityDeposit.ts
  apps/frontend/src/app/5_pages/ZeroPage/ZeroPage.tsx
  apps/frontend/src/app/5_pages/ZeroPage/hooks/useHandleTrove.ts
  apps/frontend/src/constants/currencies.ts
  apps/frontend/src/constants/gasLimits.ts
  apps/frontend/src/constants/tokens.ts
  apps/frontend/src/hooks/useMaintenance.ts
  apps/frontend/src/hooks/useWeiAmountInput.ts
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/utils/tokens.ts
  apps/frontend/src/utils/transactions.ts
  packages/contracts/src/abis/priceFeed.json
  packages/contracts/src/contracts/protocol/rsk.ts
  packages/contracts/src/contracts/protocol/rskTestnet.ts
  packages/contracts/src/contracts/tokens/rsk.ts
  packages/contracts/src/contracts/tokens/rskTestnet.ts
  packages/contracts/src/tokenDetails/index.ts
  packages/contracts/src/tokenDetails/logos/rbtc.ts
  packages/sdk/package.json
  packages/sdk/src/_tests/swaps/routes/amm-swap-route.test.ts
  packages/sdk/src/_tests/swaps/routes/zero-redemption-route.test.ts
  packages/sdk/src/_tests/swaps/smart-router.test.ts
  packages/sdk/src/swaps/smart-router/index.ts
  packages/sdk/src/swaps/smart-router/routes/amm-swap-route.ts
  packages/sdk/src/swaps/smart-router/routes/mynt-basset-route.ts
  packages/sdk/src/swaps/smart-router/routes/zero-redemption-route.ts
  packages/sdk/src/swaps/smart-router/smart-router.ts
  packages/ui/src/2_molecules/Select/Select.tsx
  packages/ui/src/2_molecules/SimpleTable/components/SimpleTableRow/SimpleTableRow.tsx
  turbo.json
Labels: enhancement

#431 SOV-2710: change swap network address
  .changeset/tough-hats-allow.md
  packages/contracts/src/contracts/protocol/rskTestnet.ts
Labels: chore
