Repository DistributedCollective/sovryn-dapp, pull requests merged in 2024-08, with the labels that each got.

#965 SOV-4265: Slippage settings + price impact
  .changeset/orange-lies-turn.md
  apps/frontend/src/app/5_pages/ConvertPage/ConvertPage.tsx
Labels: enhancement

#971 SOV-4346: add bitget wallet
  .changeset/tidy-keys-guess.md
  apps/frontend/package.json
  apps/frontend/src/lib/connector.ts
  yarn.lock
Labels: enhancement

#964 SOV-3945: prevent creation of "dead vestings"
  .changeset/orange-lizards-admire.md
  .changeset/real-paws-poke.md
  apps/frontend/src/app/4_templates/PageContainer/PageContainer.tsx
  apps/frontend/src/app/5_pages/RewardsPage/components/Vesting/Vesting.tsx
  apps/frontend/src/app/5_pages/RewardsPage/components/Vesting/components/UnclaimedVestingAlert/UnclaimedVestingAlert.constants.ts
  apps/frontend/src/app/5_pages/RewardsPage/components/Vesting/components/UnclaimedVestingAlert/UnclaimedVestingAlert.tsx
  apps/frontend/src/app/5_pages/RewardsPage/components/Vesting/components/UnlockSchedule/UnlockSchedule.tsx
  apps/frontend/src/app/5_pages/RewardsPage/components/Vesting/components/WithdrawButton/WithdrawButton.tsx
  apps/frontend/src/app/5_pages/RewardsPage/components/Vesting/context/VestingContext.tsx
  apps/frontend/src/app/5_pages/RewardsPage/components/Vesting/hooks/useGetUnlockSchedule.ts
  apps/frontend/src/app/5_pages/RewardsPage/components/Vesting/hooks/useLmLimit.ts
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/utils/graphql/rsk/generated.tsx
  apps/frontend/src/utils/graphql/rsk/operations/getVestingHistory.graphql
  packages/ui/src/2_molecules/Table/Table.types.ts
  packages/ui/src/2_molecules/Table/components/TableDesktop/TableDesktop.tsx
  packages/ui/src/2_molecules/Table/components/TableMobile/TableMobile.tsx
Labels: enhancement

#972 fix: LM Vesting crashes rewards page
  .changeset/modern-ducks-shake.md
  apps/frontend/src/app/5_pages/RewardsPage/RewardsPage.tsx
  apps/frontend/src/app/5_pages/RewardsPage/components/Vesting/components/UnclaimedVestingAlert/UnclaimedVestingAlert.tsx
  apps/frontend/src/app/5_pages/RewardsPage/components/Vesting/components/UnlockSchedule/UnlockSchedule.tsx
Labels: bug

#969 SOV-4343 add SAT pools
  .changeset/clever-planes-hunt.md
  .changeset/large-cougars-perform.md
  apps/frontend/src/app/5_pages/MarketMakingPage/components/AmbientMarketMaking/utils/pools/bobMainnet.ts
  packages/contracts/src/contracts/assets/bob.ts
  packages/contracts/src/contracts/assets/icons/bob/sat.ts
  packages/sdk/src/swaps/smart-router/utils/ambient-utils.ts
Labels: enhancement

#979 SOV-4350: Disable SOV/WBTC pool
  .changeset/honest-rockets-burn.md
  apps/frontend/src/app/5_pages/MarketMakingPage/components/AmbientMarketMaking/utils/pools/bobMainnet.ts
  packages/sdk/src/swaps/smart-router/utils/ambient-utils.ts
Labels: enhancement

#981 SOV-4331: Remove Rune points copy on promo card
  .changeset/smooth-forks-mate.md
  apps/frontend/src/locales/en/translations.json
Labels: chore

#987 SOV-4358: Market-Making page: wrong fee rates for V2 pools
  .changeset/rare-seals-double.md
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolStatistics/PoolStatistics.tsx
  apps/frontend/src/locales/en/translations.json
Labels: bug

#982 SOV-4328: BOB LP value display only showing one asset
  .changeset/violet-items-dress.md
  apps/frontend/src/app/5_pages/MarketMakingPage/components/AmbientMarketMaking/components/AmbientPoolPositions/hooks/useAmbientPositionValue.ts
  apps/frontend/src/hooks/useDollarValue.ts
Labels: bug

#986 SOV-4334: TraderJoe basic test page
  apps/frontend/CHANGELOG.md
  apps/frontend/package.json
  apps/frontend/src/app/5_pages/LiquidityBookPage/LiquidityBookPage.constants.ts
  apps/frontend/src/app/5_pages/LiquidityBookPage/LiquidityBookPage.tsx
  apps/frontend/src/app/5_pages/LiquidityBookPage/LiquidityBookPage.types.ts
  apps/frontend/src/app/5_pages/LiquidityBookPage/components/BalanceRenderer/BalanceRenderer.tsx
  apps/frontend/src/app/5_pages/LiquidityBookPage/components/LiquidityBookFrame/LiquidityBookFrame.constants.tsx
  apps/frontend/src/app/5_pages/LiquidityBookPage/components/LiquidityBookFrame/LiquidityBookFrame.tsx
  apps/frontend/src/app/5_pages/LiquidityBookPage/components/LiquidityBookFrame/components/LiquidityBookFrameAction/LiquidityBookFrameAction.tsx
  apps/frontend/src/app/5_pages/LiquidityBookPage/components/LiquidityBookFrame/components/LiquidityBookFrameBalance/LiquidityBookFrameBalance.tsx
  apps/frontend/src/app/5_pages/LiquidityBookPage/components/LiquidityBookFrame/hooks/useGetBalance.ts
  apps/frontend/src/app/5_pages/LiquidityBookPage/components/LiquidityBookFrame/hooks/useGetPools.ts
  apps/frontend/src/app/5_pages/LiquidityBookPage/hooks/useGetUserOwnedBins.ts
  apps/frontend/src/app/5_pages/LiquidityBookPage/hooks/useHandleLiquidity.ts
  apps/frontend/src/app/5_pages/LiquidityBookPage/utils/client.ts
  apps/frontend/src/app/5_pages/LiquidityBookPage/utils/pairs.ts
  apps/frontend/src/app/5_pages/LiquidityBookPage/utils/tokens.ts
  apps/frontend/src/config/chains.ts
  apps/frontend/src/constants/gasLimits.ts
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/router.tsx
  apps/frontend/src/setupTests.ts
  apps/frontend/tsconfig.json
  packages/sdk/CHANGELOG.md
  packages/sdk/package.json
  yarn.lock
Labels: enhancement

#985 SOV-4357: Fix Portfolio responsive issues
  .changeset/honest-items-jam.md
  apps/frontend/src/app/5_pages/PortfolioPage/PortfolioPage.tsx
  apps/frontend/src/app/5_pages/PortfolioPage/components/AssetSection/components/AssetSectionActions/AssetSectionActions.tsx
  apps/frontend/src/app/5_pages/PortfolioPage/components/ProtocolSection/components/DepositRow/DepositRow.tsx
Labels: bug

#991 SOV-4370: Update BOB Testnet chain id
  .changeset/silver-hornets-remember.md
  packages/ethers-provider/src/chains.ts
Labels: chore
