Repository DistributedCollective/sovryn-dapp, pull requests merged in 2024-10, with the labels that each got.

#1014 SOV-4461: Remove POWA page
  .changeset/lovely-buses-greet.md
  apps/frontend/src/app/3_organisms/Header/Header.constants.tsx
  apps/frontend/src/app/5_pages/LeaderboardPage/LeaderboardPage.tsx
  apps/frontend/src/app/5_pages/LeaderboardPage/components/CTALinks/CTALinks.tsx
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Intro/Intro.tsx
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Leaderboard/Leaderboard.constants.tsx
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Leaderboard/Leaderboard.tsx
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Leaderboard/Leaderboard.types.ts
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Leaderboard/components/Badges/Badges.tsx
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Leaderboard/components/Badges/Badges.utils.ts
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Leaderboard/components/BaseTable/BaseTable.constants.tsx
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Leaderboard/components/BaseTable/BaseTable.tsx
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Leaderboard/components/BaseTable/BaseTable.types.ts
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Leaderboard/components/BaseTable/BaseTable.utils.tsx
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Leaderboard/components/BaseTable/hooks/useGetData.ts
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Leaderboard/components/SocialLeaderboard/SocialLeaderboard.constants.ts
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Leaderboard/components/SocialLeaderboard/SocialLeaderboard.tsx
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Leaderboard/components/StakingLeaderboard/StakingLeaderboard.tsx
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Leaderboard/components/TradingLeaderboard/TradingLeaderboard.tsx
  apps/frontend/src/app/5_pages/LeaderboardPage/components/PointsSection/PointsSection.module.css
  apps/frontend/src/app/5_pages/LeaderboardPage/components/PointsSection/PointsSection.tsx
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/router.tsx
Labels: chore

#1016 SOV-4467: Spice Leaderboard adjustments for Season 3
  .changeset/spotty-poems-happen.md
  apps/frontend/src/app/3_organisms/Header/Header.tsx
  apps/frontend/src/app/5_pages/LeaderboardPointsPage/LeaderboardPointsPage.types.ts
  apps/frontend/src/app/5_pages/LeaderboardPointsPage/components/LeaderboardPoints/LeaderboardPoints.constants.tsx
  apps/frontend/src/app/5_pages/LeaderboardPointsPage/components/LeaderboardPoints/hooks/useGetPoints.ts
  apps/frontend/src/locales/en/translations.json
Labels: enhancement

#1015 SOV-4468: Show protocol data in BTC and USD only
  .changeset/long-buckets-smash.md
  apps/frontend/src/app/2_molecules/NativeTokenAmount/NativeTokenAmount.tsx
  apps/frontend/src/app/5_pages/LandingPage/components/ProtocolData/ProtocolData.tsx
  apps/frontend/src/hooks/useGetNativeTokenPrice.ts
  apps/frontend/src/utils/graphql/bob/generated.tsx
  apps/frontend/src/utils/graphql/mynt/generated.tsx
  apps/frontend/src/utils/graphql/rsk/generated.tsx
  apps/frontend/src/utils/graphql/zero/generated.tsx
Labels: enhancement

#1024 SOV-4496: add new pools
  .changeset/twelve-stingrays-appear.md
  apps/frontend/src/app/2_molecules/AssetRenderer/AssetRenderer.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/AmbientMarketMaking/AmbientMarketMaking.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/AmbientMarketMaking/components/AmbientPoolsTable/AmbientPoolsTable.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/AmbientMarketMaking/utils/AmbientLiquidityPool.ts
  apps/frontend/src/app/5_pages/MarketMakingPage/components/AmbientMarketMaking/utils/AmbientLiquidityPoolDictionary.ts
  apps/frontend/src/app/5_pages/MarketMakingPage/components/AmbientMarketMaking/utils/pools/bobMainnet.ts
  packages/contracts/src/contracts/assets/bob.ts
  packages/contracts/src/contracts/assets/icons/bob/dog.ts
  packages/contracts/src/contracts/assets/icons/bob/solvbtc.ts
  packages/contracts/src/contracts/assets/icons/bob/solvbtc_bbn.ts
  packages/contracts/src/contracts/assets/icons/bob/unibtc.ts
  packages/sdk/src/swaps/smart-router/utils/ambient-utils.ts
Labels: enhancement

#1028 SOV-4445: Runes page Updates
  .changeset/neat-humans-develop.md
  apps/frontend/src/app/5_pages/RunesPage/RunesPage.constants.ts
  apps/frontend/src/app/5_pages/RunesPage/RunesPage.tsx
  apps/frontend/src/app/5_pages/RunesPage/RunesPage.utils.tsx
  packages/contracts/src/contracts/assets/bobTestnet.ts
Labels: enhancement

#1029 SOV-4496: add LST pools
  .changeset/wet-dryers-destroy.md
  apps/frontend/src/app/2_molecules/AssetRenderer/AssetRenderer.tsx
  apps/frontend/src/app/5_pages/ConvertPage/ConvertPage.constants.ts
  apps/frontend/src/app/5_pages/ConvertPage/ConvertPage.types.ts
  apps/frontend/src/app/5_pages/MarketMakingPage/components/AmbientMarketMaking/utils/pools/bobMainnet.ts
  packages/contracts/src/contracts/assets/bob.ts
  packages/sdk/src/swaps/smart-router/utils/ambient-utils.ts
Labels: enhancement

#1032 Fix asset icon styles
  .changeset/gentle-schools-fetch.md
  apps/frontend/src/app/2_molecules/AssetRenderer/AssetRenderer.module.css
  apps/frontend/src/app/2_molecules/AssetRenderer/AssetRenderer.tsx
Labels: bug

#1041 SOV-4527: custom messages on convert page dropdown
  .changeset/fifty-paws-divide.md
  apps/frontend/src/app/5_pages/ConvertPage/components/AssetDropdownWithFilters/AssetDropdownWithFilters.tsx
Labels: bug

#1034 SOV-4493: Show ecosystem statistics only in BTC and USD
  .changeset/mighty-swans-remember.md
  apps/frontend/src/app/5_pages/ProtocolDataPage/components/EcosystemStatistics/EcosystemStatistics.tsx
Labels: enhancement
