Repository DistributedCollective/sovryn-dapp, pull requests merged in 2024-09, with the labels that each got.

#994 SOV-4406: Fix Tooltip arrow color
  .changeset/thick-flies-hope.md
  packages/ui/src/2_molecules/Tooltip/Tooltip.module.css
  packages/ui/src/2_molecules/Tooltip/Tooltip.stories.tsx
  packages/ui/src/2_molecules/Tooltip/Tooltip.tsx
  packages/ui/src/2_molecules/Tooltip/Tooltip.types.ts
Labels: enhancement

#995 SOV-4393: Fix deposit button
  .changeset/shiny-chairs-look.md
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolsTable/components/PoolsTableAction/PoolsTableAction.tsx
Labels: bug

#998 SOV-4388: Fix USD prices on Portfolio page
  .changeset/dry-chairs-wink.md
  apps/frontend/src/app/5_pages/MarketMakingPage/components/AmbientMarketMaking/hooks/useGetAmbientPositions.ts
  apps/frontend/src/constants/infrastructure.ts
  apps/frontend/src/constants/infrastructure/bob.ts
  apps/frontend/src/contexts/TokenPricesContext.tsx
  apps/frontend/src/utils/indexer.ts
Labels: bug

#996 SOV-4344: Consolidate Spice Leaderboard
  .changeset/yellow-weeks-look.md
  apps/frontend/src/app/3_organisms/Header/Header.tsx
  apps/frontend/src/app/5_pages/LeaderboardPointsPage/LeaderboardPointsPage.constants.tsx
  apps/frontend/src/app/5_pages/LeaderboardPointsPage/LeaderboardPointsPage.tsx
  apps/frontend/src/app/5_pages/LeaderboardPointsPage/LeaderboardPointsPage.types.ts
  apps/frontend/src/app/5_pages/LeaderboardPointsPage/LeaderboardPointsPage.utils.tsx
  apps/frontend/src/app/5_pages/LeaderboardPointsPage/components/LeaderboardPoints/LeaderboardPoints.constants.tsx
  apps/frontend/src/app/5_pages/LeaderboardPointsPage/components/LeaderboardPoints/LeaderboardPoints.tsx
  apps/frontend/src/app/5_pages/LeaderboardPointsPage/components/LeaderboardPoints/LeaderboardPoints.utils.tsx
  apps/frontend/src/app/5_pages/LeaderboardPointsPage/components/LeaderboardPoints/hooks/useGetPoints.ts
  apps/frontend/src/app/5_pages/LeaderboardPointsPage/components/LeaderboardPointsSeason1/LeaderboardPointsSeason1.constants.tsx
  apps/frontend/src/app/5_pages/LeaderboardPointsPage/components/LeaderboardPointsSeason1/LeaderboardPointsSeason1.tsx
  apps/frontend/src/app/5_pages/LeaderboardPointsPage/components/LeaderboardPointsSeason1/data/usersPoints.json
  apps/frontend/src/app/5_pages/LeaderboardPointsPage/components/LeaderboardPointsSeason1/hooks/useGetPoints.ts
  apps/frontend/src/app/5_pages/LeaderboardPointsPage/data/usersExtraPoints.json
  apps/frontend/src/locales/en/translations.json
Labels: enhancement

#955 SOV-4246: statistics updates
  .changeset/forty-pumpkins-play.md
  apps/frontend/src/app/2_molecules/NativeTokenAmount/NativeTokenAmount.tsx
  apps/frontend/src/app/5_pages/LandingPage/components/ProtocolData/ProtocolData.constants.ts
  apps/frontend/src/app/5_pages/LandingPage/components/ProtocolData/ProtocolData.tsx
  apps/frontend/src/app/5_pages/LandingPage/components/ProtocolData/ProtocolData.types.ts
  apps/frontend/src/app/5_pages/LandingPage/components/ProtocolData/hooks/useGetBOBVolume.ts
  apps/frontend/src/app/5_pages/LandingPage/components/ProtocolData/hooks/useGetLockedData.ts
  apps/frontend/src/app/5_pages/LandingPage/components/ProtocolData/hooks/useGetRSKVolume.ts
  apps/frontend/src/app/5_pages/LandingPage/components/ProtocolData/hooks/useGetTokens.ts
  apps/frontend/src/app/5_pages/ProtocolDataPage/ProtocolDataPage.constants.ts
  apps/frontend/src/app/5_pages/ProtocolDataPage/ProtocolDataPage.tsx
  apps/frontend/src/app/5_pages/ProtocolDataPage/components/EcosystemStatistics/EcosystemStatistics.tsx
  apps/frontend/src/app/5_pages/ProtocolDataPage/components/EcosystemStatistics/EcosystemStatistics.types.ts
  apps/frontend/src/app/5_pages/ProtocolDataPage/components/SectionLinks/SectionLinks.tsx
  apps/frontend/src/constants/infrastructure.ts
  apps/frontend/src/contexts/TokenPricesContext.tsx
  apps/frontend/src/hooks/useGetNativeTokenPrice.ts
  apps/frontend/src/hooks/zero/useGetRBTCPrice.ts
  apps/frontend/src/utils/helpers.ts
  apps/frontend/src/utils/indexer.ts
Labels: enhancement, do-not-merge

#997 SOV-4411: Update Slider component with Ranged functionality
  .changeset/cuddly-cougars-unite.md
  apps/frontend/src/app/5_pages/MarketMakingPage/components/BobDepositModal/components/PriceRange/components/BalancedRange/BalancedRange.tsx
  packages/ui/src/1_atoms/Slider/Slider.module.css
  packages/ui/src/1_atoms/Slider/Slider.stories.tsx
  packages/ui/src/1_atoms/Slider/Slider.test.tsx
  packages/ui/src/1_atoms/Slider/Slider.tsx
  packages/ui/src/1_atoms/Slider/index.ts
  packages/ui/src/1_atoms/index.tsx
Labels: enhancement

#999 SOV-4410: add liquidity modal
  .changeset/nice-pots-cover.md
  .changeset/nice-pots-coverup.md
  apps/frontend/src/app/5_pages/LiquidityBookPage/LiquidityBookPage.tsx
  apps/frontend/src/app/5_pages/LiquidityBookPage/LiquidityBookPage.types.ts
  apps/frontend/src/app/5_pages/LiquidityBookPage/components/AddLiquidityModal/AddLiquidityModal.tsx
  apps/frontend/src/app/5_pages/LiquidityBookPage/components/AddLiquidityModal/Content.tsx
  apps/frontend/src/app/5_pages/LiquidityBookPage/components/AddLiquidityModal/LiquidityPriceForm.tsx
  apps/frontend/src/app/5_pages/LiquidityBookPage/components/AddLiquidityModal/constants.ts
  apps/frontend/src/app/5_pages/LiquidityBookPage/components/LiquidityBookFrame/components/LiquidityBookFrameAction/LiquidityBookFrameAction.tsx
  apps/frontend/src/app/5_pages/LiquidityBookPage/components/LiquidityBookFrame/hooks/useGetPools.ts
  apps/frontend/src/app/5_pages/LiquidityBookPage/hooks/useHandleLiquidity.ts
  apps/frontend/src/app/5_pages/LiquidityBookPage/utils/constants.ts
  apps/frontend/src/app/5_pages/LiquidityBookPage/utils/pairs.ts
  apps/frontend/src/app/5_pages/LiquidityBookPage/utils/tokens.ts
  apps/frontend/src/locales/en/translations.json
  packages/sdk/src/internal/utils.ts
  packages/sdk/src/swaps/smart-router/routes/joe.ts
Labels: enhancement

#1002 Portfolio page in D2 on RSK fix
  .changeset/real-ghosts-judge.md
  apps/frontend/src/hooks/useGetNativeTokenPrice.ts
  packages/sdex/src/constants.ts
Labels: bug

#1006 SOV-4457: rebrand SAT token
  .changeset/green-forks-rule.md
  apps/frontend/src/app/5_pages/MarketMakingPage/components/AmbientMarketMaking/utils/pools/bobMainnet.ts
  packages/contracts/src/contracts/assets/bob.ts
  packages/sdk/src/swaps/smart-router/utils/ambient-utils.ts
Labels: chore

#1013 SOV-4443: Rune Pools Market Making updates
  .changeset/honest-fans-fly.md
  apps/frontend/src/app/5_pages/MarketMakingPage/MarketMakingPage.constants.ts
  apps/frontend/src/app/5_pages/MarketMakingPage/components/MarketMaking/MarketMaking.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolsTable/PoolsTable.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/utils/AmmLiquidityPool.ts
  apps/frontend/src/locales/en/translations.json
Labels: enhancement

#1009 SOV-4444: Rune pools convert updates
  .changeset/many-candles-confess.md
  apps/frontend/src/app/5_pages/ConvertPage/ConvertPage.constants.ts
  apps/frontend/src/app/5_pages/ConvertPage/ConvertPage.tsx
  apps/frontend/src/app/5_pages/ConvertPage/ConvertPage.types.ts
  apps/frontend/src/app/5_pages/ConvertPage/components/AssetDropdownWithFilters/AssetDropdownWithFilters.tsx
  apps/frontend/src/locales/en/translations.json
  packages/ui/src/1_atoms/FilterPill/FilterPill.module.css
  packages/ui/src/1_atoms/FilterPill/FilterPill.stories.tsx
  packages/ui/src/1_atoms/FilterPill/FilterPill.tsx
  packages/ui/src/1_atoms/FilterPill/index.tsx
  packages/ui/src/1_atoms/index.tsx
Labels: enhancement
