Repository DistributedCollective/sovryn-dapp, pull requests merged in 2024-05, with the labels that each got.

#890 Bridge and promo updates
  apps/frontend/src/app/2_molecules/CTA/CTA.tsx
  apps/frontend/src/app/3_organisms/Header/components/BridgeMenuItem/BridgeMenuItem.tsx
  apps/frontend/src/app/5_pages/LandingPage/components/QuickLaunch/QuickLaunch.tsx
  apps/frontend/src/assets/images/QuickLaunch/runes_bg.svg
  apps/frontend/src/assets/images/QuickLaunch/runes_trade_bg.svg
  apps/frontend/src/assets/images/QuickLaunch/yield_bg.svg
  apps/frontend/src/constants/infrastructure/bob.ts
  apps/frontend/src/locales/en/translations.json
Labels: enhancement

#892 SOV-4119: Show quote error on Convert page
  apps/frontend/src/app/5_pages/ConvertPage/ConvertPage.tsx
  apps/frontend/src/locales/en/translations.json
  packages/sdk/src/swaps/smart-router/smart-router.ts
Labels: enhancement

#891 bob
  apps/frontend/src/app/5_pages/ConvertPage/ConvertPage.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/AmbientMarketMaking/utils/AmbientLiquidityPoolDictionary.ts
  apps/frontend/src/app/5_pages/MarketMakingPage/components/AmbientMarketMaking/utils/pools/bobMainnet.ts
  apps/frontend/src/constants/infrastructure/bob.ts
  apps/frontend/src/hooks/useLoadContract.ts
  apps/frontend/src/locales/en/translations.json
  packages/contracts/src/contracts/assets/bob.ts
  packages/contracts/src/contracts/assets/bobTestnet.ts
  packages/contracts/src/contracts/protocol/bob.ts
  packages/contracts/src/contracts/protocol/index.ts
  packages/sdk/src/swaps/smart-router/routes/ambient.ts
  packages/sdk/src/swaps/smart-router/smart-router.ts
  packages/sdk/src/swaps/smart-router/utils/ambient-utils.ts
Labels: do-not-merge

#893 SOV-4023: Rune Bridge BOB support
  .changeset/famous-moons-work.md
  apps/frontend/src/app/3_organisms/RuneBridgeDialog/RuneBridgeDialog.tsx
  apps/frontend/src/app/3_organisms/RuneBridgeDialog/api/RuneBridgeClient.tsx
  apps/frontend/src/app/3_organisms/RuneBridgeDialog/api/index.ts
  apps/frontend/src/app/3_organisms/RuneBridgeDialog/components/ReceiveFlow/components/StatusScreen.tsx
  apps/frontend/src/app/3_organisms/RuneBridgeDialog/components/SendFlow/components/AmountForm.tsx
  apps/frontend/src/app/3_organisms/RuneBridgeDialog/components/SendFlow/components/ConfirmationScreens.tsx
  apps/frontend/src/app/3_organisms/RuneBridgeDialog/components/SendFlow/components/ReviewScreen.tsx
  apps/frontend/src/app/3_organisms/RuneBridgeDialog/components/SendFlow/components/StatusScreen.tsx
  apps/frontend/src/app/3_organisms/RuneBridgeDialog/constants.ts
  apps/frontend/src/app/3_organisms/RuneBridgeDialog/contextproviders/ReceiveFlowContext.tsx
  apps/frontend/src/app/3_organisms/RuneBridgeDialog/contextproviders/RuneContextProvider.tsx
  apps/frontend/src/app/3_organisms/RuneBridgeDialog/hooks/useChainDetails.ts
  apps/frontend/src/app/3_organisms/RuneBridgeDialog/hooks/useRequestDepositAddress.tsx
  apps/frontend/src/app/3_organisms/RuneBridgeDialog/hooks/useRuneBridgeApiClient.ts
  apps/frontend/src/app/3_organisms/RuneBridgeDialog/hooks/useRuneBridgeLocked.ts
  apps/frontend/src/app/3_organisms/TransactionStepDialog/TransactionStepDialog.types.ts
  apps/frontend/src/app/3_organisms/TransactionStepDialog/components/TransactionStep/TransactionStep.tsx
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/utils/helpers.ts
  packages/contracts/src/contracts/protocol/bob.ts
  packages/contracts/src/contracts/protocol/bobTestnet.ts
Labels: enhancement

#894 Update APR tooltip copy on BOB pools
  apps/frontend/src/app/2_molecules/CurrentStatistics/CurrentStatistics.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/BobWIthdrawModal/BobWithdrawModal.tsx
  apps/frontend/src/locales/en/translations.json
Labels: enhancement

#895 Add claim LP maintenance state
  apps/frontend/src/app/5_pages/ClaimLpPage/ClaimLpPage.tsx
  apps/frontend/src/hooks/useMaintenance.ts
Labels: enhancement

#908 SOV-4075: POWA/RBTC Pool
  .changeset/eleven-toes-cross.md
  apps/frontend/src/app/5_pages/MarketMakingPage/MarketMakingPage.constants.ts
  packages/contracts/src/contracts/assets/icons/rsk/powa.ts
  packages/contracts/src/contracts/assets/rsk.ts
  packages/sdk/src/_tests/swaps/smart-router.test.ts
  packages/sdk/src/swaps/smart-router/routes/amm-swap-route.ts
Labels: enhancement

#898 SOV-4079: Fix staking extend timestamp
  .changeset/smooth-fans-divide.md
  apps/frontend/src/app/3_organisms/StakeForm/components/StakeDatePicker/StakeDatePicker.tsx
Labels: bug

#906 SOV-3813: Fix rounding issue on the dashboard
  .changeset/eleven-mangos-suffer.md
  apps/frontend/src/app/2_molecules/LOCStatus/LOCStatus.tsx
Labels: enhancement

#904 SOV-4139: BoB Spice leaderboard
  .changeset/quiet-spiders-dress.md
  .changeset/thirty-deers-wait.md
  apps/frontend/src/app/2_molecules/ConnectWalletMessage/ConnectWalletMessage.tsx
  apps/frontend/src/app/5_pages/ClaimLpPage/ClaimLpPage.tsx
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Leaderboard/components/BaseTable/BaseTable.tsx
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Leaderboard/components/BaseTable/components/ConnectWalletMessage/ConnectWalletMessage.tsx
  apps/frontend/src/app/5_pages/LeaderboardPointsPage/LeaderboardPointsPage.constants.tsx
  apps/frontend/src/app/5_pages/LeaderboardPointsPage/LeaderboardPointsPage.tsx
  apps/frontend/src/app/5_pages/LeaderboardPointsPage/LeaderboardPointsPage.types.ts
  apps/frontend/src/app/5_pages/LeaderboardPointsPage/LeaderboardPointsPage.utils.tsx
  apps/frontend/src/app/5_pages/LeaderboardPointsPage/components/BalanceRenderer/BalanceRenderer.tsx
  apps/frontend/src/app/5_pages/LeaderboardPointsPage/components/LeaderboardPointsFrame/LeaderboardPointsFrame.tsx
  apps/frontend/src/app/5_pages/LeaderboardPointsPage/data/usersDeposits.json
  apps/frontend/src/app/5_pages/LeaderboardPointsPage/data/usersPoints.json
  apps/frontend/src/app/5_pages/LeaderboardPointsPage/hooks/useGetPoints.ts
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/router.tsx
Labels: enhancement

#912 SOV-4157: Fix maximum value in AmountInput
  .changeset/nervous-mails-punch.md
  packages/ui/src/2_molecules/AmountInput/AmountInput.test.tsx
  packages/ui/src/2_molecules/AmountInput/AmountInput.tsx
Labels: bug

#910 SOV-3959: TEMP patch to prevent future LM "dead vestings"
  .changeset/sweet-stingrays-share.md
  apps/frontend/src/app/5_pages/RewardsPage/components/Staking/Staking.constants.tsx
Labels: bug, enhancement

#907 SOV-3922: fix typedData functionality for smart router
  .changeset/modern-boxes-enjoy.md
  apps/frontend/src/app/3_organisms/TransactionStepDialog/TransactionStepDialog.types.ts
  apps/frontend/src/app/3_organisms/TransactionStepDialog/components/TransactionSteps/TransactionSteps.tsx
  apps/frontend/src/app/3_organisms/TransactionStepDialog/helpers.ts
  apps/frontend/src/app/5_pages/ConvertPage/ConvertPage.constants.ts
  apps/frontend/src/app/5_pages/ConvertPage/hooks/useHandleConversion.ts
  apps/frontend/src/utils/graphql/bob/generated.tsx
  apps/frontend/src/utils/graphql/mynt/generated.tsx
  apps/frontend/src/utils/graphql/rsk/generated.tsx
  apps/frontend/src/utils/graphql/zero/generated.tsx
  apps/frontend/src/utils/transactions.ts
  packages/sdk/README.md
  packages/sdk/package.json
  packages/sdk/src/_tests/swaps/routes/moc-integration-route.test.ts
  packages/sdk/src/_tests/swaps/routes/zero-redemption-route.test.ts
  packages/sdk/src/swaps/smart-router/index.ts
  packages/sdk/src/swaps/smart-router/routes/moc-integration-swap-route.ts
  packages/sdk/src/swaps/smart-router/routes/zero-redemption-route.ts
  packages/sdk/src/swaps/smart-router/types.ts
  packages/sdk/src/swaps/smart-router/utils/permit.ts
  yarn.lock
Labels: bug

#915 SOV-3982: Fix button location Rewards page
  .changeset/eight-turkeys-study.md
  apps/frontend/src/app/5_pages/RewardsPage/components/StabilityPool/StabilityPool.tsx
  apps/frontend/src/app/5_pages/RewardsPage/components/Staking/Staking.tsx
  apps/frontend/src/app/5_pages/RewardsPage/components/Vesting/Vesting.tsx
  apps/frontend/src/app/5_pages/RewardsPage/components/Vesting/components/WithdrawButton/WithdrawButton.tsx
Labels: enhancement

#919 SOV-4161: Reset quote error
  .changeset/quick-pets-sort.md
  apps/frontend/src/app/5_pages/ConvertPage/ConvertPage.tsx
Labels: bug

#921 SOV-3938: Fix tooltip positioning
  .changeset/healthy-buses-think.md
  packages/ui/src/2_molecules/Tooltip/Tooltip.utils.ts
Labels: bug

#922 Bump fastbtc-in fees
  .changeset/afraid-cows-beg.md
  apps/frontend/src/app/3_organisms/FastBtcDialog/constants.ts
Labels: enhancement

#925 SOV-4154: Fix Ambient pools table
  .changeset/hip-cats-approve.md
  apps/frontend/src/contexts/CrocContext.tsx
Labels: bug

#926 SOV-4159: Add slashed SOV data to Staking history
  .changeset/old-ads-admire.md
  apps/frontend/src/app/3_organisms/StakingHistoryFrame/components/StakingWithdraws/StakingWithdraws.constants.tsx
  apps/frontend/src/app/3_organisms/StakingHistoryFrame/components/StakingWithdraws/StakingWithdraws.tsx
  apps/frontend/src/app/3_organisms/StakingHistoryFrame/components/StakingWithdraws/StakingWithdraws.types.ts
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/utils/graphql/bob/generated.tsx
  apps/frontend/src/utils/graphql/bob/schema.graphql
  apps/frontend/src/utils/graphql/mynt/generated.tsx
  apps/frontend/src/utils/graphql/rsk/generated.tsx
  apps/frontend/src/utils/graphql/rsk/operations/getStakingWithdraws.graphql
  apps/frontend/src/utils/graphql/rsk/schema.graphql
  apps/frontend/src/utils/graphql/zero/generated.tsx
Labels: enhancement
