Repository DistributedCollective/sovryn-dapp, pull requests merged in 2024-02, with the labels that each got.

#758 SOV-3719: Portfolio page Sovryn protocol section integration
  .changeset/famous-islands-compare.md
  apps/frontend/src/app/5_pages/PortfolioPage/PortfolioPage.tsx
  apps/frontend/src/app/5_pages/PortfolioPage/components/AssetSection/AssetSection.utils.ts
  apps/frontend/src/app/5_pages/PortfolioPage/components/AssetSection/components/AssetBalanceRow/AssetBalanceRow.tsx
  apps/frontend/src/app/5_pages/PortfolioPage/components/AssetSection/components/TotalAssetSection/TotalAssetSection.tsx
  apps/frontend/src/app/5_pages/PortfolioPage/components/ProtocolSection/components/ProtocolTvlSection/ProtocolTvlSection.tsx
Labels: chore

#757 SOV-3736: fix AMM pool “LP fee rate“
  .changeset/short-brooms-speak.md
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolStatistics/hooks/useGetConversionFee.ts
Labels: bug

#747 SOV-3590: fix promo card click
  .changeset/nice-bees-help.md
  apps/frontend/src/app/5_pages/MarketMakingPage/MarketMakingPage.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolsTable/PoolsTable.tsx
Labels: bug

#762 SOV-3561: Re-enable EIP-2612 support
  .changeset/green-scissors-hang.md
  apps/frontend/package.json
  apps/frontend/src/app/3_organisms/TransactionStepDialog/components/TransactionStep/TransactionStep.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/CloseCreditLine.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/AdjustCreditLine.tsx
  apps/frontend/src/app/3_organisms/ZeroLocForm/components/FormContent.tsx
  apps/frontend/src/app/5_pages/ConvertPage/ConvertPage.types.ts
  apps/frontend/src/app/5_pages/ConvertPage/ConvertPage.utils.ts
  apps/frontend/src/app/5_pages/ConvertPage/hooks/useHandleConversion.ts
  apps/frontend/src/app/5_pages/EarnPage/EarnPage.tsx
  apps/frontend/src/app/5_pages/EarnPage/EarnPage.types.ts
  apps/frontend/src/app/5_pages/EarnPage/hooks/useHandleStabilityDeposit.ts
  apps/frontend/src/app/5_pages/ZeroPage/constants.ts
  apps/frontend/src/app/5_pages/ZeroPage/hooks/useHandleTrove.ts
  apps/frontend/src/app/5_pages/ZeroPage/utils/trove-manager.ts
  apps/frontend/src/utils/helpers.ts
  apps/frontend/src/utils/transactions.ts
  packages/contracts/package.json
  packages/contracts/src/abis/mocIntegration.json
  packages/sdk/src/_tests/_fixtures/permit.ts
  packages/sdk/src/_tests/swaps/routes/moc-integration-route.test.ts
  packages/sdk/src/swaps/smart-router/routes/moc-integration-swap-route.ts
  packages/sdk/src/swaps/smart-router/types.ts
  yarn.lock
Labels: enhancement

#741 Portfolio Page
  .changeset/famous-islands-compare.md
  apps/frontend/src/app/2_molecules/ConnectWalletButton/ConnectWalletButton.tsx
  apps/frontend/src/app/3_organisms/FastBtcDialog/FastBtcDialog.tsx
  apps/frontend/src/app/3_organisms/SharedStateProvider/SharedStateProvider.tsx
  apps/frontend/src/app/5_pages/PortfolioPage/PortfolioPage.tsx
  apps/frontend/src/app/5_pages/PortfolioPage/components/AssetSection/AssetSection.constants.ts
  apps/frontend/src/app/5_pages/PortfolioPage/components/AssetSection/AssetSection.tsx
  apps/frontend/src/app/5_pages/PortfolioPage/components/AssetSection/components/AssetBalanceRow/AssetBalanceRow.module.css
  apps/frontend/src/app/5_pages/PortfolioPage/components/AssetSection/components/AssetBalanceRow/AssetBalanceRow.tsx
  apps/frontend/src/app/5_pages/PortfolioPage/components/AssetSection/components/AssetSectionActions/AssetSectionActions.tsx
  apps/frontend/src/app/5_pages/PortfolioPage/components/ProtocolSection/ProtocolSection.tsx
  apps/frontend/src/app/5_pages/PortfolioPage/components/ProtocolSection/ProtocolSection.types.ts
  apps/frontend/src/app/5_pages/PortfolioPage/components/ProtocolSection/ProtocolSection.utils.tsx
  apps/frontend/src/app/5_pages/PortfolioPage/components/ProtocolSection/components/DepositRow/DepositRow.tsx
  apps/frontend/src/app/5_pages/PortfolioPage/components/ProtocolSection/components/ProtocolDepositSection/ProtocolDepositSection.tsx
  apps/frontend/src/app/5_pages/PortfolioPage/components/ProtocolSection/components/ProtocolDepositSection/components/LendingTotalValue/LendingTotalValue.tsx
  apps/frontend/src/app/5_pages/PortfolioPage/components/ProtocolSection/components/ProtocolDepositSection/components/LendingTotalValue/components/LendingPoolBalance.tsx
  apps/frontend/src/app/5_pages/PortfolioPage/components/ProtocolSection/components/ProtocolDepositSection/components/MarketMakingTotalValue/MarketMakingTotalValue.tsx
  apps/frontend/src/app/5_pages/PortfolioPage/components/ProtocolSection/components/ProtocolDepositSection/components/MarketMakingTotalValue/components/MarketMakingPoolBalance.tsx
  apps/frontend/src/app/5_pages/PortfolioPage/components/ProtocolSection/components/ProtocolDepositSection/components/StabilityPoolTotalValue/StabilityPoolTotalValue.tsx
  apps/frontend/src/app/5_pages/PortfolioPage/components/ProtocolSection/components/ProtocolDepositSection/components/StakingTotalValue/StakingTotalValue.tsx
  apps/frontend/src/app/5_pages/PortfolioPage/components/ProtocolSection/components/ProtocolDepositSection/components/StakingTotalValue/components/VestingTypeValue/VestingTypeValue.tsx
  apps/frontend/src/app/5_pages/PortfolioPage/components/ProtocolSection/components/ProtocolDepositSection/components/ZeroLineTotalValue/ZeroLineTotalValue.tsx
  apps/frontend/src/app/5_pages/PortfolioPage/components/ProtocolSection/components/ProtocolRewardsSection/ProtocolRewardsSection.tsx
  apps/frontend/src/app/5_pages/PortfolioPage/components/ProtocolSection/components/ProtocolTotalSection/ProtocolTotalSection.tsx
  apps/frontend/src/assets/images/convert.svg
  apps/frontend/src/assets/images/deposit.svg
  apps/frontend/src/assets/images/withdraw.svg
  apps/frontend/src/constants/tokens.ts
  apps/frontend/src/hooks/useDollarValue.ts
  apps/frontend/src/hooks/useTokenDetailsByAsset.ts
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/router.tsx
  apps/frontend/src/store/rxjs/shared-state.ts
Labels: enhancement

#767 Fix missing prefix in AmountRenderer when countUp prop is used
  .changeset/fuzzy-pans-confess.md
  apps/frontend/src/app/2_molecules/AmountRenderer/AmountRenderer.tsx
  apps/frontend/src/app/5_pages/PortfolioPage/components/AssetSection/components/AssetBalanceRow/AssetBalanceRow.tsx
Labels: bug

#764 SOV-3775: New lending assets
  apps/frontend/src/app/5_pages/BorrowPage/components/BorrowAssetsTable/BorrowAssetsTable.constants.tsx
  apps/frontend/src/app/5_pages/BorrowPage/components/BorrowAssetsTable/BorrowAssetsTable.tsx
  apps/frontend/src/app/5_pages/LendPage/components/AdjustModal/AdjustLendingModalContainer.tsx
  apps/frontend/src/app/5_pages/LendPage/components/LendFrame/components/LendFrameAction/LendFrameAction.tsx
  apps/frontend/src/app/5_pages/LendPage/components/LendModal/LendingModalContainer.tsx
  apps/frontend/src/utils/LendingPoolDictionary.ts
  packages/contracts/src/contracts/lend-tokens/rsk.ts
  packages/contracts/src/contracts/loan-tokens/rsk.ts
  packages/contracts/src/contracts/loan-tokens/rskTestnet.ts
Labels: enhancement

#776 SOV-3830: Initial setup
  apps/frontend/src/app/2_molecules/CTA/CTA.tsx
  apps/frontend/src/app/3_organisms/Header/Header.tsx
  apps/frontend/src/app/5_pages/LandingPage/components/QuickLaunch/QuickLaunch.tsx
  apps/frontend/src/app/5_pages/LeaderboardPage/LeaderboardPage.tsx
  apps/frontend/src/assets/images/Leaderboard/social.svg
  apps/frontend/src/assets/images/Leaderboard/stake.svg
  apps/frontend/src/assets/images/Leaderboard/trade.svg
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/router.tsx
Labels: enhancement

#775 SOV-3653: Fix LP rewards
  .changeset/spotty-countries-pay.md
  apps/frontend/src/app/5_pages/MarketMakingPage/components/AdjustAndDepositModal/components/NewPoolStatistics/NewPoolStatistics.tsx
Labels: bug

#783 SOV-3869: Portfolio - add ZUSD and update Protocol Deposits title
  .changeset/nasty-shoes-roll.md
  apps/frontend/src/app/5_pages/PortfolioPage/components/AssetSection/AssetSection.constants.ts
  apps/frontend/src/app/5_pages/PortfolioPage/components/ProtocolSection/ProtocolSection.tsx
  apps/frontend/src/locales/en/translations.json
Labels: enhancement

#781 SOV-3855: Social leaderboard
  apps/frontend/src/app/5_pages/LeaderboardPage/LeaderboardPage.tsx
  apps/frontend/src/app/5_pages/LeaderboardPage/components/CTALinks/CTALinks.tsx
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Intro/Intro.tsx
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Leaderboard/Leaderboard.constants.tsx
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Leaderboard/Leaderboard.tsx
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Leaderboard/components/SocialLeaderboard/SocialLeaderboard.tsx
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Leaderboard/components/StakingLeaderboard/StakingLeaderboard.tsx
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Leaderboard/components/TradingLeaderboard/TradingLeaderboard.tsx
Labels: enhancement

#774 Trade
  .changeset/mighty-geckos-vanish.md
  .changeset/smooth-bikes-hear.md
  apps/frontend/src/app/5_pages/BorrowPage/components/BorrowAssetsTable/BorrowAssetsTable.constants.tsx
  apps/frontend/src/app/5_pages/BorrowPage/components/BorrowAssetsTable/BorrowAssetsTable.tsx
  apps/frontend/src/app/5_pages/LendPage/components/AdjustModal/AdjustLendingModalContainer.tsx
  apps/frontend/src/app/5_pages/LendPage/components/LendFrame/components/LendFrameAction/LendFrameAction.tsx
  apps/frontend/src/app/5_pages/LendPage/components/LendModal/LendingModalContainer.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/MarketMakingPage.constants.ts
  apps/frontend/src/app/5_pages/MarketMakingPage/abis/LiquidityPoolV1Converter.json
  apps/frontend/src/app/5_pages/MarketMakingPage/abis/LiquidityPoolV2Converter.json
  apps/frontend/src/app/5_pages/MarketMakingPage/components/AdjustAndDepositModal/AdjustAndDepositModal.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/AdjustAndDepositModal/components/NewPoolStatistics/NewPoolStatistics.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/AdjustAndDepositModal/hooks/useGetMaxDeposit.ts
  apps/frontend/src/app/5_pages/MarketMakingPage/components/AdjustAndDepositModal/hooks/useGetPoolBalance.ts
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolStatistics/PoolStatistics.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolStatistics/hooks/useGetConversionFee.ts
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolsTable/components/CurrentBalance/CurrentBalance.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolsTable/components/PoolsTableAction/PoolsTableAction.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolsTable/components/PoolsTableLiquidity/PoolsTableLiquidity.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolsTable/components/PoolsTableReturns/PoolsTableReturns.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/hooks/useGetPoolLiquidity.ts
  apps/frontend/src/app/5_pages/MarketMakingPage/hooks/useGetReturnRate.ts
  apps/frontend/src/app/5_pages/MarketMakingPage/hooks/useGetUserInfo.ts
  apps/frontend/src/app/5_pages/MarketMakingPage/hooks/useHandleMarketMaking.ts
  apps/frontend/src/app/5_pages/MarketMakingPage/utils/AmmLiquidityPool.ts
  apps/frontend/src/app/5_pages/PortfolioPage/components/AssetSection/AssetSection.constants.ts
  apps/frontend/src/constants/gasLimits.ts
  apps/frontend/src/constants/tokens.ts
  apps/frontend/src/utils/LendingPoolDictionary.ts
  packages/contracts/src/contracts/lend-tokens/rsk.ts
  packages/contracts/src/contracts/loan-tokens/rsk.ts
  packages/contracts/src/contracts/loan-tokens/rskTestnet.ts
  packages/contracts/src/tokenDetails/logos/fish.ts
  packages/sdk/src/_tests/swaps/smart-router.test.ts
  packages/sdk/src/constants.ts
  packages/sdk/src/swaps/smart-router/routes/amm-swap-route.ts
Labels: enhancement

#785 SOV-3856, SOV-3857: Trading and staking leaderboard
  apps/frontend/src/app/5_pages/LandingPage/components/TitleSection/TitleSection.tsx
  apps/frontend/src/app/5_pages/LeaderboardPage/LeaderboardPage.tsx
  apps/frontend/src/app/5_pages/LeaderboardPage/components/CTALinks/CTALinks.tsx
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Intro/Intro.tsx
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Leaderboard/Leaderboard.constants.tsx
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Leaderboard/Leaderboard.tsx
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Leaderboard/Leaderboard.types.ts
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Leaderboard/components/Badges/Badges.tsx
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Leaderboard/components/Badges/Badges.utils.ts
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Leaderboard/components/BaseTable/BaseTable.constants.tsx
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Leaderboard/components/BaseTable/BaseTable.tsx
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Leaderboard/components/BaseTable/BaseTable.types.ts
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Leaderboard/components/BaseTable/BaseTable.utils.tsx
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Leaderboard/components/BaseTable/components/ConnectWalletMessage/ConnectWalletMessage.tsx
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Leaderboard/components/BaseTable/hooks/useGetData.ts
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Leaderboard/components/SocialLeaderboard/SocialLeaderboard.constants.ts
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Leaderboard/components/SocialLeaderboard/SocialLeaderboard.tsx
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Leaderboard/components/StakingLeaderboard/StakingLeaderboard.tsx
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Leaderboard/components/TradingLeaderboard/TradingLeaderboard.tsx
  apps/frontend/src/app/5_pages/LeaderboardPage/components/PointsSection/PointsSection.tsx
  apps/frontend/src/hooks/useHandlePagination.ts
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/utils/helpers.ts
  packages/ui/src/1_atoms/Accordion/Accordion.tsx
  packages/ui/src/1_atoms/Badge/Badge.module.css
  packages/ui/src/1_atoms/Badge/Badge.types.ts
  packages/ui/src/2_molecules/Table/Table.types.ts
  packages/ui/src/2_molecules/Table/components/TableMobile/TableMobile.tsx
  packages/ui/src/2_molecules/Table/components/TableMobile/components/TableMobileRow.tsx
  packages/ui/src/2_molecules/Tabs/Tabs.tsx
Labels: enhancement

#787 SOV-3847: Lend and borrow section
  .changeset/little-socks-tie.md
  apps/frontend/src/app/5_pages/ProtocolDataPage/ProtocolDataPage.constants.ts
  apps/frontend/src/app/5_pages/ProtocolDataPage/components/LendAndBorrow/LendAndBorrow.constants.tsx
  apps/frontend/src/app/5_pages/ProtocolDataPage/components/LendAndBorrow/LendAndBorrow.tsx
  apps/frontend/src/locales/en/translations.json
  packages/ui/src/2_molecules/Table/Table.types.ts
  packages/ui/src/2_molecules/Table/components/TableMobile/TableMobile.tsx
  packages/ui/src/2_molecules/Table/components/TableMobile/components/TableMobileRow.tsx
Labels: enhancement

#790 SOV-3918: Leaderboard adjustments
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Leaderboard/Leaderboard.types.ts
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Leaderboard/components/Badges/Badges.utils.ts
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Leaderboard/components/BaseTable/BaseTable.constants.tsx
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Leaderboard/components/BaseTable/BaseTable.tsx
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Leaderboard/components/BaseTable/BaseTable.utils.tsx
  apps/frontend/src/app/5_pages/LeaderboardPage/components/Leaderboard/components/BaseTable/hooks/useGetData.ts
  apps/frontend/src/locales/en/translations.json
Labels: enhancement

#784 SOV-3823: Fix markdown display on Bitocracy
  .changeset/light-ears-dream.md
  apps/frontend/src/app/5_pages/BitocracyPage/components/NewProposalForm/components/ProposalDataForm/ProposalDataForm.tsx
  apps/frontend/src/app/5_pages/BitocracyPage/components/ProposalTitle/ProposalTitle.tsx
  apps/frontend/src/app/5_pages/ProposalPage/ProposalPage.tsx
  apps/frontend/src/app/5_pages/ProposalPage/ProposalPage.utils.ts
  apps/frontend/src/app/5_pages/ProposalPage/components/ProposalInfo/ProposalInfo.module.css
  apps/frontend/src/app/5_pages/ProposalPage/components/ProposalInfo/ProposalInfo.tsx
Labels: bug

#777 SOV-3827: Protocol Data Page
  .changeset/clever-adults-bathe.md
  .changeset/little-socks-tie.md
  .changeset/nervous-windows-kneel.md
  .changeset/olive-dolphins-repair.md
  .changeset/tame-beans-travel.md
  apps/frontend/public/index.html
  apps/frontend/src/app/2_molecules/AssetRenderer/AssetRenderer.tsx
  apps/frontend/src/app/3_organisms/Footer/Footer.tsx
  apps/frontend/src/app/5_pages/ConvertPage/ConvertPage.tsx
  apps/frontend/src/app/5_pages/LandingPage/components/ProtocolData/ProtocolData.constants.ts
  apps/frontend/src/app/5_pages/LandingPage/components/ProtocolData/ProtocolData.tsx
  apps/frontend/src/app/5_pages/LandingPage/components/ProtocolData/ProtocolData.types.ts
  apps/frontend/src/app/5_pages/LandingPage/components/ProtocolData/hooks/useGetData.ts
  apps/frontend/src/app/5_pages/MarketMakingPage/MarketMakingPage.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolsTable/components/CurrentBalance/CurrentBalance.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/PoolsTable/components/PoolsTableLiquidity/PoolsTableLiquidity.tsx
  apps/frontend/src/app/5_pages/PortfolioPage/components/AssetSection/components/AssetBalanceRow/AssetBalanceRow.tsx
  apps/frontend/src/app/5_pages/ProtocolDataPage/ProtocolData.constants.ts
  apps/frontend/src/app/5_pages/ProtocolDataPage/ProtocolDataPage.constants.ts
  apps/frontend/src/app/5_pages/ProtocolDataPage/ProtocolDataPage.tsx
  apps/frontend/src/app/5_pages/ProtocolDataPage/components/EcosystemStatistics/EcosystemStatistics.tsx
  apps/frontend/src/app/5_pages/ProtocolDataPage/components/EcosystemStatistics/EcosystemStatistics.types.ts
  apps/frontend/src/app/5_pages/ProtocolDataPage/components/LendAndBorrow/LendAndBorrow.constants.tsx
  apps/frontend/src/app/5_pages/ProtocolDataPage/components/LendAndBorrow/LendAndBorrow.module.css
  apps/frontend/src/app/5_pages/ProtocolDataPage/components/LendAndBorrow/LendAndBorrow.tsx
  apps/frontend/src/app/5_pages/ProtocolDataPage/components/MarketMaking/MarketMaking.constants.tsx
  apps/frontend/src/app/5_pages/ProtocolDataPage/components/MarketMaking/MarketMaking.tsx
  apps/frontend/src/app/5_pages/ProtocolDataPage/components/MarketMaking/MarketMaking.types.ts
  apps/frontend/src/app/5_pages/ProtocolDataPage/components/MarketMaking/components/PoolBalance/PoolBalance.tsx
  apps/frontend/src/app/5_pages/ProtocolDataPage/components/PricesBy24hChange/PricesBy24hChange.constants.tsx
  apps/frontend/src/app/5_pages/ProtocolDataPage/components/PricesBy24hChange/PricesBy24hChange.module.css
  apps/frontend/src/app/5_pages/ProtocolDataPage/components/PricesBy24hChange/PricesBy24hChange.tsx
  apps/frontend/src/app/5_pages/ProtocolDataPage/components/PricesBy24hChange/PricesBy24hChange.types.ts
  apps/frontend/src/app/5_pages/ProtocolDataPage/components/PricesBy24hChange/PricesBy24hChange.utils.ts
  apps/frontend/src/app/5_pages/ProtocolDataPage/components/PricesBy24hChange/components/PriceChange.tsx
  apps/frontend/src/app/5_pages/ProtocolDataPage/components/PricesBy24hChange/hooks/useGetAssetData.ts
  apps/frontend/src/app/5_pages/ProtocolDataPage/components/PricesBy24hChange/hooks/useGetCryptoPairs.ts
  apps/frontend/src/app/5_pages/ProtocolDataPage/components/SectionLinks/SectionLinks.tsx
  apps/frontend/src/locales/en/translations.json
  apps/frontend/src/router.tsx
  packages/ui/src/1_atoms/Icon/Icon.types.ts
  packages/ui/src/1_atoms/Icon/iconSvgPaths.ts
  packages/ui/src/2_molecules/Table/Table.types.ts
  packages/ui/src/2_molecules/Table/components/TableDesktop/TableDesktop.tsx
  packages/ui/src/2_molecules/Table/components/TableMobile/TableMobile.tsx
  packages/ui/src/2_molecules/Table/components/TableMobile/components/TableMobileRow.tsx
  packages/ui/src/2_molecules/Tooltip/Tooltip.tsx
Labels: enhancement, do-not-merge
