Repository DistributedCollective/sovryn-dapp, pull requests merged in 2024-06, with the labels that each got.

#931 SOV-4193: Fix hardcoded conversion
  .changeset/ninety-snakes-remain.md
  apps/frontend/src/app/5_pages/ConvertPage/ConvertPage.utils.ts
  apps/frontend/src/app/5_pages/PortfolioPage/components/ProtocolSection/components/ProtocolDepositSection/components/StakingTotalValue/StakingTotalValue.tsx
Labels: bug

#905 SOV-4068: User positions refreshes each block
  apps/frontend/src/app/3_organisms/TransactionStepDialog/TransactionStepDialog.tsx
  apps/frontend/src/app/3_organisms/TransactionStepDialog/components/TransactionSteps/TransactionSteps.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/AmbientMarketMaking/components/AmbientPoolsTable/components/AmbientPoolDeposit/AmbientPoolDeposit.tsx
  apps/frontend/src/app/5_pages/MarketMakingPage/components/AmbientMarketMaking/hooks/useAmbientPositions.ts
  apps/frontend/src/app/5_pages/MarketMakingPage/components/AmbientMarketMaking/hooks/useGetAmbientPositions.ts
  apps/frontend/src/contexts/TransactionContext.tsx
  apps/frontend/src/hooks/useCachedData.ts
Labels: enhancement

#933 SOV-4219: update OSSOV label
  .changeset/stale-spies-know.md
  apps/frontend/src/locales/en/translations.json
Labels: bug

#936 SOV-4199: Fix mobile layout
  .changeset/kind-candles-add.md
  apps/frontend/src/app/3_organisms/Header/Header.tsx
  apps/frontend/src/app/3_organisms/Header/components/BridgeMenuItem/BridgeMenuItem.tsx
  packages/ui/src/2_molecules/Header/Header.module.css
Labels: bug

#935 SOV-4240: update tiledesk version
  .changeset/silver-seahorses-sleep.md
  apps/frontend/public/index.html
Labels: enhancement

#939 SOV-4239: sdex logger
  .changeset/little-avocados-buy.md
  apps/frontend/.env.example
  packages/sdex/package.json
  packages/sdex/src/index.ts
  packages/sdex/src/logger.ts
  packages/sdex/src/swap.ts
  packages/sdk/src/swaps/smart-router/utils/ambient-utils.ts
  yarn.lock
Labels: enhancement

#942 SOV-4252: bitlayer network support
  apps/frontend/src/config/chains.ts
  apps/frontend/src/constants/infrastructure/bitlayer.ts
  packages/contracts/src/contracts/assets/bitlayer.ts
  packages/contracts/src/contracts/assets/bitlayerTestnet.ts
  packages/contracts/src/contracts/assets/index.ts
  packages/ethers-provider/src/chains.ts
  packages/ethers-provider/src/networks.ts
Labels: enhancement

#941 SOV-4255: Multichain logic cleanup
  .changeset/nice-rivers-run.md
  apps/frontend/src/app/3_organisms/ConversionsHistoryFrame/ConvertHistory.tsx
  apps/frontend/src/app/3_organisms/ConversionsHistoryFrame/ConvertHistory.utils.ts
  apps/frontend/src/app/3_organisms/EarnHistoryFrame/EarnHistory.tsx
  apps/frontend/src/app/3_organisms/Header/components/BridgeMenuItem/BridgeMenuItem.tsx
  apps/frontend/src/app/3_organisms/Header/components/BridgeMenuItem/BridgeMenuItem.utils.ts
  apps/frontend/src/app/3_organisms/RuneBridgeDialog/RuneBridgeDialog.utils.ts
  apps/frontend/src/app/3_organisms/RuneBridgeDialog/hooks/useRuneBridgeApiClient.ts
  apps/frontend/src/app/5_pages/PortfolioPage/components/ProtocolSection/ProtocolSection.utils.tsx
  apps/frontend/src/app/5_pages/PortfolioPage/components/ProtocolSection/components/ProtocolDepositSection/components/StakingTotalValue/StakingTotalValue.tsx
  apps/frontend/src/app/5_pages/PortfolioPage/components/ProtocolSection/components/ProtocolDepositSection/components/StakingTotalValue/StakingTotalValue.utils.ts
  apps/frontend/src/app/5_pages/StakePage/components/StakingStatistics/StakingStatistics.tsx
  apps/frontend/src/hooks/useGetNativeTokenPrice.ts
Labels: chore

#943 SOV-4259: Migrate from lodash.set to lodash
  .changeset/fluffy-hats-pull.md
  apps/frontend/package.json
  apps/frontend/public/release.json
  packages/contracts/package.json
  packages/contracts/src/utils/global.ts
  yarn.lock
Labels: bug

#940 SOV-4249: BoB Spice leaderboard - adding new column
  .changeset/eleven-swans-explain.md
  apps/frontend/src/app/5_pages/LeaderboardPointsPage/LeaderboardPointsPage.constants.tsx
  apps/frontend/src/app/5_pages/LeaderboardPointsPage/LeaderboardPointsPage.types.ts
  apps/frontend/src/app/5_pages/LeaderboardPointsPage/LeaderboardPointsPage.utils.tsx
  apps/frontend/src/app/5_pages/LeaderboardPointsPage/data/usersExtraPoints.json
  apps/frontend/src/app/5_pages/LeaderboardPointsPage/hooks/useGetPoints.ts
  apps/frontend/src/locales/en/translations.json
Labels: enhancement
